import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
    'en-US': {
        'title-dashboard': 'Farm Dashboard',
        'title-trade': 'Smart Trade',
        'title-disease': 'Disease Scanner',
        'title-advisory': 'Expert Advisory',
        'logo': 'Cattle Care',
        'nav-dashboard': 'Dashboard',
        'nav-trade': 'Smart Trade',
        'nav-disease': 'Disease Scanner',
        'nav-advisory': 'Advisory',
        'nav-cows': 'My Cattle',
        'nav-services': 'Services',
        'nav-alerts': 'Alerts',
        'nav-settings': 'Settings',
        'alerts-title': 'Alerts & Notifications',
        'alerts-subtitle': 'Critical updates about your herd.',
        'alerts-empty': 'No new alerts.',
        'settings-title': 'Settings',
        'settings-subtitle': 'Manage your account and app preferences.',
        'stg-account': 'Farmer Account',
        'stg-signout': 'Sign Out',
        'stg-pref': 'Preferences',
        'stg-lang': 'Language',
        'stg-theme': 'Theme',
        'stg-notif': 'Notifications',
        'stg-push': 'Push Notifications',
        'stg-email': 'Email Alerts',
        'stg-security': 'Security',
        'stg-change-pw': 'Change Password',
        'stg-save': 'Save Changes',
        'grants-title': 'Government Grants',
        'grants-subtitle': 'Find available grants and subsidies for your farm.',
        'grants-new': 'Post New Grant (Admin)',
        'grants-schemes': 'Available Schemes',
        'grants-apply': 'Apply Now',
        'predict-title': 'Health Prediction AI',
        'predict-subtitle': 'Analyze vital signs to detect potential health issues.',
        'pred-enter-vitals': 'Enter Vitals',
        'pred-temp': 'Temperature (°C)',
        'pred-appetite': 'Appetite (1-10)',
        'pred-mobility': 'Mobility (1-10)',
        'pred-run': 'Run Prediction',
        'pred-analyzing': 'Analyzing...',
        'pred-result-placeholder': 'Enter vitals to see analysis result.',
        'pred-note': 'Note: This is an AI estimation. Please consult a vet for final diagnosis.',
        'cows-title': 'My Cattle',
        'cows-subtitle': 'Manage your herd registry and health status.',
        'btn-add-cow': 'Add New Cow',
        'hdr-herd-list': 'Herd List',
        'tbl-tag': 'Tag ID',
        'tbl-age': 'Age',
        'tbl-health': 'Health',
        'tbl-owner': 'Owner',
        'ph-tag': 'Tag ID',
        'ph-age': 'Age',
        'ph-owner': 'Owner',
        'opt-select-status': 'Select Status',
        'opt-healthy': 'Healthy',
        'opt-sick': 'Sick',
        'opt-pregnant': 'Pregnant',
        'srv-title': 'Our Services',
        'srv-subtitle': 'Comprehensive tools for modern cattle management.',
        'srv-health-hub': 'Health Hub',
        'srv-health-desc': 'AI prediction & disease scanning',
        'srv-trade': 'Smart Trade',
        'srv-trade-desc': 'Fair price estimation & market trends',
        'srv-advisory': 'Advisory',
        'srv-advisory-desc': 'Expert guidance & best practices',
        'srv-grants': 'Govt. Grants',
        'srv-grants-desc': 'Subsidy & financial aid information',
        'dash-active-trades': 'Active Trades',
        'dash-govt-grants': 'Govt Grants',
        'dash-health-ai': 'Health AI',
        'lbl-breed': 'Cattle Breed',
        'lbl-weight': 'Weight (kg)',
        'lbl-age': 'Age (Months)',
        'lbl-milk': 'Milk Yield (L/Day)',
        'lbl-preg': 'Pregnancy (Months)',
        'btn-calc': 'Calculate Price',
        'btn-scan': 'Scan Image',
        'total-cattle': 'Total Cattle',
        'health-alerts': 'Health Alerts',
        'market-rate': 'Avg. Local Rate',
        'weather': 'Weather',
        'recent-activity': 'Recent Activity',
        'opt-gir': 'Gir (Desi)',
        'opt-sahiwal': 'Sahiwal',
        'opt-redsindhi': 'Red Sindhi',
        'opt-tharparkar': 'Tharparkar',
        'opt-jersey': 'Jersey',
        'opt-holstein': 'Holstein Friesian',
        'opt-hfcross': 'HF Cross',
        'opt-murrah': 'Murrah Buffalo',
        'opt-unknown': 'Unknown / Other',

        // States
        'st-karnataka': 'Karnataka',
        'st-goa': 'Goa',
        'st-andhrapradesh': 'Andhra Pradesh',
        'st-telangana': 'Telangana',
        'st-tamilnadu': 'Tamil Nadu',
        'st-kerala': 'Kerala',
        'st-maharashtra': 'Maharashtra',
        'st-gujarat': 'Gujarat',
        'st-madhyapradesh': 'Madhya Pradesh',
        'st-uttarpradesh': 'Uttar Pradesh',
        'st-arunachalpradesh': 'Arunachal Pradesh',
        'st-assam': 'Assam',
        'st-bihar': 'Bihar',
        'st-chhattisgarh': 'Chhattisgarh',
        'st-haryana': 'Haryana',
        'st-himachalpradesh': 'Himachal Pradesh',
        'st-jharkhand': 'Jharkhand',
        'st-manipur': 'Manipur',
        'st-meghalaya': 'Meghalaya',
        'st-mizoram': 'Mizoram',
        'st-nagaland': 'Nagaland',
        'st-odisha': 'Odisha',
        'st-punjab': 'Punjab',
        'st-rajasthan': 'Rajasthan',
        'st-sikkim': 'Sikkim',
        'st-tripura': 'Tripura',
        'st-uttarakhand': 'Uttarakhand',
        'st-westbengal': 'West Bengal',

        // Dashboard Keys
        'subtitle-dashboard': 'Smart Farm Infrastructure & Management System',
        'status-db': 'DB Connected',
        'status-live': 'LIVE',
        'unit-kg': '/kg',
        'chart-milk': 'Milk Yield (Liters)',
        'disclaimer-gps': '*Based on your GPS location',
        'dash-infra': 'Farm Infrastructure',
        'dash-acres': 'Acres',
        'dash-sheds': 'Sheds',
        'dash-cctv': 'CCTV Live',
        'dash-feed': 'Feed Stock',
        'dash-water': 'Water Tank',
        'dash-trends': 'Production Trends',
        'dash-sick': 'Sick History (Records)',
        'dash-no-sick': 'No sick records found.',
        'dash-vets': 'Nearby Vet Hospitals',
        'dash-nav': 'Navigate',
        'dash-view-map': 'View All on Map',
        'trade-subtitle': 'AI-Powered Valuation & Certification',
        'grp-desi': 'Indian Indigenous (Desi)',
        'grp-exotic': 'Exotic / Cross',
        'opt-murrah': 'Murrah Buffalo',
        'msg-analyzing': 'AI Analyzing...',
        'hint-qr': 'Use Google Lens • Save Details Instantly',
        'lbl-forecast': '6-Month Forecast',
        'adv-critical': 'Critical Attention Needed. Contact Vet Immediately.',

        // Report / Certificate Keys
        'cert-title': 'Valuation Report',
        'cert-subtitle': 'Certified by Cattle Care AI',
        'cert-value': 'Estimated Fair Value',
        'cert-confidence': 'TVL Confidence',
        'cert-proof': 'Price Breakdown (Proof)',
        'cert-base': 'Base Weight Value',
        'cert-milk': 'Milk Yield Bonus',
        'cert-preg': 'Pregnancy Bonus',
        'cert-age': 'Age Depreciation',
        'cert-analysis': 'AI Expert Analysis',
        'cert-footer': 'Generated by Gemini AI • Verifiable Trace',
        'btn-download': 'Download Official PDF',
        'qr-scan': 'Scan to Save on Phone',

        // Advisory Chat Keys
        'step-1-title': 'Register Cattle',
        'step-1-desc': 'Add your herd details to the digital registry to start tracking.',
        'step-2-title': 'Monitor Health',
        'step-2-desc': 'Use AI Disease Scanner to ensure well-being.',
        'step-3-title': 'Access Services',
        'step-3-desc': 'Get fair trade prices, advisory, and government grants.',

        'adv-chat-placeholder': 'Type your question here...',
        'adv-chat-send': 'Send',
        'adv-welcome-msg': 'Namaste! I am your AI Veterinary Expert. How can I help your cattle today?',
        'adv-typing': 'Vet is typing...',

        'sys-mongo': 'In-Memory / Database',
        'sys-s1-subtitle': 'Infrastructure Overview',
        'sys-s1-desc-text': 'The platform is built on a high-concurrency architecture that bridges rural field data with state-of-the-art AI. We utilize a three-tier design strategy: **Edge Interaction**, **Scalable Backend**, and **Hybrid Intelligence Reasoning**. This direct alignment ensures our 4 core objectives are met with efficiency and security.',
        'sys-s1-p1-title': 'Rural-First Design',
        'sys-s1-p1-desc': 'Optimized for low-bandwidth zones with offline-first capabilities.',
        'sys-s1-p2-title': 'Intelligence Scalability',
        'sys-s1-p2-desc': 'Elastic compute resources for high-intensity vision and predictive tasks.',
        'sys-s1-p3-title': 'Data Security',
        'sys-s1-p3-desc': 'End-to-end encryption for all farmer data and cattle medical history.',
        'sys-farmers-desc': 'Omnichannel access via Mobile, Web, and Voice.',
        'sys-frontend-desc': 'Modern interface with Tailwind for fluid, responsive UI.',
        'sys-backend-desc': 'RESTful Microservices using Python gateway.',
        'sys-intelligence-desc': 'EfficientNet Vision + Gemini Semantic Reasoning.',
        'sys-datalayer-desc': 'Hybrid storage for profiles and time-series data.',
        'sys-header': 'Platform Demo',
        'sys-farmers': 'Farmers',
        'sys-frontend': 'Interface',
        'sys-backend': 'Engine',
        'sys-hybrid': 'Neural Core',
        'sys-datalayer': 'Knowledge Base',

        'sys-obj-header': 'Core Strategic Objectives',
        'sys-obj-1-t': 'Health Security',
        'sys-obj-1-d': 'AI-driven rapid disease detection to prevent herd loss.',
        'sys-obj-2-t': 'Fair Market Trade',
        'sys-obj-2-d': 'Algorithmic valuation ensuring fair prices for every farmer.',
        'sys-obj-3-t': 'Rural Accessibility',
        'sys-obj-3-d': 'Multilingual voice support bridging the digital divide.',
        'sys-obj-4-t': 'Data-Driven Insights',
        'sys-obj-4-d': 'Predictive analytics for milk yields and health forecasting.',
        'sys-obj-interaction': 'Through the **Interface**, farmers scan cattle for **Health Security**. Our **Neural Core** performs algorithmic valuation for **Fair Trade**, while **Voice AI** ensures **Accessibility**. All data feeds the **Knowledge Base** for **Predictive Insights**.',

        'meth-title-1': 'Methodology: Health Security',
        'meth-title-2': 'Methodology: Fair Market Trade',
        'meth-title-3': 'Methodology: Rural Accessibility',
        'meth-title-4': 'Methodology: Data-Driven Insights',
        'sys-view-meth': 'View Methodology →',

        'sys-s2-title': 'End-to-End Indic Multilingual Platform',
        'sys-s2-hybrid-title': 'IndicWav2Vec + Gemini Hybrid',
        'sys-s2-desc': 'A hybrid design combining **Pre-trained Acoustic Models** for phonetic decoding and **Gemini 1.5 Pro** for cross-lingual semantic reasoning.',
        'sys-s2-neural-stats': 'Neural Stats',
        'sys-s2-model': 'Model',
        'sys-s2-params': 'Params',
        'sys-s2-latency': 'Latency',
        'sys-s2-pipeline-title': 'Cross-Lingual Inference Pipeline',
        'sys-s2-raw-audio': 'Raw Audio',
        'sys-s2-feat-extract': 'Feature Extraction',
        'sys-s2-phoneme-map': 'IndicWav2Vec + Gemini',
        'sys-s2-action': 'Action',

        'sys-s3-title': 'Context-Aware Generative Reasoning',
        'sys-s3-role-prompt': 'Role-Based Prompt Engineering',
        'sys-s3-desc': 'Transforms a standard LLM into a specialized Veterinary or Nutrition expert by feeding it structured history and strict behavioral instructions.',
        'sys-s3-cog-func': 'Cognitive Functions',
        'sys-s3-persona-switch': 'Dynamic Persona Switching',
        'sys-s3-concise': 'Concise Output (Voice)',
        'sys-s3-pipe-title': 'Conversation Pipeline',
        'sys-s3-user-query': 'User Query',
        'sys-s3-ctx-engine': 'Context Engine',
        'sys-s3-gemini-llm': 'Gemini LLM',
        'sys-s3-expert-advice': 'Expert Advice',

        'sys-s4-title': 'Temporal Analytics & Forecasting Platform',
        'sys-s4-tft-title': 'Temporal Fusion Transformer',
        'sys-s4-desc': 'Powered by a **Multi-Horizon Quantile Recurrent Neural Network**. Uses **TFT** to forecast milk yields and **Isolation Forest** to detect real-time anomalies.',
        'sys-s4-model-specs': 'Model Specs',
        'sys-s4-forecasting': 'Forecasting',
        'sys-s4-horizon': 'Horizon',
        'sys-s4-error-rate': 'Error Rate',
        'sys-s4-pipe-title': 'Analytics Pipeline',
        'sys-s4-hist-data': 'Historical Data',
        'sys-s4-sliding-win': 'Sliding Window',
        'sys-s4-ensemble': 'Ensemble Core',
        'sys-s4-smart-insight': 'Smart Insights',

        // Disease Scanner
        'btn-camera': 'Open Camera',
        'btn-capture': 'Capture Photo',
        'btn-retake': 'Retake',
        'lbl-analyzing': 'AI is scanning the image...',
        'p-disease-guide': 'Point camera at the affected area (skin, eyes, mouth) for instant diagnosis.',

        // Disease Scanner V2 Keys
        'lbl-temperature': 'Temperature (°F)',
        'lbl-pregnancy': 'Pregnancy Status',
        'lbl-water': 'Water Intake (Liters)',
        'lbl-milk-yield': 'Milk Yield (Liters)',
        'lbl-nose': 'Running Nose?',
        'lbl-breath': 'Breathing Sound?',
        'lbl-history': 'Medical History',
        'lbl-diagnosis-basis': 'Basis of Diagnosis',
        'lbl-basis-desc': 'Why was this status chosen?',
        'opt-yes': 'Yes',
        'opt-no': 'No',
        'opt-abnormal': 'Abnormal / Heavy',

        // Skin Pre-Check
        'skin-check-title': 'Skin Health Pre-Check',
        'q-skin-rash': 'Do you see any rashes, pimples, or skin lesions?',
        'q-from-birth': 'Is this mark present from birth?',
        'q-skin-change': 'Has there been any recent change (size, color, bleeding)?',
        'msg-benign': 'Likely a benign birthmark. You may proceed to scan if you are still concerned.',
        'msg-consult': 'We recommend running a disease scan for accurate diagnosis.',
        'btn-continue': 'Continue',
        'btn-check-disease': 'Check Disease',

        // Advisory Voice
        'adv-tab-general': 'General Advisory',
        'adv-tab-nutrition': 'Nutrition Advisory',
        'adv-listening': 'Listening...',
        'adv-speak-now': 'Tap microphone and speak',
        'adv-processing': 'Thinking...',
        'adv-replying': 'Speaking...',
        'lbl-vet-dermatologist': 'AI-Powered Veterinary Dermatologist',
        'btn-upload-photo': 'Upload Photo',
        'btn-live-camera': 'Live Camera',
        'btn-remove': 'Remove',
        'btn-run-analysis': 'Run AI Analysis',
        'lbl-low-appetite': 'Low Appetite?',
        'ph-vitals-history': 'e.g. Previous infection in left leg...',
        'msg-connecting-gemini': 'Connecting to Gemini Vision...',
        'lbl-ai-recommendation': 'AI Recommendation',
        'lbl-detected': 'Detected',
        'lbl-confidence': 'Confidence',
        'lbl-ready-scan': 'Ready to Scan',
        'msg-upload-start': 'Upload a photo to start AI Analysis',
        'msg-complete-precheck': 'Complete the pre-check to enable scanning',
        'upload-text': 'Select Photo',
        'upload-instruction': 'Click to upload from gallery',
        'lbl-location': 'Location',
        'lbl-fever': 'Fever?',
        'lbl-high-fever': 'High Fever',
        'ph-age': 'e.g. 4',
        'ph-weight': 'kg',
        'ph-temp': '°F',
        'ph-milk': 'Liters',

        'lbl-vaccination': 'Vaccination Status',
        'lbl-lactation': 'Lactation Cycle (1-10)',
        'lbl-disease-hist': 'Disease History',
        'opt-vac-none': 'None / Unknown',
        'opt-vac-partial': 'Partially Vaccinated',
        'opt-vac-full': 'Fully Vaccinated',
        'dis-fmd': 'FMD (Hoof & Mouth)',
        'dis-mastitis': 'Mastitis',
        'dis-brucellosis': 'Brucellosis',

    },
    'hi-IN': {
        'title-dashboard': 'पशु फार्म डैशबोर्ड',
        'title-trade': 'व्यापार (स्मार्ट ट्रेड)',
        'title-disease': 'रोग जाँच (स्कैन)',
        'title-advisory': 'विशेषज्ञ सलाह',
        'logo': 'कैटल केयर',
        'nav-dashboard': 'डैशबोर्ड',
        'nav-trade': 'व्यापार',
        'nav-disease': 'रोग जाँच',
        'nav-advisory': 'सलाह',
        'nav-cows': 'पशु धन',
        'nav-services': 'सेवाएं',
        'nav-alerts': 'अलर्ट',
        'nav-settings': 'सेटिंग्स',
        'alerts-title': 'अलर्ट और सूचनाएं',
        'alerts-subtitle': 'आपके झुंड के बारे में महत्वपूर्ण अपडेट।',
        'alerts-empty': 'कोई नई सूचना नहीं।',
        'settings-title': 'सेटिंग्स',
        'settings-subtitle': 'अपने खाते और ऐप की प्राथमिकताओं को प्रबंधित करें।',
        'stg-account': 'किसान खाता',
        'stg-signout': 'साइन आउट',
        'stg-pref': 'प्राथमिकताएं',
        'stg-lang': 'भाषा',
        'stg-theme': 'थीम',
        'stg-notif': 'सूचनाएं',
        'stg-push': 'पुश नोटिफिकेशन',
        'stg-email': 'ईमेल अलर्ट',
        'stg-security': 'सुरक्षा',
        'stg-change-pw': 'पासवर्ड बदलें',
        'stg-save': 'परिवर्तन सहेजें',
        'grants-title': 'सरकारी अनुदान',
        'grants-subtitle': 'अपने खेत के लिए उपलब्ध अनुदान और सब्सिडी खोजें।',
        'grants-new': 'नया अनुदान (व्यवस्थापक)',
        'grants-schemes': 'उपलब्ध योजनाएं',
        'grants-apply': 'आवेदन करें',
        'predict-title': 'स्वास्थ्य भविष्यवाणी एआई',
        'predict-subtitle': 'संभावित स्वास्थ्य समस्याओं का पता लगाने के लिए महत्वपूर्ण संकेतों का विश्लेषण करें।',
        'pred-enter-vitals': 'वाइटल्स दर्ज करें',
        'pred-temp': 'तापमान (°C)',
        'pred-appetite': 'भूख (1-10)',
        'pred-mobility': 'गतिशीलता (1-10)',
        'pred-run': 'भविष्यवाणी करें',
        'pred-analyzing': 'विश्लेषण कर रहा है...',
        'pred-result-placeholder': 'परिणाम देखने के लिए वाइटल्स दर्ज करें।',
        'pred-note': 'नोट: यह एआई अनुमान है। कृपया अंतिम निदान के लिए पशु चिकित्सक से परामर्श करें।',
        'cows-title': 'मेरा पशुधन',
        'cows-subtitle': 'अपने झुंड रजिस्ट्री और स्वास्थ्य स्थिति का प्रबंधन करें।',
        'btn-add-cow': 'नई गाय जोड़ें',
        'hdr-herd-list': 'झुंड सूची',
        'tbl-tag': 'टैग आईडी',
        'tbl-age': 'उम्र',
        'tbl-health': 'स्वास्थ्य',
        'tbl-owner': 'मालिक',
        'ph-tag': 'टैग आईडी',
        'ph-age': 'उम्र',
        'ph-owner': 'मालिक',
        'opt-select-status': 'स्थिति चुनें',
        'opt-healthy': 'स्वस्थ',
        'opt-sick': 'बीमार',
        'opt-pregnant': 'गर्भवती',
        'srv-title': 'हमारी सेवाएं',
        'srv-subtitle': 'आधुनिक पशु प्रबंधन के लिए व्यापक उपकरण।',
        'srv-health-hub': 'स्वास्थ्य केंद्र',
        'srv-health-desc': 'एआई भविष्यवाणी और रोग स्कैनिंग',
        'srv-trade': 'स्मार्ट ट्रेड',
        'srv-trade-desc': 'उचित मूल्य अनुमान और बाजार के रुझान',
        'srv-advisory': 'सलाह',
        'srv-advisory-desc': 'विशेषज्ञ मार्गदर्शन और सर्वोत्तम प्रथाएं',
        'srv-grants': 'सरकारी अनुदान',
        'srv-grants-desc': 'सब्सिडी और वित्तीय सहायता जानकारी',
        'dash-active-trades': 'सक्रिय व्यापार',
        'dash-govt-grants': 'सरकारी अनुदान',
        'dash-health-ai': 'हेल्थ एआई',
        'lbl-breed': 'गाय की नस्ल',
        'lbl-weight': 'वजन (किग्रा)',
        'lbl-age': 'उम्र (महीने)',
        'lbl-milk': 'दूध (लीटर/दिन)',
        'lbl-preg': 'गर्भावस्था (महीने)',
        'btn-calc': 'कीमत बतायें',
        'btn-scan': 'स्कैन करें',
        'total-cattle': 'कुल पशु',
        'health-alerts': 'स्वास्थ्य अलर्ट',
        'market-rate': 'औसत स्थानीय दर',
        'weather': 'मौसम',
        'recent-activity': 'हाल की गतिविधि',
        'opt-gir': 'गिर (देसी)',
        'opt-sahiwal': 'साहीवाल',
        'opt-redsindhi': 'लाल सिंधी',
        'opt-tharparkar': 'थारपारकर',
        'opt-jersey': 'जर्सी',
        'opt-holstein': 'होलस्टीन',

        'dash-infra': 'फार्म इंफ्रास्ट्रक्चर',
        'subtitle-dashboard': 'स्मार्ट फार्म प्रबंधन प्रणाली',
        'status-db': 'DB कनेक्टेड',
        'status-live': 'लाईंव',
        'unit-kg': '/किग्रा',
        'chart-milk': 'दुग्ध उत्पादन (लीटर)',
        'disclaimer-gps': '*आपके जीपीएस स्थान पर आधारित',
        'dash-acres': 'एकड़',
        'dash-sheds': 'शेड',
        'dash-cctv': 'सीसीटीवी (लाइव)',
        'dash-feed': 'चारा भंडार',
        'dash-water': 'पानी की टंकी',
        'dash-trends': 'उत्पादन रुझान',
        'dash-sick': 'बीमारी का इतिहास',
        'dash-no-sick': 'कोई रिकॉर्ड नहीं मिला।',
        'dash-vets': 'निकटतम पशु चिकित्सक',
        'dash-nav': 'रास्ता देखें',
        'dash-view-map': 'मैप पर देखें',
        'trade-subtitle': 'AI संचालित मूल्यांकन और प्रमाणन',
        'grp-desi': 'भारतीय स्वदेशी (देसी)',
        'grp-exotic': 'विदेशी / संकर',
        'opt-murrah': 'मुर्रा भैंस',
        'msg-analyzing': 'AI विश्लेषण कर रहा है...',
        'hint-qr': 'Google Lens का उपयोग करें • विवरण तुरंत सहेजें',
        'lbl-forecast': '6-महीने का पूर्वानुमान',
        'adv-critical': 'गंभीर ध्यान देने की आवश्यकता है। तुरंत पशु चिकित्सक से संपर्क करें।',

        'cert-title': 'मूल्यांकन रिपोर्ट',
        'cert-subtitle': 'कैटल केयर AI द्वारा प्रमाणित',
        'cert-value': 'अनुमानित उचित मूल्य',
        'cert-confidence': 'सटीकता',
        'cert-proof': 'मूल्य का विवरण (प्रमाण)',
        'cert-base': 'वजन का मूल्य',
        'cert-milk': 'दूध का बोनस',
        'cert-preg': 'गर्भावस्था बोनस',
        'cert-age': 'उम्र की कटौती',
        'cert-analysis': 'AI विशेषज्ञ विश्लेषण',
        'cert-footer': 'जेमिनी AI द्वारा निर्मित • सत्यापित रिपोर्ट',
        'btn-download': 'PDF डाउनलोड करें',
        'qr-scan': 'फोन पर सेव करने के लिए स्कैन करें',

        'adv-chat-placeholder': 'अपना प्रश्न यहाँ लिखें...',
        'adv-chat-send': 'भेजें',
        'adv-welcome-msg': 'नमस्ते! मैं आपका एआई पशु चिकित्सक विशेषज्ञ हूँ। आज मैं आपकी कैसे सहायता कर सकता हूँ?',
        'adv-typing': 'विशेषज्ञ टाइप कर रहे हैं...',

        // Dashboard Steps
        'step-1-title': 'पशु पंजीकरण',
        'step-1-desc': 'ट्रैकिंग शुरू करने के लिए अपने झुंड का विवरण जोड़ें।',
        'step-2-title': 'स्वास्थ्य निगरानी',
        'step-2-desc': 'कल्याण सुनिश्चित करने के लिए एआई रोग स्कैनर का उपयोग करें।',
        'step-3-title': 'सेवाएं',
        'step-3-desc': 'उचित व्यापार मूल्य और सरकारी अनुदान प्राप्त करें।',

        // Advisory Tabs
        'adv-tab-general': 'सामान्य सलाह',
        'adv-tab-nutrition': 'पोषण सलाह',

        'btn-camera': 'कैमरा खोलें',
        'btn-capture': 'फोटो लें',
        'btn-retake': 'दूबारा लें',
        'lbl-analyzing': 'AI छवि को स्कैन कर रहा है...',
        'p-disease-guide': 'त्वरित निदान के लिए कैमरे को प्रभावित क्षेत्र (त्वचा, आंखें, मुंह) की ओर इंगित करें।',
        'skin-check-title': 'त्वचा स्वास्थ्य पूर्व-जांच',
        'q-skin-rash': 'क्या आपको कोई चकत्ते, मुंहासे या त्वचा के घाव दिखाई देते हैं?',
        'q-from-birth': 'क्या यह निशान जन्म से ही मौजूद है?',
        'q-skin-change': 'क्या हाल ही में कोई बदलाव (आकार, रंग, रक्तस्राव) हुआ है?',
        'msg-benign': 'संभावना है कि यह जन्मजात निशान है। यदि आप अभी भी चिंतित हैं तो आप स्कैन कर सकते हैं।',
        'msg-consult': 'हम सटीक निदान के लिए रोग स्कैन चलाने की सलाह देते हैं।',
        'btn-continue': 'जारी रखें',
        'btn-check-disease': 'रोग की जाँच करें',
        'opt-yes': 'हाँ',
        'opt-no': 'नहीं',
        'lbl-vet-dermatologist': 'एआई-संचालित पशु चिकित्सा त्वचा विशेषज्ञ',
        'btn-upload-photo': 'फोटो अपलोड करें',
        'btn-live-camera': 'लाइव कैमरा',
        'btn-remove': 'हटाएं',
        'btn-run-analysis': 'एआई विश्लेषण चलाएं',
        'lbl-low-appetite': 'कम भूख?',
        'ph-vitals-history': 'जैसे: बाएं पैर में पिछला संक्रमण...',
        'msg-connecting-gemini': 'जेमिनी विजन से जुड़ रहा है...',
        'lbl-ai-recommendation': 'एआई सिफारिश',
        'lbl-detected': 'पता चला',
        'lbl-confidence': 'विश्वास',
        'lbl-ready-scan': 'स्कैन के लिए तैयार',
        'msg-upload-start': 'एआई विश्लेषण शुरू करने के लिए एक फोटो अपलोड करें',
        'msg-complete-precheck': 'स्कैनिंग सक्षम करने के लिए पूर्व-जांच पूरी करें',
        'upload-text': 'फोटो चुनें',
        'upload-instruction': 'गैलरी से अपलोड करने के लिए क्लिक करें',
        'lbl-location': 'स्थान',
        'lbl-temperature': 'तापमान (°F)',
        'lbl-pregnancy': 'गर्भावस्था की स्थिति',
        'lbl-milk-yield': 'दूध की उपज (लीटर)',
        'lbl-nose': 'नाक बह रही है?',
        'lbl-breath': 'सांस की आवाज?',
        'lbl-history': 'चिकित्सा इतिहास',
        'lbl-fever': 'बुखार?',
        'lbl-high-fever': 'तेज बुखार',
        'ph-age': 'जैसे: 4',
        'ph-weight': 'किग्रा',
        'ph-temp': '°F',
        'ph-milk': 'लीटर',

        'lbl-vaccination': 'टीकाकरण की स्थिति',
        'lbl-lactation': 'दुग्ध चक्र (1-10)',
        'lbl-disease-hist': 'बीमारी का इतिहास',
        'opt-vac-none': 'कोई नहीं / अज्ञात',
        'opt-vac-partial': 'आंशिक रूप से टीका लगाया गया',
        'opt-vac-full': 'पूरी तरह से टीका लगाया गया',
        'dis-fmd': 'खुरपका-मुंहपका (FMD)',
        'dis-mastitis': 'थनैला रोग (Mastitis)',
        'dis-brucellosis': 'ब्रूसीलोसिस',


        // System Demo Keys
        'sys-header': 'प्लेटफॉर्म डेमो',
        'sys-s1-title': 'नवाचार रणनीति और मुख्य कार्यप्रवाह',
        'sys-farmers': 'किसान',
        'sys-frontend': 'इंटरफ़ेस परत',
        'sys-backend': 'निर्णय इंजन',
        'sys-hybrid': 'न्यूरल कोर',
        'sys-datalayer': 'ज्ञान आधार',
        'sys-mobile-web': 'मल्टी-मोडल इंटरेक्शन',
        'sys-react-vite': 'रेस्पॉन्सिव रिएक्ट इकोसिस्टम',
        'sys-flask': 'पायथन वितरित माइक्रोसर्विसेज',
        'sys-ml-gemini': 'हाइब्रिड विजन + लार्ज लैंग्वेज मॉडल',
        'sys-mongo': 'इन-मेमोरी / मोंगोडीबी',
        'sys-s1-subtitle': 'आधारभूत संरचना अवलोकन',
        'sys-s1-desc-text': 'यह प्लेटफॉर्म एक उच्च-समवर्ती वास्तुकला पर बनाया गया है जो ग्रामीण क्षेत्र के डेटा को आधुनिक एआई के साथ जोड़ता है। हम तीन-स्तरीय डिज़ाइन रणनीति का उपयोग करते हैं: **एज इंटरेक्शन**, **स्केलेबल बैकएंड**, और **हाइब्रिड इंटेलिजेंस रीजनिंग**। यह सीधा संरेखण सुनिश्चित करता है कि हमारे 4 मुख्य उद्देश्य दक्षता और सुरक्षा के साथ पूरे हों।',
        'sys-s1-p1-title': 'ग्रामीण-प्रथम डिजाइन',
        'sys-s1-p1-desc': 'ऑफलाइन-प्रथम क्षमताओं के साथ कम-बैंडविड्थ क्षेत्रों के लिए अनुकूलित।',
        'sys-s1-p2-title': 'इंटेलिजेंस स्केलेबिलिटी',
        'sys-s1-p2-desc': 'उच्च-तीव्रता वाले विजन और भविष्य कहनेवाला कार्यों के लिए लोचदार कंप्यूट संसाधन।',
        'sys-s1-p3-title': 'डेटा सुरक्षा',
        'sys-s1-p3-desc': 'सभी किसान डेटा और पशु चिकित्सा इतिहास के लिए एंड-टू-एंड एन्क्रिप्शन।',
        'sys-farmers-desc': 'मोबाइल, वेब और वॉयस के माध्यम से ओमनीचैनल पहुंच।',
        'sys-frontend-desc': 'तरल यूआई के लिए टेलविंड के साथ आधुनिक इंटरफ़ेस।',
        'sys-backend-desc': 'पायथन गेटवे का उपयोग करके रेस्टफुल माइक्रोसर्विसेज।',
        'sys-intelligence-desc': 'एफिशिएंटनेट विजन + जेमिनी सिमेंटिक रीजनिंग।',
        'sys-datalayer-desc': 'प्रोफाइल और टाइम-सीरीज डेटा के लिए हाइब्रिड स्टोरेज।',

        'sys-obj-header': 'प्लेटफॉर्म के मुख्य उद्देश्य',
        'sys-obj-1-t': 'स्वास्थ्य सुरक्षा',
        'sys-obj-1-d': 'पशुओं को बीमारियों से बचाने के लिए AI आधारित त्वरित पहचान।',
        'sys-obj-2-t': 'उचित बाजार व्यापार',
        'sys-obj-2-d': 'हर किसान के लिए उचित मूल्य सुनिश्चित करने वाला एल्गोरिथम मूल्यांकन।',
        'sys-obj-3-t': 'ग्रामीण सुलभता',
        'sys-obj-3-d': 'डिजिटल दूरी को पाटने वाली बहुभाषी वॉयस सहायता।',
        'sys-obj-4-t': 'डेटा-संचालित अंतर्दृष्टि',
        'sys-obj-4-d': 'दूध की पैदावार और स्वास्थ्य पूर्वानुमान के लिए भविष्य कहनेवाला विश्लेषण।',
        'sys-obj-interaction': 'किसान **इंटरफ़ेस** के माध्यम से **स्वास्थ्य सुरक्षा** के लिए मवेशियों को स्कैन करते हैं। हमारा **इंटेलिजेंस कोर** **फेयर ट्रेड** के लिए मूल्यांकन करता है, जबकि **वॉयस एआई** **पहुंच** सुनिश्चित करता है। सभी डेटा **भविष्य कहनेवाला अंतर्दृष्टि** के लिए **ज्ञान आधार** को फीड करते हैं।',

        'meth-title-1': 'कार्यप्रणाली: स्वास्थ्य सुरक्षा',
        'meth-title-2': 'कार्यप्रणाली: उचित बाजार व्यापार',
        'meth-title-3': 'कार्यप्रणाली: ग्रामीण पहुंच',
        'meth-title-4': 'कार्यप्रणाली: डेटा-संचालित अंतर्दृष्टि',
        'sys-view-meth': 'कार्यप्रणाली देखें →',

        'sys-s2-title': 'एंड-टू-एंड इंडिक बहुभाषी प्लेटफॉर्म',
        'sys-s2-hybrid-title': 'इंडिकवेव2वेक + जेमिनी हाइब्रिड',
        'sys-s2-desc': 'ध्वन्यात्मक डिकोडिंग के लिए **पूर्व-प्रशिक्षित ध्वनिक मॉडल** और क्रॉस-भाषाई सिमेंटिक रीजनिंग के लिए **जेमिनी 1.5 प्रो** को संयोजित करने वाला एक हाइब्रिड डिज़ाइन।',
        'sys-s2-neural-stats': 'न्यूरल आंकड़े',
        'sys-s2-model': 'मॉडल',
        'sys-s2-params': 'पैरम्स',
        'sys-s2-latency': 'विलंबता',
        'sys-s2-pipeline-title': 'क्रॉस-भाषाई अनुमान पाइपलाइन',
        'sys-s2-raw-audio': 'रॉ ऑडियो',
        'sys-s2-feat-extract': 'फीचर एक्सट्रैक्शन',
        'sys-s2-phoneme-map': 'इंडिकवेव2वेक + जेमिनी',
        'sys-s2-action': 'कार्य',

        'sys-s3-title': 'संदर्भ-जागरूक उत्पादक तर्क',
        'sys-s3-role-prompt': 'भूमिका-आधारित प्रॉम्प्ट इंजीनियरिंग',
        'sys-s3-desc': 'संरचित इतिहास और सख्त व्यवहार संबंधी निर्देश खिलाकर एक मानक एलएलएम को एक विशेष पशु चिकित्सा या पोषण विशेषज्ञ में बदल देता है।',
        'sys-s3-cog-func': 'संज्ञानात्मक कार्य',
        'sys-s3-persona-switch': 'डायनामिक व्यक्तित्व स्विचिंग',
        'sys-s3-concise': 'संक्षिप्त आउटपुट (वॉयस)',
        'sys-s3-pipe-title': 'बातचीत पाइपलाइन',
        'sys-s3-user-query': 'उपयोगकर्ता प्रश्न',
        'sys-s3-ctx-engine': 'संदर्भ इंजन',
        'sys-s3-gemini-llm': 'जेमिनी एलएलएम',
        'sys-s3-expert-advice': 'विशेषज्ञ की सलाह',

        'sys-s4-title': 'भविष्य कहनेवाला फार्म एनालिटिक्स (TFT)',
        'sys-s4-tft-title': 'टेंपोरल फ्यूजन ट्रांसफार्मर',
        'sys-s4-desc': '**मल्टी-होराइजन क्वांटाइल रिकरेंट न्यूरल नेटवर्क** द्वारा संचालित। दूध की पैदावार का पूर्वानुमान लगाने के लिए **TFT** और वास्तविक समय की विसंगतियों का पता लगाने के लिए **आइसोलेशन फ़ॉरेस्ट** का उपयोग करता है।',
        'sys-s4-model-specs': 'मॉडल स्पेक्स',
        'sys-s4-forecasting': 'पूर्वानुमान',
        'sys-s4-horizon': 'होराइजन',
        'sys-s4-error-rate': 'त्रुटि दर',
        'sys-s4-pipe-title': 'एनालिटिक्स पाइपलाइन',
        'sys-s4-hist-data': 'ऐतिहासिक डेटा',
        'sys-s4-sliding-win': 'स्लाइडिंग विंडो',
        'sys-s4-ensemble': 'एंसेम्बल कोर',
        'sys-s4-smart-insight': 'स्मार्ट अंतर्दृष्टि',

        // Breeds & Locations
        'opt-gir': 'गिर',
        'opt-sahiwal': 'साहीवाल',
        'opt-redsindhi': 'लाल सिंधी',
        'opt-tharparkar': 'थारपारकर',
        'opt-jersey': 'जर्सी',
        'opt-holstein': 'होलस्टीन फ्रिसियन',
        'opt-hfcross': 'एचएफ क्रॉस',
        'opt-murrah': 'मुर्रा भैंस',
        'opt-unknown': 'अज्ञात / अन्य',

        // States
        'st-karnataka': 'कर्नाटक',
        'st-goa': 'गोवा',
        'st-andhrapradesh': 'आंध्र प्रदेश',
        'st-telangana': 'तेलंगाना',
        'st-tamilnadu': 'तमिलनाडु',
        'st-kerala': 'केरल',
        'st-maharashtra': 'महाराष्ट्र',
        'st-gujarat': 'गुजरात',
        'st-madhyapradesh': 'मध्य प्रदेश',
        'st-uttarpradesh': 'उत्तर प्रदेश',
        'st-arunachalpradesh': 'अरुणाचल प्रदेश',
        'st-assam': 'असम',
        'st-bihar': 'बिहार',
        'st-chhattisgarh': 'छत्तीसगढ़',
        'st-haryana': 'हरियाणा',
        'st-himachalpradesh': 'हिमाचल प्रदेश',
        'st-jharkhand': 'झारखंड',
        'st-manipur': 'मणिपुर',
        'st-meghalaya': 'मेघालय',
        'st-mizoram': 'मिजोरम',
        'st-nagaland': 'नागालैंड',
        'st-odisha': 'ओडिशा',
        'st-punjab': 'पंजाब',
        'st-rajasthan': 'राजस्थान',
        'st-sikkim': 'सिक्किम',
        'st-tripura': 'त्रिपुरा',
        'st-uttarakhand': 'उत्तराखंड',
        'st-westbengal': 'पश्चिम बंगाल'
    },
    'te-IN': {
        'title-dashboard': 'పశువుల డాష్‌బోర్డ్',
        'title-trade': 'స్మార్ట్ ట్రేడ్ (ధర)',
        'title-disease': 'వ్యాధి స్కానర్',
        'title-advisory': 'నిపుణుల సలహా',
        'logo': 'కేటిల్ కేర్',
        'nav-dashboard': 'డ్యాష్‌బోర్డ్',
        'nav-trade': 'స్మార్ట్ ట్రేడ్',
        'nav-disease': 'వ్యాధి స్కానర్',
        'nav-advisory': 'సలహా',
        'nav-cows': 'నా పశువులు',
        'nav-services': 'సేవలు',
        'nav-alerts': 'హెచ్చరికలు',
        'nav-settings': 'అమరికలు',
        'alerts-title': 'హెచ్చరికలు & నోటిఫికేషన్‌లు',
        'alerts-subtitle': 'మీ మంద గురించి ముఖ్యమైన నవీకరణలు.',
        'alerts-empty': 'కొత్త హెచ్చరికలు లేవు.',
        'settings-title': 'అమరికలు',
        'settings-subtitle': 'మీ ఖాతా మరియు యాప్ ప్రాధాన్యతలను నిర్వహించండి.',
        'stg-account': 'రైతు ఖాతా',
        'stg-signout': 'సైన్ అవుట్',
        'stg-pref': 'ప్రాధాన్యతలు',
        'stg-lang': 'భాష',
        'stg-theme': 'థీమ్',
        'stg-notif': 'నోటిఫికేషన్‌లు',
        'stg-push': 'పుష్ నోటిఫికేషన్‌లు',
        'stg-email': 'ఇమెయిల్ హెచ్చరికలు',
        'stg-security': 'భద్రత',
        'stg-change-pw': 'పాస్‌వర్డ్ మార్చండి',
        'stg-save': 'మార్పులను భద్రపరచండి',
        'grants-title': 'ప్రభుత్వ గ్రాంట్లు',
        'grants-subtitle': 'మీ పొలం కోసం అందుబాటులో ఉన్న గ్రాంట్లు మరియు సబ్సిడీలను కనుగొనండి.',
        'grants-new': 'కొత్త గ్రాంట్ (అడ్మిన్)',
        'grants-schemes': 'అందుబాటులో ఉన్న పథకాలు',
        'grants-apply': 'దరఖాస్తు చేయండి',
        'predict-title': 'ఆరోగ్య అంచనా AI',
        'predict-subtitle': 'ఆరోగ్య సమస్యలను గుర్తించడానికి కీలక సంకేతాలను విశ్లేషించండి.',
        'pred-enter-vitals': 'వివరాలను నమోదు చేయండి',
        'pred-temp': 'ఉష్ణోగ్రత (°C)',
        'pred-appetite': 'ఆకలి (1-10)',
        'pred-mobility': 'చలనం (1-10)',
        'pred-run': 'అంచనా వేయండి',
        'pred-analyzing': 'విశ్లేషిస్తోంది...',
        'pred-result-placeholder': 'ఫలితాన్ని చూడటానికి వివరాలను నమోదు చేయండి.',
        'pred-note': 'గమనిక: ఇది AI అంచనా. దయచేసి నిర్ధారణ కోసం వెట్‌ను సంప్రదించండి.',
        'cows-title': 'నా పశువులు',
        'cows-subtitle': 'మీ పశువుల జాబితా మరియు ఆరోగ్యాన్ని నిర్వహించండి.',
        'btn-add-cow': 'కొత్త ఆవును జోడించండి',
        'hdr-herd-list': 'పశువుల జాబితా',
        'tbl-tag': 'ట్యాగ్ ఐడి',
        'tbl-age': 'వయస్సు',
        'tbl-health': 'ఆరోగ్యం',
        'tbl-owner': 'యజమాని',
        'ph-tag': 'ట్యాగ్ ఐడి',
        'ph-age': 'వయస్సు',
        'ph-owner': 'యజమాని',
        'opt-select-status': 'స్థితిని ఎంచుకోండి',
        'opt-healthy': 'ఆరోగ్యంగా',
        'opt-sick': 'అనారోగ్యం',
        'opt-pregnant': 'గర్భవతి',
        'srv-title': 'మా సేవలు',
        'srv-subtitle': 'ఆధునిక పశువుల నిర్వహణ కోసం సమగ్ర సాధనాలు.',
        'srv-health-hub': 'హెల్త్ హబ్',
        'srv-health-desc': 'AI అంచనా & వ్యాధి స్కానింగ్',
        'srv-trade': 'స్మార్ట్ ట్రేడ్',
        'srv-trade-desc': 'న్యాయమైన ధర అంచనా & మార్కెట్ పోకడలు',
        'srv-advisory': 'సలహా',
        'srv-advisory-desc': 'నిపుణుల మార్గదర్శకత్వం & ఉత్తమ పద్ధతులు',
        'srv-grants': 'ప్రభుత్వ గ్రాంట్లు',
        'srv-grants-desc': 'సబ్సిడీ & ఆర్థిక సహాయ సమాచారం',
        'dash-active-trades': 'యాక్టివ్ ట్రేడ్స్',
        'dash-govt-grants': 'ప్రభుత్వ గ్రాంట్లు',
        'dash-health-ai': 'హెల్త్ ఏఐ',
        'lbl-breed': 'జాతి',
        'lbl-weight': 'బరువు (kg)',
        'lbl-age': 'వయస్సు (నెలలు)',
        'lbl-milk': 'పాలు (లీటర్లు)',
        'lbl-preg': 'గర్భం (నెలలు)',
        'btn-calc': 'ధరను లెక్కించు',
        'btn-scan': 'స్కాన్ చేయండి',
        'total-cattle': 'మొత్తం పశువులు',
        'health-alerts': 'ఆరోగ్య హెచ్చరికలు',
        'market-rate': 'సగటు స్థానిక ధర',
        'weather': 'వాతావరణం',
        'recent-activity': 'ఇటీవలి కార్యకలాపాలు',
        'opt-gir': 'గిర్ (దేశీయ)',
        'opt-sahiwal': 'సాహివాల్',
        'opt-redsindhi': 'రెడ్ సింధీ',
        'opt-tharparkar': 'థార్‌పార్కర్',
        'opt-jersey': 'జెర్సీ',
        'opt-holstein': 'హోల్స్టీన్',

        'dash-infra': 'ఫార్మ్ మౌలిక సదుపాయాలు',
        'subtitle-dashboard': 'స్మార్ట్ ఫార్మ్ నిర్వహణ వ్యవస్థ',
        'status-db': 'DB కనెక్ట్ చేయబడింది',
        'status-live': 'లైవ్',
        'unit-kg': '/kg',
        'chart-milk': 'పాల దిగుబడి (లీటర్లు)',
        'disclaimer-gps': '*మీ GPS స్థానం ఆధారంగా',
        'dash-acres': 'ఎకరాలు',
        'dash-sheds': 'షెడ్లు',
        'dash-cctv': 'CCTV లైవ్',
        'dash-feed': 'మేత నిల్వ',
        'dash-water': 'నీటి ట్యాంక్',
        'dash-trends': 'ఉత్పత్తి పోకడలు',
        'dash-sick': 'అనారోగ్య చరిత్ర',
        'dash-no-sick': 'రికార్డులు కనుగొనబడలేదు.',
        'dash-vets': 'దగ్గరి పశువైద్యశాలలు',
        'dash-nav': 'దారి చూపించు',
        'dash-view-map': 'మ్యాప్‌లో చూడండి',
        'trade-subtitle': 'AI ఆధారిత వాల్యుయేషన్ & సర్టిఫికేషన్',
        'grp-desi': 'భారతీయ దేశీయ (దేసీ)',
        'grp-exotic': 'విదేశీ / క్రాస్',
        'opt-murrah': 'ముర్రా గేదె',
        'msg-analyzing': 'AI విశ్లేషిస్తోంది...',
        'hint-qr': 'Google Lens ఉపయోగించండి • వివరాలను సేవ్ చేయండి',
        'lbl-forecast': '6-నెలల అంచనా',
        'adv-critical': 'అత్యవసర శ్రద్ధ అవసరం. వెంటనే వెట్‌ను సంప్రదించండి.',

        'cert-title': 'వాల్యుయేషన్ రిపోర్ట్',
        'cert-subtitle': 'కాటిల్ కేర్ AI ద్వారా ధృవీకరించబడింది',
        'cert-value': 'అంచనా వేయబడిన ధర',
        'cert-confidence': 'ఖచ్చితత్వం',
        'cert-proof': 'ధర వివరాలు (రుజువు)',
        'cert-base': 'బరువు విలువ',
        'cert-milk': 'పాల దిగుబడి బోనస్',
        'cert-preg': 'గర్భధారణ బోనస్',
        'cert-age': 'వయస్సు తగ్గింపు',
        'cert-analysis': 'AI నిపుణుల విశ్లేషణ',
        'cert-footer': 'జెమిని AI ద్వారా రూపొందించబడింది • అధికారిక నివేదిక',
        'btn-download': 'PDF డౌన్‌లోడ్ చేయండి',
        'qr-scan': 'ఫోన్‌లో సేవ్ చేయడానికి స్కాన్ చేయండి',

        'adv-chat-placeholder': 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
        'adv-chat-send': 'పంపండి',
        'adv-welcome-msg': 'నమస్తే! నేను మీ AI పశువైద్య నిపుణుడిని. ఈ రోజు నేను మీ పశువులకు ఎలా సహాయం చేయగలను?',
        'adv-typing': 'వెట్ టైప్ చేస్తున్నారు...',

        // Dashboard Steps
        'step-1-title': 'పశువుల నమోదు',
        'step-1-desc': 'ట్రాకింగ్ ప్రారంభించడానికి మీ మంద వివరాలను నమోదు చేయండి.',
        'step-2-title': 'ఆరోగ్య పర్యవేక్షణ',
        'step-2-desc': 'శ్రేయస్సును నిర్ధారించడానికి AI వ్యాధి స్కానర్‌ని ఉపయోగించండి.',
        'step-3-title': 'సేవలు',
        'step-3-desc': 'సరసమైన వాణిజ్య ధరలు మరియు ప్రభుత్వ గ్రాంట్‌లను పొందండి.',

        // Advisory Tabs
        'adv-tab-general': 'సాధారణ సలహా',
        'adv-tab-nutrition': 'పోషకాహార సలహా',

        'sys-header': 'మొత్తం ప్లాట్‌ఫారమ్ డెమో',
        'sys-s1-title': 'డిజైన్ స్ట్రాటజీ మరియు కీ ఫ్లో',
        'sys-farmers': 'రైతులు',
        'sys-frontend': 'ఇంటర్‌ఫేస్ లేయర్',
        'sys-backend': 'నిర్ణయ యంత్రం',
        'sys-hybrid': 'న్యూరల్ కోర్',
        'sys-datalayer': 'జ్ఞాన ఆధారం',
        'sys-mobile-web': 'మల్టీ-మోడల్ ఇంటరాక్షన్',
        'sys-react-vite': 'రెస్పాన్సివ్ రియాక్ట్ ఎకోసిస్టమ్',
        'sys-flask': 'పైథాన్ డిస్ట్రిబ్యూటెడ్ మైక్రోసర్వీసెస్',
        'sys-ml-gemini': 'హైబ్రిడ్ విజన్ + లార్జ్ లాంగ్వేజ్ మోడల్',
        'sys-mongo': 'మెమరీ / మోంగోడీబి',
        'sys-s1-subtitle': 'మౌలిక సదుపాయాల అవలోకనం',
        'sys-s1-desc-text': 'కేటిల్ కేర్ ప్లాట్‌ఫారమ్ గ్రామీణ ఫీల్డ్ డేటాను ఆధునిక ఏఐతో కలిపే హై-కాన్కరెన్సీ ఆర్కిటెక్చర్ ఆధారంగా నిర్మించబడింది. మేము మూడు-స్థాయిల డిజైన్ వ్యూహాన్ని ఉపయోగిస్తాము: **ఎడ్జ్ ఇంటరాక్షన్**, **స్కేలబుల్ బ్యాకెండ్**, మరియు **హైబ్రిడ్ ఇంటెలిజెన్స్ రీజనింగ్**. ఈ ప్రత్యక్ష సమలేఖనం మా 4 ప్రధాన లక్ష్యాలను సమర్థత మరియు భద్రతతో నెరవేర్చేలా చేస్తుంది।',
        'sys-s1-p1-title': 'గ్రామీణ-మొదటి డిజైన్',
        'sys-s1-p1-desc': 'తక్కువ బ్యాండ్‌విడ్త్ జోన్‌ల కోసం ఆఫ్‌లైన్-ఫస్ట్ సామర్థ్యాలతో ఆప్టిమైజ్ చేయబడింది.',
        'sys-s1-p2-title': 'ఏఐ స్కేలబిలిటీ',
        'sys-s1-p2-desc': 'అధిక-తీవ్రత కలిగిన విజన్ మరియు ప్రిడిక్టివ్ పనుల కోసం సాగే కంప్యూట్ వనరులు.',
        'sys-s1-p3-title': 'డేటా భద్రత',
        'sys-s1-p3-desc': 'అన్ని రైతు డేటా మరియు పశువుల వైద్య చరిత్ర కోసం ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్.',
        'sys-farmers-desc': 'మొబైల్, వెబ్ మరియు వాయిస్ ద్వారా ఓమ్నీఛానల్ యాక్సెస్.',
        'sys-frontend-desc': 'ఫ్లూయిడ్ యూఐ కోసం టైల్‌విండ్‌తో విట్ ఎస్‌పిఏ.',
        'sys-backend-desc': 'ఫ్లాస్క్ గేట్‌వేని ఉపయోగించి రెస్ట్‌ఫుల్ మైక్రోసర్వీసెస్.',
        'sys-intelligence-desc': 'ఎఫిషియంట్ నెట్ విజన్ + జెమిని సెమాంటిక్ రీజనింగ్.',
        'sys-datalayer-desc': 'ప్రొఫైల్స్ మరియు టైమ్-సిరీస్ డేటా కోసం హైబ్రిడ్ స్టోరేజ్.',

        'sys-obj-header': 'ప్లాట్‌ఫారమ్ యొక్క ప్రధాన లక్ష్యాలు',
        'sys-obj-1-t': 'ఆరోగ్య భద్రత',
        'sys-obj-1-d': 'పశువుల వ్యాధులను త్వరగా గుర్తించడానికి AI ఆధారిత స్కాన్.',
        'sys-obj-2-t': 'న్యాయమైన మార్కెట్ వ్యాపారం',
        'sys-obj-2-d': 'ప్రతి రైతుకు న్యాయమైన ధరను నిర్ధారించే అల్గారిథమిక్ వాల్యుయేషన్.',
        'sys-obj-3-t': 'గ్రామీణ ప్రాప్యత',
        'sys-obj-3-d': 'డిజిటల్ అంతరాన్ని తగ్గించే బహుభాషా వాయిస్ సపోర్ట్.',
        'sys-obj-4-t': 'డేటా ఆధారిత అంతర్దృష్టులు',
        'sys-obj-4-d': 'పాల దిగుబడి మరియు ఆరోగ్య అంచనాల కోసం ప్రిడిక్టివ్ అనలిటిక్స్.',
        'sys-obj-interaction': 'రైతులు **ఇంటర్‌ఫేస్** ద్వారా **ఆరోగ్య భద్రత** కోసం పశువులను స్కాన్ చేస్తారు. మా **ఇంటెలిజెన్స్ కోర్** **ఫెయిర్ ట్రేడ్** కోసం మూల్యాంకనం చేస్తుంది, మరియు **వాయిస్ ఏఐ** **యాక్సెసిబిలిటీ**ని నిర్ధారిస్తుంది. మొత్తం డేటా **ప్రిడిక్టివ్ ఇన్‌సైట్స్** కోసం **నాలెడ్జ్ బేస్** కి చేరుతుంది.',

        'meth-title-1': 'పద్ధతి: ఆరోగ్య భద్రత',
        'meth-title-2': 'పద్ధతి: సరసమైన మార్కెట్ వ్యాపారం',
        'meth-title-3': 'పద్ధతి: గ్రామీణ ప్రాప్యత',
        'meth-title-4': 'పద్ధతి: డేటా-ఆధారిత అంతర్దృష్టులు',
        'sys-view-meth': 'పద్ధతిని వీక్షించండి →',

        'sys-s2-title': 'ఎండ్-టు-ఎండ్ ఇండిక్ బహుభాషా ప్లాట్‌ఫారమ్',
        'sys-s2-hybrid-title': 'ఇండిక్‌వేవ్2వెక్ + జెమిని హైబ్రిడ్',
        'sys-s2-desc': 'ఫోనెటిక్ డీకోడింగ్ కోసం **ప్రీ-ట్రైన్డ్ అకౌస్టిక్ మోడల్స్** మరియు క్రాస్-లింగ్విస్టిక్ సెమాంటిక్ రీజనింగ్ కోసం **జెమిని 1.5 ప్రో**లను కలిపి ఒక హైబ్రిడ్ డిజైన్.',
        'sys-s2-neural-stats': 'న్యూరల్ స్టాట్స్',
        'sys-s2-model': 'మోడల్',
        'sys-s2-params': 'పారామీటర్లు',
        'sys-s2-latency': 'లేటెన్సీ',
        'sys-s2-pipeline-title': 'క్రాస్-లింగ్విస్టిక్ ఇన్‌ఫరెన్స్ పైప్‌లైన్',
        'sys-s2-raw-audio': 'రా ఆడియో',
        'sys-s2-feat-extract': 'ఫీచర్ ఎక్స్‌ట్రాక్షన్',
        'sys-s2-phoneme-map': 'ఇండిక్‌వేవ్2వెక్ + జెమిని',
        'sys-s2-action': 'చర్య',

        'sys-s3-title': 'కాంటెక్స్ట్-అవేర్ జనరేటివ్ రీజనింగ్',
        'sys-s3-role-prompt': 'రోల్-బేస్డ్ ప్రాంప్ట్ ఇంజనీరింగ్',
        'sys-s3-desc': 'స్ట్రక్చర్డ్ హిస్టరీ మరియు కఠినమైన బిహేవియరల్ ఇన్‌స్ట్రక్షన్స్‌ను అందించడం ద్వారా స్టాండర్డ్ LLMని ప్రత్యేక వెటర్నరీ లేదా న్యూట్రిషన్ నిపుణుడిగా మారుస్తుంది.',
        'sys-s3-cog-func': 'కాగ్నిటివ్ ఫంక్షన్లు',
        'sys-s3-persona-switch': 'డైనమిక్ పర్సనా స్విచింగ్',
        'sys-s3-concise': 'సంక్షిప్త అవుట్‌పుట్ (వాయిస్)',
        'sys-s3-pipe-title': 'సంభాషణ పైప్‌లైన్',
        'sys-s3-user-query': 'యూజర్ క్వెరీ',
        'sys-s3-ctx-engine': 'కాంటెక్స్ట్ ఇంజిన్',
        'sys-s3-gemini-llm': 'జెమిని LLM',
        'sys-s3-expert-advice': 'నిపుణుల సలహా',

        'sys-s4-title': 'ప్రిడిక్టివ్ ఫార్మ్ అనలిటిక్స్ (TFT)',
        'sys-s4-tft-title': 'టెంపోరల్ ఫ్యూషన్ ట్రాన్స్‌ఫార్మర్',
        'sys-s4-desc': '**మల్టీ-హారిజన్ క్వాంటైల్ రికరెంట్ న్యూరల్ నెట్‌వర్క్** ద్వారా ఆధారితం. పాల దిగుబడిని అంచనా వేయడానికి **TFT**ని మరియు రియల్-టైమ్ అనామలీలను గుర్తించడానికి **ఐసోలేషన్ ఫారెస్ట్**ని ఉపయోగిస్తుంది.',
        'sys-s4-model-specs': 'మోడల్ స్పెక్స్',
        'sys-s4-forecasting': 'ఫోర్‌కాస్టింగ్',
        'sys-s4-horizon': 'హారిజన్',
        'sys-s4-error-rate': 'ఎర్రర్ రేట్',
        'sys-s4-pipe-title': 'అనలిటిక్స్ పైప్‌లైన్',
        'sys-s4-hist-data': 'హిస్టారికల్ డేటా',
        'sys-s4-sliding-win': 'స్లైడింగ్ విండో',
        'sys-s4-ensemble': 'ఎన్‌సెంబుల్ కోర్',
        'sys-s4-smart-insight': 'స్మార్ట్ ఇన్‌సైట్స్',

        'btn-camera': 'కెమెరా తెరవండి',
        'btn-capture': 'ఫోటో తీయండి',
        'btn-retake': 'మళ్ళీ తీయండి',
        'lbl-analyzing': 'AI చిత్రాన్ని స్కాన్ చేస్తోంది...',
        'p-disease-guide': 'తక్షణ నిర్ధారణ కోసం కెమెరాను ప్రభావిత ప్రాంతం (చర్మం, కళ్లు, నోరు) వైపు ఉంచండి।',
        'skin-check-title': 'చర్మ ఆరోగ్య ముందస్తు తనిఖీ',
        'q-skin-rash': 'మీకు ఏవైనా దద్దుర్లు, మొటిమలు లేదా చర్మ గాయాలు కనిపిస్తున్నాయా?',
        'q-from-birth': 'ఈ గుర్తు పుట్టినప్పటి నుండి ఉందా?',
        'q-skin-change': 'ఇటీవల ఏదైనా మార్పు (పరిమాణం, రంగు, రక్తస్రావం) జరిగిందా?',
        'msg-benign': 'ఇది పుట్టుమచ్చ అయ్యే అవకాశం ఉంది. మీకు ఇంకా ఆందోళనగా ఉంటే మీరు స్కాన్ చేయవచ్చు.',
        'msg-consult': 'ఖచ్చితమైన నిర్ధారణ కోసం మేము వ్యాధి స్కాన్ చేయమని సిఫార్సు చేస్తున్నాము.',
        'btn-continue': 'కొనసాగించండి',
        'btn-check-disease': 'వ్యాధిని తనిఖీ చేయండి',
        'opt-yes': 'అవును',
        'opt-no': 'లేదు',
        'lbl-vet-dermatologist': 'AI-ఆధారిత వెటర్నరీ డెర్మటాలజిస్ట్',
        'btn-upload-photo': 'ఫోటోను అప్‌లోడ్ చేయండి',
        'btn-live-camera': 'లైవ్ కెమెరా',
        'btn-remove': 'తొలగించు',
        'btn-run-analysis': 'AI విశ్లేషణను అమలు చేయండి',
        'lbl-low-appetite': 'తక్కువ ఆకలి?',
        'ph-vitals-history': 'ఉదా: ఎడమ కాలిలో మునుపటి ఇన్ఫెక్షన్...',
        'msg-connecting-gemini': 'జెమినీ విజన్‌కి కనెక్ట్ అవుతోంది...',
        'lbl-ai-recommendation': 'AI సిఫార్సు',
        'lbl-detected': 'గుర్తించబడింది',
        'lbl-confidence': 'నమ్మకం',
        'lbl-ready-scan': 'స్కాన్ చేయడానికి సిద్ధంగా ఉంది',
        'msg-upload-start': 'AI విశ్లేషణను ప్రారంభించడానికి ఫోటోను అప్‌లోడ్ చేయండి',
        'msg-complete-precheck': 'స్కానింగ్‌ని ప్రారంభించడానికి ముందస్తు తనిఖీని పూర్తి చేయండి',
        'upload-text': 'ఫోటోను ఎంచుకోండి',
        'upload-instruction': 'గ్యాలరీ నుండి అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
        'lbl-location': 'ప్రాంతం',
        'lbl-temperature': 'ఉష్ణోగ్రత (°F)',
        'lbl-pregnancy': 'గర్భధారణ స్థితి',
        'lbl-milk-yield': 'పాల దిగుబడి (లీటర్లు)',
        'lbl-nose': 'ముక్కు కారుతుందా?',
        'lbl-breath': 'శ్వాస శబ్దం?',
        'lbl-history': 'వైద్య చరిత్ర',
        'lbl-fever': 'జ్వరం?',
        'lbl-high-fever': 'తీవ్రమైన జ్వరం',
        'ph-age': 'ఉదా: 4',
        'ph-weight': 'kg',
        'ph-temp': '°F',
        'ph-milk': 'లీటర్లు',

        'lbl-vaccination': 'టీకా స్థితి',
        'lbl-lactation': 'పాల చక్రం (1-10)',
        'lbl-disease-hist': 'వ్యాధి చరిత్ర',
        'opt-vac-none': 'ఏమీ లేదు / తెలియదు',
        'opt-vac-partial': 'పాక్షికంగా టీకాలు వేయబడ్డాయి',
        'opt-vac-full': 'పూర్తిగా టీకాలు వేయబడ్డాయి',
        'dis-fmd': 'గాలికుంటు వ్యాధి (FMD)',
        'dis-mastitis': 'పొదుగు వాపు (Mastitis)',
        'dis-brucellosis': 'బర్ుసిల్లోసిస్',

    },
    'ta-IN': {
        'title-dashboard': 'பண்ணை டாஷ்போர்டு',
        'title-trade': 'ஸ்மார்ட் வர்த்தகம்',
        'title-disease': 'நோய் ஸ்கேனர்',
        'title-advisory': 'நிபுணர் ஆலோசனை',
        'logo': 'கால்நடை பராமரிப்பு',
        'nav-dashboard': 'டாஷ்போர்டு',
        'nav-trade': 'வர்த்தகம்',
        'nav-disease': 'நோய் ஸ்கேனர்',
        'nav-advisory': 'ஆலோசனை',
        'nav-cows': 'என் மாடுகள்',
        'nav-services': 'சேவைகள்',
        'nav-alerts': 'எச்சரிக்கைகள்',
        'nav-settings': 'அமைப்புகள்',
        'alerts-title': 'எச்சரிக்கைகள் & அறிவிப்புகள்',
        'alerts-subtitle': 'உங்கள் மந்தை பற்றிய முக்கிய அறிவிப்புகள்.',
        'alerts-empty': 'புதிய எச்சரிக்கைகள் இல்லை.',
        'settings-title': 'அமைப்புகள்',
        'settings-subtitle': 'கணக்கு மற்றும் பயன்பாட்டு விருப்பங்களை நிர்வகிக்கவும்.',
        'stg-account': 'விவசாயி கணக்கு',
        'stg-signout': 'வெளியேறு',
        'stg-pref': 'விருப்பங்கள்',
        'stg-lang': 'மொழி',
        'stg-theme': 'தீம்',
        'stg-notif': 'அறிவிப்புகள்',
        'stg-push': 'புஷ் அறிவிப்புகள்',
        'stg-email': 'மின்னஞ்சல் எச்சரிக்கைகள்',
        'stg-security': 'பாதுகாப்பு',
        'stg-change-pw': 'கடவுச்சொல்லை மாற்றவும்',
        'stg-save': 'சேமி',
        'grants-title': 'அரசு மானியங்கள்',
        'grants-subtitle': 'உங்கள் பண்ணைக்கான மானியங்களைக் கண்டறியவும்.',
        'grants-new': 'புதிய மானியம் (நிர்வாகி)',
        'grants-schemes': 'கிடைக்கும் திட்டங்கள்',
        'grants-apply': 'விண்ணப்பிக்கவும்',
        'predict-title': 'சுகாதார முன்னறிவிப்பு AI',
        'predict-subtitle': 'சுகாதார சிக்கல்களைக் கண்டறிய முக்கிய அறிகுறிகளை பகுப்பாய்வு செய்யவும்.',
        'pred-enter-vitals': 'விவரங்களை உள்ளிடவும்',
        'pred-temp': 'வெப்பநிலை (°C)',
        'pred-appetite': 'பசி (1-10)',
        'pred-mobility': 'இயக்கம் (1-10)',
        'pred-run': 'கணிக்கவும்',
        'pred-analyzing': 'பகுப்பாய்வு செய்கிறது...',
        'pred-result-placeholder': 'முடிவைக் காண விவரங்களை உள்ளிடவும்.',
        'pred-note': 'குறிப்பு: இது AI மதிப்பீடு. மருத்துவரை அணுகவும்.',
        'cows-title': 'என் மாடுகள்',
        'cows-subtitle': 'உங்கள் மந்தை பதிவு மற்றும் சுகாதார நிலையை நிர்வகிக்கவும்.',
        'btn-add-cow': 'புதிய பசுவைச் சேர்க்கவும்',
        'hdr-herd-list': 'மந்தை பட்டியல்',
        'tbl-tag': 'குறிச்சொல் ஐடி',
        'tbl-age': 'வயது',
        'tbl-health': 'ஆரோக்கியம்',
        'tbl-owner': 'உரிமையாளர்',
        'ph-tag': 'குறிச்சொல் ஐடி',
        'ph-age': 'வயது',
        'ph-owner': 'உரிமையாளர்',
        'opt-select-status': 'நிலையைத் தேர்ந்தெடுக்கவும்',
        'opt-healthy': 'ஆரோக்கியமான',
        'opt-sick': 'நோய்வாய்ப்பட்ட',
        'opt-pregnant': 'கர்ப்பிணி',
        'srv-title': 'எங்கள் சேவைகள்',
        'srv-subtitle': 'நவீன கால்நடை மேலாண்மைக்கான விரிவான கருவிகள்.',
        'srv-health-hub': 'சுகாதார மையம்',
        'srv-health-desc': 'AI கணிப்பு & நோய் ஸ்கேனிங்',
        'srv-trade': 'ஸ்மார்ட் வர்த்தகம்',
        'srv-trade-desc': 'நியாயமான விலை மதிப்பீடு & சந்தை போக்குகள்',
        'srv-advisory': 'ஆலோசனை',
        'srv-advisory-desc': 'நிபுணர் வழிகாட்டுதல் & சிறந்த நடைமுறைகள்',
        'srv-grants': 'அரசு மானியங்கள்',
        'srv-grants-desc': 'மானியம் மற்றும் நிதி உதவித் தகவல்',
        'dash-active-trades': 'செயலில் உள்ள வர்த்தகம்',
        'dash-govt-grants': 'அரசு மானியங்கள்',
        'dash-health-ai': 'ஹெல்த் ஏஐ',
        'lbl-breed': 'இனம்',
        'lbl-weight': 'எடை (kg)',
        'lbl-age': 'வயது (மாதங்கள்)',
        'lbl-milk': 'பால் (லிட்டர்)',
        'lbl-preg': 'கர்ப்பம் (மாதம்)',
        'btn-calc': 'விலையை கணக்கிடு',
        'btn-scan': 'ஸ்கேன் செய்',
        'total-cattle': 'மொத்த கால்நடைகள்',
        'health-alerts': 'சுகாதார எச்சரிக்கைகள்',
        'market-rate': 'சராசரி உள்ளூர் விலை',
        'weather': 'வானிலை',
        'recent-activity': 'சமீபத்திய செயல்பாடு',
        'opt-gir': 'கிர் (நாட்டு மாடு)',
        'opt-sahiwal': 'சாஹிவால்',
        'opt-redsindhi': 'ரெட் சிந்தி',
        'opt-tharparkar': 'தார்பார்கர்',
        'opt-jersey': 'ஜெர்சி',
        'opt-holstein': 'ஹால்ஸ்டீன்',

        'dash-infra': 'பண்ணை கட்டமைப்பு',
        'subtitle-dashboard': 'ஸ்மார்ட் பண்ணை மேலாண்மை அமைப்பு',
        'status-db': 'DB இணைக்கப்பட்டது',
        'status-live': 'நேரலை',
        'unit-kg': '/kg',
        'chart-milk': 'பால் உற்பத்தி (லிட்டர்)',
        'disclaimer-gps': '*உங்கள் GPS இருப்பிடத்தின் அடிப்படையில்',
        'dash-acres': 'ஏக்கர்',
        'dash-sheds': 'கொட்டகைகள்',
        'dash-cctv': 'CCTV நேரலை',
        'dash-feed': 'தீவன இருப்பு',
        'dash-water': 'தண்ணீர் தொட்டி',
        'dash-trends': 'உற்பத்தி போக்குகள்',
        'dash-sick': 'நோய் வரலாறு',
        'dash-no-sick': 'பதிவுகள் எதுவும் இல்லை.',
        'dash-vets': 'அருகிலுள்ள கால்நடை மருத்துவமனைகள்',
        'dash-nav': 'செல்லவும்',
        'dash-view-map': 'வரைபடத்தில் காண்க',
        'trade-subtitle': 'AI மதிப்பீடு மற்றும் சான்றிதழ்',
        'grp-desi': 'இந்திய உள்நாட்டு (தேசி)',
        'grp-exotic': 'வெளிநாட்டு / கலப்பின',
        'opt-murrah': 'முர்ரா எருமை',
        'msg-analyzing': 'AI பகுப்பாய்வு செய்கிறது...',
        'hint-qr': 'Google Lens பயன்படுத்தவும் • விவரங்களைச் சேமிக்கவும்',
        'lbl-forecast': '6 மாத முன்னறிவிப்பு',
        'adv-critical': 'முக்கிய கவனம் தேவை. உடனடியாக மருத்துவரை அணுகவும்.',

        'cert-title': 'மதிப்பீட்டு அறிக்கை',
        'cert-subtitle': 'Cattle Care AI மூலம் சான்றளிக்கப்பட்டது',
        'cert-value': 'மதிப்பிடப்பட்ட விலை',
        'cert-confidence': 'நம்பகத்தன்மை',
        'cert-proof': 'விலை விவரம் (ஆதாரம்)',
        'cert-base': 'எடை மதிப்பு',
        'cert-milk': 'பால் போனஸ்',
        'cert-preg': 'கர்ப்ப போனஸ்',
        'cert-age': 'வயது தேய்மானம்',
        'cert-analysis': 'AI நிபுணர் பகுப்பாய்வு',
        'cert-footer': 'ஜெமினி AI மூலம் உருவாக்கப்பட்டது',
        'btn-download': 'PDF பதிவிறக்கம்',
        'qr-scan': 'தொலைபேசியில் சேமிக்க ஸ்கேன் செய்யவும்',

        'adv-chat-placeholder': 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்யவும்...',
        'adv-chat-send': 'அனுப்பு',
        'adv-welcome-msg': 'வணக்கம்! நான் உங்கள் AI கால்நடை நிபுணர். இன்று உங்கள் கால்நடைகளுக்கு நான் எவ்வாறு உதவ முடியும்?',
        'adv-typing': 'நிபுணர் தட்டச்சு செய்கிறார்...',

        // Dashboard Steps
        'step-1-title': 'கால்நடை பதிவு',
        'step-1-desc': 'கண்காணிப்பைத் தொடங்க உங்கள் மந்தை விவரங்களைச் சேர்க்கவும்.',
        'step-2-title': 'சுகாதார கண்காணிப்பு',
        'step-2-desc': 'நல்வாழ்வை உறுதிப்படுத்த AI நோய் ஸ்கேனரைப் பயன்படுத்தவும்.',
        'step-3-title': 'சேவைகள்',
        'step-3-desc': 'நியாயமான விலைகள் மற்றும் அரசு மானியங்களைப் பெறுங்கள்.',

        // Advisory Tabs
        'adv-tab-general': 'பொதுவான ஆலோசனை',
        'adv-tab-nutrition': 'ஊட்டச்சத்து ஆலோசனை',

        'sys-header': 'முழுமையான சிஸ்டம் கட்டமைப்பு டெமோ',
        'sys-s1-title': 'வடிவமைப்பு உத்தி மற்றும் முக்கிய ஓட்டம்',
        'sys-farmers': 'விவசாயிகள்',
        'sys-frontend': 'முன்பக்கம்',
        'sys-backend': 'பின்தள API',
        'sys-hybrid': 'கலப்பின நுண்ணறிவு',
        'sys-datalayer': 'தரவு அடுக்கு',
        'sys-mobile-web': 'மொபைல்/வலை இடைமுகம்',
        'sys-react-vite': 'ரியாக்ட் + வைட்',
        'sys-flask': 'ஃப்ளாஸ்க் (பைதான்)',
        'sys-ml-gemini': 'பயிற்சி பெற்ற ML + ஜெமினி AI',
        'sys-mongo': 'நினைவகத்தில் / MongoDB',
        'sys-s1-subtitle': 'கட்டமைப்பு மேலோட்டம்',
        'sys-s1-desc-text': 'கால்நடை பராமரிப்பு அமைப்பு, கிராமப்புற களத் தரவை அதிநவீன AI உடன் இணைக்கும் உயர்-ஒத்திசைவு கட்டமைப்பில் உருவாக்கப்பட்டுள்ளது. நாங்கள் மூன்று அடுக்கு வடிவமைப்பு உத்தியைப் பயன்படுத்துகிறோம்: **எட்ஜ் தொடர்பு**, **அளவிடக்கூடிய பின்தளம்**, மற்றும் **கலப்பின AI பகுத்தறிவு**. இந்த நேரடி சீரமைப்பு எங்களின் 4 முக்கிய குறிக்கோள்களை நிபுணத்துவம் மற்றும் பாதுகாப்புடன் நிறைவேற்றுவதை உறுதி செய்கிறது.',
        'sys-s1-p1-title': 'கிராமப்புற-முதல் வடிவமைப்பு',
        'sys-s1-p1-desc': 'குறைந்த அலைவரிசை மண்டலங்களுக்காக ஆஃப்லைன்-முதல் திறன்களுடன் மேம்படுத்தப்பட்டுள்ளது.',
        'sys-s1-p2-title': 'AI அளவிடுதல்',
        'sys-s1-p2-desc': 'அதிக தீவிரம் கொண்ட பார்வை மற்றும் முன்கணிப்பு பணிகளுக்கான நெகிழ்வான கணினி வளங்கள்.',
        'sys-s1-p3-title': 'தரவு பாதுகாப்பு',
        'sys-s1-p3-desc': 'அனைத்து விவசாயி தரவு மற்றும் கால்நடை மருத்துவ வரலாறுக்கான எண்ட்-டு-எண்ட் குறியாக்கம்.',
        'sys-farmers-desc': 'மொபைல், வலை மற்றும் குரல் வழியாக ஓம்னிசேனல் அணுகல்.',
        'sys-frontend-desc': 'திரவ UI க்காக டெயில்விண்ட் கொண்ட வைட் SPA.',
        'sys-backend-desc': 'ஃப்ளாஸ்க் கேட்வேயைப் பயன்படுத்தி RESTful மைக்ரோசர்வீஸ்கள்.',
        'sys-intelligence-desc': 'எஃபிஷியன்ட்நெட் விஷன் + ஜெமினி செமண்டிக் பகுத்தறிவு.',
        'sys-datalayer-desc': 'சுயவிவரங்கள் மற்றும் நேரத் தொடர் தரவுகளுக்கான கலப்பின சேமிப்பு.',

        'sys-s2-title': 'முழுமையான இந்திய பன்மொழி அமைப்பு',
        'sys-s2-hybrid-title': 'இண்டிக்வேவ்2வெக் + ஜெமினி கலப்பினம்',
        'sys-s2-desc': 'ஒலியியல் டிகோடிங்கிற்கான **முன்-பயிற்சி பெற்ற ஒலி மாதிரிகள்** மற்றும் குறுக்கு மொழி சொற்பொருள் பகுத்தறிவுக்கான **ஜெமினி 1.5 ப்ரோ** ஆகியவற்றை இணைக்கும் ஒரு கலப்பின கட்டமைப்பு.',
        'sys-s2-neural-stats': 'நியூரல் புள்ளிவிவரங்கள்',
        'sys-s2-model': 'மாதிரி',
        'sys-s2-params': 'அளவுகள்',
        'sys-s2-latency': 'தாமதம்',
        'sys-s2-pipeline-title': 'குறுக்கு மொழி ஊகக் குழாய்',
        'sys-s2-raw-audio': 'மூல ஆடியோ',
        'sys-s2-feat-extract': 'அம்சம் பிரித்தெடுத்தல்',
        'sys-s2-phoneme-map': 'இண்டிக்வேவ்2வெக் + ஜெமினி',
        'sys-s2-action': 'செயல்',

        'sys-s3-title': 'சூழல்-அறிந்த உற்பத்தி பகுத்தறிவு',
        'sys-s3-role-prompt': 'பங்கு அடிப்படையிலான தூண்டுதல் பொறியியல்',
        'sys-s3-desc': 'கட்டமைக்கப்பட்ட வரலாறு மற்றும் கடுமையான நடத்தை வழிமுறைகளை வழங்குவதன் மூலம் ஒரு நிலையான LLM ஐ ஒரு சிறப்பு கால்நடை அல்லது ஊட்டச்சத்து நிபுணராக மாற்றுகிறது.',
        'sys-s3-cog-func': 'அறிவாற்றல் செயல்பாடுகள்',
        'sys-s3-persona-switch': 'டைனமிக் ஆளுமை மாற்றம்',
        'sys-s3-concise': 'சுருக்கமான வெளியீடு (குரல்)',
        'sys-s3-pipe-title': 'உரையாடல் குழாய்',
        'sys-s3-user-query': 'பயனர் கேள்வி',
        'sys-s3-ctx-engine': 'சூழல் இயந்திரம்',
        'sys-s3-gemini-llm': 'ஜெமினி LLM',
        'sys-s3-expert-advice': 'நிபுணர் ஆலோசனை',

        'sys-s4-title': 'முன்கணிப்பு பண்ணை பகுப்பாய்வு (TFT)',
        'sys-s4-tft-title': 'தற்காலிக இணைவு மாற்றியமைப்பான்',
        'sys-s4-desc': '**மல்டி-ஹாரிசன் குவாண்டில் ரெகரண்ட் நியூரோ நெட்வொர்க்** மூலம் இயக்கப்படுகிறது. பால் மகசூலை கணிக்க **TFT** ஐயும், நிகழ்நேர அசாதாரணங்களைக் கண்டறிய **ஐசோலேஷன் ஃபாரஸ்ட்** ஐயும் பயன்படுத்துகிறது.',
        'sys-s4-model-specs': 'மாதிரி விவரக்குறிப்புகள்',
        'sys-s4-forecasting': 'முன்கணிப்பு',
        'sys-s4-horizon': 'தொலைநோக்கு',
        'sys-s4-error-rate': 'பிழை விகிதம்',
        'sys-s4-pipe-title': 'பகுப்பாய்வு குழாய்',
        'sys-s4-hist-data': 'வரலாற்று தரவு',
        'sys-s4-sliding-win': 'நகரும் சாளரம்',
        'sys-s4-ensemble': 'கூட்டு மையப்பகுதி',
        'sys-s4-smart-insight': 'ஸ்மார்ட் நுண்ணறிவு',

        'btn-camera': 'கேமராவைத் திற',
        'btn-capture': 'புகைப்படம் எடு',
        'btn-retake': 'மீண்டும் எடு',
        'lbl-analyzing': 'AI படத்தை ஸ்கேன் செய்கிறது...',
        'p-disease-guide': 'உடனடி நோயறிதலுக்கு கேமராவை பாதிக்கப்பட்ட பகுதிக்கு (தோல், கண்கள், வாய்) காட்டவும்।',
        'skin-check-title': 'தோல் ஆரோக்கிய முன் சோதனை',
        'q-skin-rash': 'உங்களுக்கு ஏதேனும் தடிப்புகள், பருக்கள் அல்லது தோல் புண்கள் தெரிகிறதா?',
        'q-from-birth': 'இந்த அடையாளம் பிறந்ததிலிருந்தே இருக்கிறதா?',
        'q-skin-change': 'சமீபத்தில் ஏதேனும் மாற்றம் (அளவு, நிறம், ரத்தம் கசிதல்) ஏற்பட்டுள்ளதா?',
        'msg-benign': 'இது ஒரு சாதாரணமான பிறப்பு அடையாளமாக இருக்கலாம். உங்களுக்கு இன்னும் கவலை இருந்தால் நீங்கள் ஸ்கேன் செய்யலாம்.',
        'msg-consult': 'துல்லியமான நோயறிதலுக்கு நோய் ஸ்கேன் செய்யுமாறு நாங்கள் பரிந்துரைக்கிறோம்.',
        'btn-continue': 'தொடர்க',
        'btn-check-disease': 'நோயைச் சரிபார்க்கவும்',
        'opt-yes': 'ஆம்',
        'opt-no': 'இல்லை',
        'lbl-vet-dermatologist': 'AI-இயங்கும் கால்நடை தோல் மருத்துவர்',
        'btn-upload-photo': 'புகைப்படத்தைப் பதிவேற்றவும்',
        'btn-live-camera': 'நேரடி கேமரா',
        'btn-remove': 'நீக்கவும்',
        'btn-run-analysis': 'AI பகுப்பாய்வை இயக்கவும்',
        'lbl-low-appetite': 'குறைந்த பசி?',
        'ph-vitals-history': 'எ.கா: இடது காலில் முந்தைய தொற்று...',
        'msg-connecting-gemini': 'ஜெமினி விஷனுடன் இணைக்கிறது...',
        'lbl-ai-recommendation': 'AI பரிந்துரை',
        'lbl-detected': 'கண்டறியப்பட்டது',
        'lbl-confidence': 'நம்பிக்கை',
        'lbl-ready-scan': 'ஸ்கேன் செய்ய தயார்',
        'msg-upload-start': 'AI பகுப்பாய்வைத் தொடங்க ஒரு புகைப்படத்தைப் பதிவேற்றவும்',
        'msg-complete-precheck': 'ஸ்கேனிங்கை இயக்க முன் சோதனையை முடிக்கவும்',
        'upload-text': 'புகைப்படத்தைத் தேர்ந்தெடுக்கவும்',
        'upload-instruction': 'கேலரியில் இருந்து பதிவேற்ற கிளிக் செய்யவும்',
        'lbl-location': 'இருப்பிடம்',
        'lbl-temperature': 'வெப்பநிலை (°F)',
        'lbl-pregnancy': 'கர்ப்ப நிலை',
        'lbl-milk-yield': 'பால் மகசூல் (லிட்டர்)',
        'lbl-nose': 'சளி பிடிக்கிறதா?',
        'lbl-breath': 'சுவாச சத்தம்?',
        'lbl-history': 'மருத்துவ வரலாறு',
        'lbl-fever': 'காய்ச்சல்?',
        'lbl-high-fever': 'அதிக காய்ச்சல்',
        'ph-age': 'எ.கா: 4',
        'ph-weight': 'kg',
        'ph-temp': '°F',
        'ph-milk': 'லிட்டர்',

        'lbl-vaccination': 'தடுப்பூசி நிலை',
        'lbl-lactation': 'பாலூட்டும் சுழற்சி (1-10)',
        'lbl-disease-hist': 'நோய் வரலாறு',
        'opt-vac-none': 'எதுவுமில்லை / தெரியவில்லை',
        'opt-vac-partial': 'பகுதி தடுப்பூசி போடப்பட்டது',
        'opt-vac-full': 'முழுமையாக தடுப்பூசி போடப்பட்டது',
        'dis-fmd': 'கால்நடைக் கோமாரி (FMD)',
        'dis-mastitis': 'மடி நோய் (Mastitis)',
        'dis-brucellosis': 'புருசெல்லோசிஸ்',


        // System Demo Keys
        'sys-header': 'விரிவான சிஸ்டம் டெமோ',
        'sys-s1-title': 'புதுமை உத்தி மற்றும் முக்கிய பணிப்பாய்வு',
        'sys-farmers': 'விவசாயிகள்',
        'sys-frontend': 'இடைமுக அடுக்கு',
        'sys-backend': 'முடிவு இயந்திரம்',
        'sys-hybrid': 'நியூரல் கோர்',
        'sys-datalayer': 'அறிவுத் தளம்',
        'sys-mobile-web': 'மல்டி-மாடல் தொடர்பு',
        'sys-react-vite': 'பதிலளிக்கக்கூடிய ரியாக்ட் சுற்றுச்சூழல்',
        'sys-flask': 'பைதான் விநியோகிக்கப்பட்ட மைக்ரோசர்வீஸ்கள்',
        'sys-ml-gemini': 'ஹைப்ரிட் விஷன் + பெரிய மொழி மாதிரி',
        'sys-mongo': 'இன்-மெமரி / மொங்கோடிபி',
        'sys-s1-subtitle': 'உள்கட்டமைப்பு கண்ணோட்டம்',
        'sys-s1-desc-text': 'கேட்டில் கேர் சிஸ்டம் ஒரு உயர்-ஒரே நேரத்தில் இயங்கும் கட்டமைப்பில் உருவாக்கப்பட்டுள்ளது, இது கிராமப்புற தரவை நவீன AI உடன் இணைக்கிறது. நாங்கள் மூன்று அடுக்கு வடிவமைப்பு உத்தியைப் பயன்படுத்துகிறோம்: **எட்ஜ் தொடர்பு**, **அளவிடக்கூடிய பின்தளம்**, மற்றும் **ஹைப்ரிட் AI பகுத்தறிவு**.',
        'sys-s1-p1-title': 'கிராமப்புற-முதன்மை வடிவமைப்பு',
        'sys-s1-p1-desc': 'ஆஃப்லைன்-முதன்மை திறன்களுடன் குறைந்த அலைவரிசை மண்டலங்களுக்கு உகந்ததாக உள்ளது.',
        'sys-s1-p2-title': 'AI அளவிடுதல்',
        'sys-s1-p2-desc': 'அதிக தீவிரம் கொண்ட பார்வை மற்றும் முன்கணிப்பு பணிகளுக்கான மீள் கம்ப்யூட் வளங்கள்.',
        'sys-s1-p3-title': 'தரவு பாதுகாப்பு',
        'sys-s1-p3-desc': 'அனைத்து விவசாயி தரவு மற்றும் கால்நடை மருத்துவ வரலாற்றிற்கான எண்ட்-டு-எண்ட் என்க்ரிப்ஷன்.',
        'sys-farmers-desc': 'மொபைல், வலை மற்றும் குரல் வழியாக ஓம்னிசேனல் அணுகல்.',
        'sys-frontend-desc': 'திரவ UI-க்கான டெயில்விண்டுடன் கூடிய விட் SPA.',
        'sys-backend-desc': 'பிளாஸ்க் கேட்வேயைப் பயன்படுத்தும் ரெஸ்ட்ஃபுல் மைக்ரோசர்வீஸ்கள்.',
        'sys-intelligence-desc': 'எஃபிசியன்ட்நெட் விஷன் + ஜெமினி செமாண்டிக் பகுத்தறிவு.',
        'sys-datalayer-desc': 'விவரக்குறிப்புகள் மற்றும் நேர-தொடர் தரவுகளுக்கான ஹைப்ரிட் சேமிப்பு.',

        'sys-obj-header': 'அமைப்பின் முக்கிய குறிக்கோள்கள்',
        'sys-obj-1-t': 'சுகாதார பாதுகாப்பு',
        'sys-obj-1-d': 'கால்நடை நோய்களை விரைவாகக் கண்டறிய AI அடிப்படையிலான ஸ்கேனிங்.',
        'sys-obj-2-t': 'நியாயமான சந்தை வர்த்தகம்',
        'sys-obj-2-d': 'ஒவ்வொரு விவசாயிக்கும் நியாயமான விலையை உறுதி செய்யும் அல்காரிதமிக் மதிப்பீடு.',
        'sys-obj-3-t': 'கிராமப்புற அணுகல்',
        'sys-obj-3-d': 'டிஜிட்டல் இடைவெளியைக் குறைக்கும் பன்மொழி குரல் உதவி.',
        'sys-obj-4-t': 'தரவு சார்ந்த நுண்ணறிவு',
        'sys-obj-4-d': 'பால் விளைச்சல் மற்றும் சுகாதார முன்னறிவிப்புகளுக்கான முன்கணிப்பு பகுப்பாய்வு.',

        'sys-s2-title': 'எண்ட்-டு-எண்ட் இண்டிக் பன்மொழி அமைப்பு',
        'sys-s2-hybrid-title': 'இண்டிக்வேவ்2வெக் + ஜெமினி ஹைப்ரிட்',
        'sys-s2-desc': 'ஒலியியல் குறியீட்டிற்கான **முன்பே பயிற்சி பெற்ற ஒலியியல் மாதிரிகள்** மற்றும் குறுக்கு மொழி செமாண்டிக் பகுத்தறிவிற்கான **ஜெமினி 1.5 ப்ரோ** ஆகியவற்றை இணைக்கும் ஒரு ஹைப்ரிட் கட்டமைப்பு.',
        'sys-s2-neural-stats': 'நியூரல் புள்ளிவிவரங்கள்',
        'sys-s2-model': 'மாதிரி',
        'sys-s2-params': 'அளவுருக்கள்',
        'sys-s2-latency': 'தாமதம்',
        'sys-s2-pipeline-title': 'குறுக்கு மொழி அனுமான குழாய்',
        'sys-s2-raw-audio': 'மூல ஆடியோ',
        'sys-s2-feat-extract': 'அம்சம் பிரித்தெடுத்தல்',
        'sys-s2-phoneme-map': 'இண்டிக்வேவ்2வெக் + ஜெமினி',
        'sys-s2-action': 'செயல்',

        'sys-s3-title': 'சூழல்-அறிந்த உற்பத்தி பகுத்தறிவு',
        'sys-s3-role-prompt': 'பங்கு அடிப்படையிலான ப்ராம்ப்ட் இன்ஜினியரிங்',
        'sys-s3-desc': 'கட்டமைக்கப்பட்ட வரலாறு மற்றும் கடுமையான நடத்தை வழிமுறைகளை வழங்குவதன் மூலம் ஒரு நிலையான LLM-ஐ ஒரு சிறப்பு கால்நடை அல்லது ஊட்டச்சத்து நிபுணராக மாற்றுகிறது.',
        'sys-s3-cog-func': 'அறிவுசார் செயல்பாடுகள்',
        'sys-s3-persona-switch': 'டைனமிக் ஆளுமை மாறுதல்',
        'sys-s3-concise': 'சுருக்கமான வெளியீடு (குரல்)',
        'sys-s3-pipe-title': 'உரையாடல் குழாய்',
        'sys-s3-user-query': 'பயனர் கேள்வி',
        'sys-s3-ctx-engine': 'சூழல் இயந்திரம்',
        'sys-s3-gemini-llm': 'ஜெமினி LLM',
        'sys-s3-expert-advice': 'நிபுணர் ஆலோசனை',

        'sys-s4-title': 'முன்கணிப்பு பண்ணை பகுப்பாய்வு (TFT)',
        'sys-s4-tft-title': 'டெம்போரல் ஃபியூஷன் டிரான்ஸ்ஃபார்மர்',
        'sys-s4-desc': '**மல்டி-ஹொரைசன் குவாண்டைல் ரீகரன்ட் நியூூரல் நெட்வொர்க்** மூலம் இயக்கப்படுகிறது. பால் விளைச்சலை முன்னறிவிக்க **TFT** மற்றும் நிகழ்நேர முரண்பாடுகளைக் கண்டறிய **ஐசோலேஷன் ஃபாரஸ்ட்** ஆகியவற்றை பயன்படுத்துகிறது.',
        'sys-s4-model-specs': 'மாதிரி விவரக்குறிப்புகள்',
        'sys-s4-forecasting': 'முன்னறிவிப்பு',
        'sys-s4-horizon': 'கால அளவு',
        'sys-s4-error-rate': 'பிழை விகிதம்',
        'sys-s4-pipe-title': 'பகுப்பாய்வு குழாய்',
        'sys-s4-hist-data': 'வரலாற்று தரவு',
        'sys-s4-sliding-win': 'ஸ்லைடிங் விண்டோ',
        'sys-s4-ensemble': 'என்செம்பிள் கோர்',
        'sys-s4-smart-insight': 'ஸ்மார்ட் நுண்ணறிவுகள்',
    },
    'kn-IN': {
        'title-dashboard': 'ಜಾನುವಾರು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'title-trade': 'ಸ್ಮಾರ್ಟ್ ವ್ಯಾಪಾರ',
        'title-disease': 'ರೋಗ ಪತ್ತೆ',
        'title-advisory': 'ತಜ್ಞರ ಸಲಹೆ',
        'logo': 'ಕ್ಯಾಟಲ್ ಕೇರ್',
        'nav-dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'nav-trade': 'ಸ್ಮಾರ್ಟ್ ವ್ಯಾಪಾರ',
        'nav-disease': 'ರೋಗ ಪತ್ತೆ',
        'nav-advisory': 'ಸಲಹೆ',
        'nav-cows': 'ನನ್ನ ಹಸುಗಳು',
        'nav-services': 'ಸೇವೆಗಳು',
        'nav-alerts': 'ಎಚ್ಚರಿಕೆಗಳು',
        'nav-settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'alerts-title': 'ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಸೂಚನೆಗಳು',
        'alerts-subtitle': 'ನಿಮ್ಮ ಹಿಂಡಿನ ಬಗ್ಗೆ ಪ್ರಮುಖ ನವೀಕರಣಗಳು.',
        'alerts-empty': 'ಯಾವುದೇ ಹೊಸ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.',
        'settings-title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'settings-subtitle': 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
        'stg-account': 'ರೈತ ಖಾತೆ',
        'stg-signout': 'ಲಾಗ್ ಔಟ್',
        'stg-pref': 'ಆದ್ಯತೆಗಳು',
        'stg-lang': 'ಭಾಷೆ',
        'stg-theme': 'ಥೀಮ್',
        'stg-notif': 'ಸೂಚನೆಗಳು',
        'stg-push': 'ಪುಶ್ ಸೂಚನೆಗಳು',
        'stg-email': 'ಇಮೇಲ್ ಎಚ್ಚರಿಕೆಗಳು',
        'stg-security': 'ಭದ್ರತೆ',
        'stg-change-pw': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
        'stg-save': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
        'grants-title': 'ಸರ್ಕಾರಿ ಅನುದಾನಗಳು',
        'grants-subtitle': 'ನಿಮ್ಮ ಫಾರ್ಮ್‌ಗಾಗಿ ಲಭ್ಯವಿರುವ ಅನುದಾನ ಮತ್ತು ಸಹಾಯಧನವನ್ನು ಹುಡುಕಿ.',
        'grants-new': 'ಹೊಸ ಅನುದಾನ (ನಿರ್ವಾಹಕ)',
        'grants-schemes': 'ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು',
        'grants-apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
        'predict-title': 'ಆರೋಗ್ಯ ಮುನ್ಸೂಚನೆ AI',
        'predict-subtitle': 'ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ಗುರುತಿಸಲು ಪ್ರಮುಖ ಚಿಹ್ನೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
        'pred-enter-vitals': 'ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
        'pred-temp': 'ತಾಪಮಾನ (°C)',
        'pred-appetite': 'ಹಸಿವು (1-10)',
        'pred-mobility': 'ಚಲನೆ (1-10)',
        'pred-run': 'ಅಂದಾಜಿಸಿ',
        'pred-analyzing': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
        'pred-result-placeholder': 'ಅನಾಲಿಸಿಸ್ ಫಲಿತಾಂಶವನ್ನು ನೋಡಲು ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
        'pred-note': 'ಗಮನಿಸಿ: ಇದು ಎಐ ಅಂದಾಜು. ದಯವಿಟ್ಟು ಅಂತಿಮ ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
        'cows-title': 'ನನ್ನ ಹಸುಗಳು',
        'cows-subtitle': 'ನಿಮ್ಮ ಹಿಂಡಿನ ನೋಂದಣಿ ಮತ್ತು ಆರೋಗ್ಯ ಸ್ಥಿತಿಯನ್ನು ನಿರ್ವಹಿಸಿ.',
        'btn-add-cow': 'ಹೊಸ ಹಸುವನ್ನು ಸೇರಿಸಿ',
        'hdr-herd-list': 'ಹಿಂಡಿನ ಪಟ್ಟಿ',
        'tbl-tag': 'ಟ್ಯಾಗ್ ಐಡಿ',
        'tbl-age': 'ವಯಸ್ಸು',
        'tbl-health': 'ಆರೋಗ್ಯ',
        'tbl-owner': 'ಮಾಲೀಕರು',
        'ph-tag': 'ಟ್ಯಾಗ್ ಐಡಿ',
        'ph-age': 'ವಯಸ್ಸು',
        'ph-owner': 'ಮಾಲೀಕರು',
        'opt-select-status': 'ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        'opt-healthy': 'ಆರೋಗ್ಯಕರ',
        'opt-sick': 'ಅನಾರೋಗ್ಯ',
        'opt-pregnant': 'ಗರ್ಭಿಣಿ',
        'srv-title': 'ನಮ್ಮ ಸೇವೆಗಳು',
        'srv-subtitle': 'ಆಧುನಿಕ ಜಾನುವಾರು ನಿರ್ವಹಣೆಗಾಗಿ ಸಮಗ್ರ ಸಾಧನಗಳು.',
        'srv-health-hub': 'ಆರೋಗ್ಯ ಕೇಂದ್ರ',
        'srv-health-desc': 'ಎಐ ಮುನ್ಸೂಚನೆ ಮತ್ತು ರೋಗ ಸ್ಕ್ಯಾನಿಂಗ್',
        'srv-trade': 'ಸ್ಮಾರ್ಟ್ ವ್ಯಾಪಾರ',
        'srv-trade-desc': 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಅಂದಾಜು ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು',
        'srv-advisory': 'ಸಲಹೆ',
        'srv-advisory-desc': 'ತಜ್ಞರ ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಉತ್ತಮ ಅಭ್ಯಾಸಗಳು',
        'srv-grants': 'ಸರ್ಕಾರಿ ಅನುದಾನಗಳು',
        'srv-grants-desc': 'ಸಬ್ಸಿಡಿ ಮತ್ತು ಆರ್ಥಿಕ ಸಹಾಯ ಮಾಹಿತಿ',
        'dash-active-trades': 'ಸಕ್ರಿಯ ವ್ಯಾಪಾರಗಳು',
        'dash-govt-grants': 'ಸರ್ಕಾರಿ ಅನುದಾನಗಳು',
        'dash-health-ai': 'ಹೆಲ್ತ್ ಎಐ',
        'lbl-breed': 'ತಳಿ',
        'lbl-weight': 'ತೂಕ (ಕೆಜಿ)',
        'lbl-age': 'ವಯಸ್ಸು (ತಿಂಗಳು)',
        'lbl-milk': 'ಹಾಲು (ಲೀಟರ್)',
        'lbl-preg': 'ಗರ್ಭಾವಸ್ಥೆ (ತಿಂಗಳು)',
        'lbl-nose': 'ಮೂಗು ಸೋರುವಿಕೆ?',
        'lbl-breath': 'ಉಸಿರಾಟದ ಶಬ್ದ?',
        'lbl-fever': 'ಜ್ವರ?',
        'lbl-high-fever': 'ತೀವ್ರ ಜ್ವರ',
        'lbl-low-appetite': 'ಕಡಿಮೆ ಹಸಿವು?',
        'btn-calc': 'ಬೆಲೆ ಲೆಕ್ಕಹಾಕಿ',
        'btn-scan': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
        'total-cattle': 'ಒಟ್ಟು ಜಾನುವಾರು',
        'health-alerts': 'ಆರೋಗ್ಯ ಎಚ್ಚರಿಕೆಗಳು',
        'market-rate': 'ಸರಾಸರಿ ಸ್ಥಳೀಯ ದರ',
        'weather': 'ಹವಾಮಾನ',
        'recent-activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
        'opt-gir': 'ಗಿರ್ (ದೇಸಿ)',
        'opt-sahiwal': 'ಸಾಹಿವಾಲ್',
        'opt-redsindhi': 'ಕೆಂಪು ಸಿಂಧಿ',
        'opt-tharparkar': 'ಥಾರ್ಪಾರ್ಕರ್',
        'opt-jersey': 'ಜರ್ಸಿ',
        'opt-holstein': 'ಹೋಲ್ಸ್ಟೀನ್',

        'lbl-vaccination': 'ಲಸಿಕೆ ಸ್ಥಿತಿ',
        'lbl-lactation': 'ಹಾಲುಣಿಸುವ ಚಕ್ರ (1-10)',
        'lbl-disease-hist': 'ರೋಗ ಇತಿಹಾಸ',
        'opt-vac-none': 'ಯಾವುದೂ ಇಲ್ಲ / ತಿಳಿದಿಲ್ಲ',
        'opt-vac-partial': 'ಭಾಗಶಃ ಲಸಿಕೆ ಹಾಕಲಾಗಿದೆ',
        'opt-vac-full': 'ಸಂಪೂರ್ಣವಾಗಿ ಲಸಿಕೆ ಹಾಕಲಾಗಿದೆ',
        'dis-fmd': 'ಕಾಲುಬಾಯಿ ಜ್ವರ (FMD)',
        'dis-mastitis': 'ಕೆಚ್ಚಲು ಬಾವು (Mastitis)',
        'dis-brucellosis': 'ಬ್ರೂಸೆಲೋಸಿಸ್',


        'dash-infra': 'ಫಾರ್ಮ್ ಮೂಲಸೌಕರ್ಯ',
        'subtitle-dashboard': 'ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮ್ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ',
        'status-db': 'DB ಸಂಪರ್ಕಗೊಂಡಿದೆ',
        'status-live': 'ಲೈವ್',
        'unit-kg': '/ಕೆಜಿ',
        'chart-milk': 'ಹಾಲಿನ ಇಳುವರಿ (ಲೀಟರ್)',
        'disclaimer-gps': '*ನಿಮ್ಮ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಆಧರಿಸಿ',
        'dash-acres': 'ಎಕರೆ',
        'dash-sheds': 'ಶೆಡ್ಗಳು',
        'dash-cctv': 'CCTV ಲೈವ್',
        'dash-feed': 'ಮೇವು ಸಂಗ್ರಹ',
        'dash-water': 'ನೀರಿನ ಟ್ಯಾಂಕ್',
        'dash-trends': 'ಉತ್ಪಾದನೆ ಪ್ರವೃತ್ತಿಗಳು',
        'dash-sick': 'ಅನಾರೋಗ್ಯ ಇತಿಹಾಸ',
        'dash-no-sick': 'ಯಾವುದೇ ದಾಖಲೆಗಳಿಲ್ಲ.',
        'dash-vets': 'ಹತ್ತಿರದ ಪಶುವೈದ್ಯಕೀಯ ಆಸ್ಪತ್ರೆಗಳು',
        'dash-nav': 'ನ್ಯಾವಿಗೇಟ್',
        'dash-view-map': 'ನಕ್ಷೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
        'trade-subtitle': 'AI ಚಾಲಿತ ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ',
        'grp-desi': 'ಭಾರತೀಯ ದೇಶೀಯ (ದೇಸಿ)',
        'grp-exotic': 'ವಿದೇಶಿ / ಮಿಶ್ರತಳಿ',
        'opt-murrah': 'ಮುರ್ರ ಎಮ್ಮೆ',
        'msg-analyzing': 'AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
        'hint-qr': 'Google Lens ಬಳಸಿ • ವಿವರಗಳನ್ನು ತಕ್ಷಣ ಉಳಿಸಿ',
        'lbl-forecast': '6-ತಿಂಗಳ ಮುನ್ಸೂಚನೆ',
        'adv-critical': 'ತುರ್ತು ಗಮನ ನೀಡಬೇಕಿದೆ. ತಕ್ಷಣ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',

        'cert-title': 'ಮೌಲ್ಯಮಾಪನ ವರದಿ',
        'cert-subtitle': 'ಕ್ಯಾಟಲ್ ಕೇರ್ AI ನಿಂದ ಪ್ರಮಾಣೀಕರಿಸಲಾಗಿದೆ',
        'cert-value': 'ಅಂದಾಜು ಬೆಲೆ',
        'cert-confidence': 'ನಿಖರತೆ',
        'cert-proof': 'ಬೆಲೆ ವಿವರ (ಪುರಾವೆ)',
        'cert-base': 'ತೂಕದ ಮೌಲ್ಯ',
        'cert-milk': 'ಹಾಲಿನ ಬೋನಸ್',
        'cert-preg': 'ಗರ್ಭಾವಸ್ಥೆಯ ಬೋನಸ್',
        'cert-age': 'ವಯಸ್ಸಿನ ಕಡಿತ',
        'cert-analysis': 'AI ತಜ್ಞರ ವಿಶ್ಲೇಷಣೆ',
        'cert-footer': 'ಜೆಮಿನಿ AI ನಿಂದ ರಚಿಸಲಾಗಿದೆ',
        'btn-download': 'PDF ಡೌನ್‌ಲೋಡ್',
        'qr-scan': 'ಫೋನ್‌ನಲ್ಲಿ ಉಳಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',

        'adv-chat-placeholder': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
        'adv-chat-send': 'ಕಳುಹಿಸಿ',
        'adv-welcome-msg': 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಪಶುವೈದ್ಯಕೀಯ ತಜ್ಞ. ಇಂದು ನಾನು ನಿಮ್ಮ ಜಾನುವಾರುಗಳಿಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
        'adv-typing': 'ತಜ್ಞರು ಬರೆಯುತ್ತಿದ್ದಾರೆ...',

        // Dashboard Steps
        'step-1-title': 'ಜಾನುವಾರು ನೋಂದಣಿ',
        'step-1-desc': 'ಟ್ರ್ಯಾಕಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಹಿಂಡಿನ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ.',
        'step-2-title': 'ಆರೋಗ್ಯ ಮಾನಿಟರ್',
        'step-2-desc': 'ಕ್ಷೇಮವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಎಐ ರೋಗ ಸ್ಕ್ಯಾನರ್ ಬಳಸಿ.',
        'step-3-title': 'ಸೇವೆಗಳು',
        'step-3-desc': 'ನ್ಯಾಯಯುತ ವ್ಯಾಪಾರ ಬೆಲೆಗಳು ಮತ್ತು ಸರ್ಕಾರಿ ಅನುದಾನಗಳನ್ನು ಪಡೆಯಿರಿ.',

        // Advisory Tabs
        'adv-tab-general': 'ಸಾಮಾನ್ಯ ಸಲಹೆ',
        'adv-tab-nutrition': 'ಪೋಷಣೆ ಸಲಹೆ',

        'btn-camera': 'ಕ್ಯಾಮರಾ ತೆರೆಯಿರಿ',
        'btn-capture': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
        'btn-retake': 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
        'lbl-analyzing': 'AI ಚಿತ್ರವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಿದೆ...',
        'p-disease-guide': 'ತ್ವರಿತ ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಕ್ಯಾಮೆರಾವನ್ನು ಪೀಡಿತ ಪ್ರದೇಶದ (ಚರ್ಮ, ಕಣ್ಣುಗಳು, ಬಾಯಿ) ಕಡೆಗೆ ಇರಿಸಿ.',
        'skin-check-title': 'ಚರ್ಮದ ಆರೋಗ್ಯದ ಪೂರ್ವ-ಪರಿಶೀಲನೆ',
        'q-skin-rash': 'ನಿಮಗೆ ಯಾವುದಾದರೂ ದದ್ದುಗಳು, ಗುಳ್ಳೆಗಳು ಅಥವಾ ಚರ್ಮದ ಗಾಯಗಳು ಕಂಡುಬರುತ್ತವೆಯೇ?',
        'q-from-birth': 'ಈ ಗುರುತು ಹುಟ್ಟಿನಿಂದಲೇ ಇದೆಯೇ?',
        'q-skin-change': 'ಇತ್ತೀಚೆಗೆ ಏನಾದರೂ ಬದಲಾವಣೆಗಳಿವೆಯೇ (ಗಾತ್ರ, ಬಣ್ಣ, ರಕ್ತಸ್ರಾವ)?',
        'msg-benign': 'ಇದು ಹುಟ್ಟುಜನ್ಮದ ಗುರುತಿರಬಹುದು. ನಿಮಗೆ ಇನ್ನೂ ಕಾಳಜಿಯಿದ್ದರೆ ನೀವು ಸ್ಕ್ಯಾನ್ ಮಾಡಬಹುದು.',
        'msg-consult': 'ನಿಖರವಾದ ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ನಾವು ರೋಗದ ಸ್ಕ್ಯಾನ್ ನಡೆಸಲು ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ.',
        'btn-continue': 'ಮುಂದುವರಿಸಿ',
        'btn-check-disease': 'ರೋಗ ತಪಾಸಣೆ ಮಾಡಿ',
        'opt-yes': 'ಹೌದು',
        'opt-no': 'ಇಲ್ಲ',
        'lbl-vet-dermatologist': 'ಎಐ-ಚಾಲಿತ ಪಶುವೈದ್ಯಕೀಯ ಚರ್ಮರೋಗ ತಜ್ಞ',
        'btn-upload-photo': 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        'btn-live-camera': 'ಲೈವ್ ಕ್ಯಾಮೆರಾ',
        'btn-remove': 'ತೆಗೆದುಹಾಕಿ',
        'btn-run-analysis': 'ಎಐ ವಿಶ್ಲೇಷಣೆ ನಡೆಸಿ',
        'lbl-low-appetite': 'ಹಸಿವು ಕಡಿಮೆಯಿದೆಯೇ?',
        'ph-vitals-history': 'ಉದಾ: ಎಡಗಾಲಿನಲ್ಲಿ ಹಿಂದಿನ ಸೋಂಕು...',
        'msg-connecting-gemini': 'ಜೆಮಿನಿ ಎಐಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
        'lbl-ai-recommendation': 'ಎಐ ಶಿಫಾರಸು',
        'lbl-detected': 'ಪತ್ತೆಯಾಗಿದೆ',
        'lbl-confidence': 'ಭರವಸೆ',
        'lbl-ready-scan': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಸಿದ್ಧವಾಗಿದೆ',
        'msg-upload-start': 'ಎಐ ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಲು ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        'msg-complete-precheck': 'ಸ್ಕ್ಯಾನಿಂಗ್ ಸಕ್ರಿಯಗೊಳಿಸಲು ಪೂರ್ವ-ಪರಿಶೀಲನೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ',
        'upload-text': 'ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ',
        'upload-instruction': 'ಗ್ಯಾಲರಿಯಿಂದ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ',
        'lbl-location': 'ಸ್ಥಳ',
        'lbl-temperature': 'ತಾಪಮಾನ (°F)',
        'lbl-pregnancy': 'ಗರ್ಭಧಾರಣೆಯ ಸ್ಥಿತಿ',
        'lbl-fever': 'ಜ್ವರ?',
        'lbl-high-fever': 'ಹೆಚ್ಚಿನ ಜ್ವರ',
        'ph-age': 'ಉದಾ: 4',
        'ph-weight': 'ಕೆಜಿ',
        'ph-temp': '°F',
        'ph-milk': 'ಲೀಟರ್',

        // System Demo Keys
        'sys-header': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಡೆಮೊ',
        'sys-s1-title': 'ನಾವೀನ್ಯತೆ ಕಾರ್ಯತಂತ್ರ ಮತ್ತು ಪ್ರಮುಖ ಕೆಲಸದ ಹರಿವು',
        'sys-farmers': 'ರೈತರು',
        'sys-frontend': 'ಇಂಟರ್ಫೇಸ್ ಲೇಯರ್',
        'sys-backend': 'ನಿರ್ಧಾರ ಎಂಜಿನ್',
        'sys-hybrid': 'ನ್ಯೂರಲ್ ಕೋರ್',
        'sys-datalayer': 'ಜ್ಞಾನ ಕೇಂದ್ರ',
        'sys-mobile-web': 'ಮಲ್ಟಿ-ಮೋಡಲ್ ಸಂವಹನ',
        'sys-react-vite': 'ರೆಸ್ಪಾನ್ಸಿವ್ ರಿಯಾಕ್ಟ್ ಪರಿಸರ ವ್ಯವಸ್ಥೆ',
        'sys-flask': 'ಪೈಥಾನ್ ವಿತರಿಸಿದ ಮೈಕ್ರೋಸರ್ವಿಸಸ್',
        'sys-ml-gemini': 'ಹೈಬ್ರಿಡ್ ವಿಷನ್ + ಲಾರ್ಜ್ ಲ್ಯಾಂಗ್ವೇಜ್ ಮಾಡೆಲ್',
        'sys-mongo': 'ಇನ್-ಮೆಮೊರಿ / ಮೊಂಗೋಡಿಬಿ',
        'sys-s1-subtitle': 'ಮೂಲಸೌಕರ್ಯ ಅವಲೋಕನ',
        'sys-s1-desc-text': 'ಕ್ಯಾಟಲ್ ಕೇರ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಗ್ರಾಮೀಣ ಫೀಲ್ಡ್ ಡೇಟಾವನ್ನು ಆಧುನಿಕ ಎಐನೊಂದಿಗೆ ಸಂಯೋಜಿಸುವ ಉನ್ನತ-ಸಮಕಾಲಿಕ ಅರ್ಕಿಟೆಕ್ಚರ್ ಮೇಲೆ ನಿರ್ಮಿಸಲಾಗಿದೆ. ನಾವು ಮೂರು ಹಂತದ ವಿನ್ಯಾಸ ತಂತ್ರವನ್ನು ಬಳಸುತ್ತೇವೆ: **ಎಡ್ಜ್ ಇಂಟರಾಕ್ಷನ್**, **ಸ್ಕೇಲೆಬಲ್ ಬ್ಯಾಕೆಂಡ್**, ಮತ್ತು **ಹೈಬ್ರಿಡ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ರೀಸನಿಂಗ್**. ಈ ನೇರ ಜೋಡಣೆಯು ನಮ್ಮ 4 ಪ್ರಮುಖ ಉದ್ದೇಶಗಳನ್ನು ದಕ್ಷತೆ ಮತ್ತು ಭದ್ರತೆಯೊಂದಿಗೆ ಪೂರೈಸುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.',
        'sys-s1-p1-title': 'ಗ್ರಾಮೀಣ-ಪ್ರಥಮ ವಿನ್ಯಾಸ',
        'sys-s1-p1-desc': 'ಆಫ್‌ಲೈನ್-ಫಸ್ಟ್ ಸಾಮರ್ಥ್ಯಗಳೊಂದಿಗೆ ಕಡಿಮೆ-ಬ್ಯಾಂಡ್ವಿಡ್ತ್ ವಲಯಗಳಿಗೆ ಆಪ್ಟಿಮೈಸ್ ಮಾಡಲಾಗಿದೆ.',
        'sys-s1-p2-title': 'ಎಐ ಸ್ಕೇಲೆಬಿಲಿಟಿ',
        'sys-s1-p2-desc': 'ಅಧಿಕ-ತೀವ್ರತೆಯ ವಿಷನ್ ಮತ್ತು ಮುನ್ಸೂಚಕ ಕಾರ್ಯಗಳಿಗಾಗಿ ಸ್ಥಿತಿಸ್ಥಾಪಕ ಕಂಪ್ಯೂಟ್ ಸಂಪನ್ಮೂಲಗಳು.',
        'sys-s1-p3-title': 'ಡೇಟಾ ಸುರಕ್ಷತೆ',
        'sys-s1-p3-desc': 'ಎಲ್ಲಾ ರೈತರ ಡೇಟಾ ಮತ್ತು ಜಾನುವಾರು ವೈದ್ಯಕೀಯ ಇತಿಹಾಸಕ್ಕಾಗಿ ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್.',
        'sys-farmers-desc': 'ಮೊಬೈಲ್, ವೆಬ್ ಮತ್ತು ವಾಯ್ಸ್ ಮೂಲಕ ಓಮ್ನಿಚಾನಲ್ ಪ್ರವೇಶ.',
        'sys-frontend-desc': 'ದ್ರವ ಯುಐಗಾಗಿ ಟೈಲ್‌ವಿಂಡ್‌ನೊಂದಿಗೆ ವಿಟ್ ಎಸ್‌ಪಿಎ.',
        'sys-backend-desc': 'ಫ್ಲಾಸ್ಕ್ ಗೇಟ್‌ವೇ ಬಳಸುವ ರೆಸ್ಟ್‌ಫುಲ್ ಮೈಕ್ರೋಸರ್ವಿಸಸ್.',
        'sys-intelligence-desc': 'ಎಫಿಷಿಯೆಂಟ್ ನೆಟ್ ವಿಷನ್ + ಜೆಮಿನಿ ಸೆಮ್ಯಾಂಟಿಕ್ ರೀಸನಿಂಗ್.',
        'sys-datalayer-desc': 'ಪ್ರೊಫೈಲ್‌ಗಳು ಮತ್ತು ಟೈಮ್-ಸೀರೀಸ್ ಡೇಟಾಕ್ಕಾಗಿ ಹೈಬ್ರಿಡ್ ಸ್ಟೋರೇಜ್.',

        'sys-obj-header': 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನ ಪ್ರಮುಖ ಉದ್ದೇಶಗಳು',
        'sys-obj-1-t': 'ಆರೋಗ್ಯ ಭದ್ರತೆ',
        'sys-obj-1-d': 'ಜಾನುವಾರು ರೋಗಗಳನ್ನು ತ್ವರಿತವಾಗಿ ಪತ್ತೆಹಚ್ಚಲು AI ಆಧಾರಿತ ಸ್ಕ್ಯಾನಿಂಗ್.',
        'sys-obj-2-t': 'ನ್ಯಾಯಯುತ ಮಾರುಕಟ್ಟೆ ವ್ಯಾಪಾರ',
        'sys-obj-2-d': 'ಪ್ರತಿ ರೈತರಿಗೆ ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ಖಚಿತಪಡಿಸುವ ಅಲ್ಗಾರಿದಮಿಕ್ ಮೌಲ್ಯಮಾಪನ.',
        'sys-obj-3-t': 'ಕೈಗೆಟುಕುವ ಸೇವೆ',
        'sys-obj-3-d': 'ಡಿಜಿಟಲ್ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡುವ ಬಹುಭಾಷಾ ಧ್ವನಿ ಬೆಂಬಲ.',
        'sys-obj-4-t': 'ಡೇಟಾ ಚಾಲಿತ ಒಳನೋಟಗಳು',
        'sys-obj-4-d': 'ಹಾಲಿನ ಇಳುವರಿ ಮತ್ತು ಆರೋಗ್ಯ ಮುನ್ಸೂಚನೆಗಾಗಿ ಮುನ್ಸೂಚಕ ವಿಶ್ಲೇಷಣೆ.',
        'sys-obj-interaction': 'ರೈತರು **ಇಂಟರ್ಫೇಸ್** ಮೂಲಕ **ಆರೋಗ್ಯ ಭದ್ರತೆ**ಗಾಗಿ ಜಾನುವಾರುಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಾರೆ. ನಮ್ಮ **ಇಂಟೆಲಿಜೆನ್ಸ್ ಕೋರ್** **ನ್ಯಾಯಯುತ ವ್ಯಾಪಾರ**ಕ್ಕಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ, ಹಾಗೂ **ವಾಯ್ಸ್ ಎಐ** **ಗೆಟುಕುವ ಸೇವೆ**ಯನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ. ಎಲ್ಲಾ ಡೇಟಾ **ಮುನ್ಸೂಚಕ ಒಳನೋಟಗಳಿಗಾಗಿ** **ಜ್ಞಾನ ಕೇಂದ್ರ**ಕ್ಕೆ ಸೇರುತ್ತದೆ.',

        'meth-title-1': 'ಕಾರ್ಯವಿಧಾನ: ಆರೋಗ್ಯ ಭದ್ರೆತೆ',
        'meth-title-2': 'ಕಾರ್ಯವಿಧಾನ: ನ್ಯಾಯಯುತ ಮಾರುಕಟ್ಟೆ ವ್ಯಾಪಾರ',
        'meth-title-3': 'ಕಾರ್ಯವಿಧಾನ: ಕೈಗೆಟುಕುವ ಸೇವೆ',
        'meth-title-4': 'ಕಾರ್ಯವಿಧಾನ: ಡೇಟಾ ಚಾಲಿತ ಒಳನೋಟಗಳು',
        'sys-view-meth': 'ಕಾರ್ಯವಿಧಾನವನ್ನು ವೀಕ್ಷಿಸಿ →',

        'sys-s2-title': 'ಎಂಡ್-ಟು-ಎಂಡ್ ಇಂಡಿಕ್ ಬಹುಭಾಷಾ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
        'sys-s2-hybrid-title': 'ಇಂಡಿಕ್‌ವೇವ್2ವೆಕ್ + ಜೆಮಿನಿ ಹೈಬ್ರಿಡ್',
        'sys-s2-desc': 'ಫೋನೆಟಿಕ್ ಡಿಕೋಡಿಂಗ್‌ಗಾಗಿ **ಪೂರ್ವ-ತರಬೇತಿ ಪಡೆದ ಅಕೌಸ್ಟಿಕ್ ಮಾಡೆಲ್‌ಗಳು** ಮತ್ತು ಕ್ರಾಸ್-ಲಿಂಗ್ವಿಸ್ಟಿಕ್ ಸೆಮ್ಯಾಂಟಿಕ್ ರೀಸನಿಂಗ್‌ಗಾಗಿ **ಜೆಮಿನಿ 1.5 ಪ್ರೊ** ಅನ್ನು ಸಂಯೋಜಿಸುವ ಹೈಬ್ರಿಡ್ ಆರ್ಕಿಟೆಕ್ಚರ್.',
        'sys-s2-neural-stats': 'ನ್ಯೂರಲ್ ಅಂಕಿಅಂಶಗಳು',
        'sys-s2-model': 'ಮಾಡೆಲ್',
        'sys-s2-params': 'ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು',
        'sys-s2-latency': 'ಲೇಟೆನ್ಸಿ',
        'sys-s2-pipeline-title': 'ಕ್ರಾಸ್-ಲಿಂಗ್ವಿಸ್ಟಿಕ್ ಇನ್ಫರೆನ್ಸ್ ಪೈಪ್‌ಲೈನ್',
        'sys-s2-raw-audio': 'ರಾ ಆಡಿಯೋ',
        'sys-s2-feat-extract': 'ಫೀಚರ್ ಎಕ್ಸ್‌ಟ್ರಾಕ್ಷನ್',
        'sys-s2-phoneme-map': 'ಇಂಡಿಕ್‌ವೇವ್2ವೆಕ್ + ಜೆಮಿನಿ',
        'sys-s2-action': 'ಕ್ರಿಯೆ',

        'sys-s3-title': 'ಸಂದರ್ಭ-ಅರಿವಿನ ಉತ್ಪಾದಕ ತಾರ್ಕಿಕತೆ',
        'sys-s3-role-prompt': 'ಪಾತ್ರ-ಆಧಾರಿತ ಪ್ರಾಂಪ್ಟ್ ಎಂಜಿನಿಯರಿಂಗ್',
        'sys-s3-desc': 'ರಚನಾತ್ಮಕ ಇತಿಹಾಸ ಮತ್ತು ಕಟ್ಟುನಿಟ್ಟಾದ ವರ್ತನೆಯ ಸೂಚನೆಗಳನ್ನು ನೀಡುವ ಮೂಲಕ ಪ್ರಮಾಣಿತ LLM ಅನ್ನು ವಿಶೇಷ ಪಶುವೈದ್ಯಕೀಯ ಅಥವಾ ಪೌಷ್ಟಿಕಾಂಶ ತಜ್ಞರನ್ನಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ.',
        'sys-s3-cog-func': 'ಅರಿವಿನ ಕಾರ್ಯಗಳು',
        'sys-s3-persona-switch': 'ಡೈನಾಮಿಕ್ ಪರ್ಸನಾ ಸ್ವಿಚಿಂಗ್',
        'sys-s3-concise': 'ಸಂಕ್ಷಿಪ್ತ ಔಟ್‌ಪುಟ್ (ವಾಯ್ಸ್)',
        'sys-s3-pipe-title': 'ಸಂಭಾಷಣೆ ಪೈಪ್‌ಲೈನ್',
        'sys-s3-user-query': 'ಬಳಕೆದಾರರ ಪ್ರಶ್ನೆ',
        'sys-s3-ctx-engine': 'ಸಂದರ್ಭ ಎಂಜಿನ್',
        'sys-s3-gemini-llm': 'ಜೆಮಿನಿ LLM',
        'sys-s3-expert-advice': 'ತಜ್ಞರ ಸಲಹೆ',

        'sys-s4-title': 'ಮುನ್ಸೂಚಕ ಫಾರ್ಮ್ ಅನಾಲಿಟಿಕ್ಸ್ (TFT)',
        'sys-s4-tft-title': 'ಟೆಂಪೋರಲ್ ಫ್ಯೂಷನ್ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್',
        'sys-s4-desc': '**ಮಲ್ಟಿ-ಹಾರಿಜನ್ ಕ್ವಾಂಟೈಲ್ ರಿಕರೆಂಟ್ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್** ಮೂಲಕ ಚಾಲಿತವಾಗಿದೆ. ಹಾಲಿನ ಇಳುವರಿಯನ್ನು ಮುನ್ಸೂಚಿಸಲು **TFT** ಮತ್ತು ನೈಜ-ಸಮಯದ ವೈಪರೀತ್ಯಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು **ಐಸೊಲೇಷನ್ ಫಾರೆಸ್ಟ್** ಅನ್ನು ಬಳಸುತ್ತದೆ.',
        'sys-s4-model-specs': 'ಮಾಡೆಲ್ ಸ್ಪೆಕ್ಸ್',
        'sys-s4-forecasting': 'ಮುನ್ಸೂಚನೆ',
        'sys-s4-horizon': 'ಹಾರಿಜನ್',
        'sys-s4-error-rate': 'ದೋಷ ದರ',
        'sys-s4-pipe-title': 'ಅನಾಲಿಟಿಕ್ಸ್ ಪೈಪ್‌ಲೈನ್',
        'sys-s4-hist-data': 'ಐತಿಹಾಸಿಕ ಡೇಟಾ',
        'sys-s4-sliding-win': 'ಸ್ಲೈಡಿಂಗ್ ವಿಂಡೋ',
        'sys-s4-ensemble': 'ಎನ್ಸೆಂಬಲ್ ಕೋರ್',
        'sys-s4-smart-insight': 'ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳು',
        'dash-no-sick': 'ಯಾವುದೇ ದಾಖಲೆಗಳಿಲ್ಲ.',

        // Breeds & Locations
        'opt-gir': 'ಗಿರ್',
        'opt-sahiwal': 'ಸಾಹಿವಾಲ್',
        'opt-redsindhi': 'ಕೆಂಪು ಸಿಂಧಿ',
        'opt-tharparkar': 'ಥಾರ್ಪಾರ್ಕರ್',
        'opt-jersey': 'ಜರ್ಸಿ',
        'opt-holstein': 'ಹೋಲ್ಸ್ಟೀನ್ ಫ್ರೀಸಿಯನ್',
        'opt-hfcross': 'ಎಚ್ಎಫ್ ಕ್ರಾಸ್',
        'opt-murrah': 'ಮುರ್ರಾ',
        'opt-unknown': 'ಅಜ್ಞಾತ / ಇತರ',

        // States
        'st-karnataka': 'ಕರ್ನಾಟಕ',
        'st-goa': 'ಗೋವಾ',
        'st-andhrapradesh': 'ಆಂಧ್ರ ಪ್ರದೇಶ',
        'st-telangana': 'ತೆಲಂಗಾಣ',
        'st-tamilnadu': 'ತಮಿಳುನಾಡು',
        'st-kerala': 'ಕೇರಳ',
        'st-maharashtra': 'ಮಹಾರಾಷ್ಟ್ರ',
        'st-gujarat': 'ಗುಜರಾತ್',
        'st-madhyapradesh': 'ಮಧ್ಯಪ್ರದೇಶ',
        'st-uttarpradesh': 'ಉತ್ತರ ಪ್ರದೇಶ',
        'st-arunachalpradesh': 'ಅರುಣಾಚಲ ಪ್ರದೇಶ',
        'st-assam': 'ಅಸ್ಸಾಂ',
        'st-bihar': 'ಬಿಹಾರ',
        'st-chhattisgarh': 'ಛತ್ತೀಸ್‌ಗಢ',
        'st-haryana': 'ಹರಿಯಾಣ',
        'st-himachalpradesh': 'ಹಿಮಾಚಲ ಪ್ರದೇಶ',
        'st-jharkhand': 'ಜಾರ್ಖಂಡ್',
        'st-manipur': 'ಮಣಿಪುರ',
        'st-meghalaya': 'ಮೇಘಾಲಯ',
        'st-mizoram': 'ಮಿಜೋರಾಂ',
        'st-nagaland': 'ನಾಗಾಲ್ಯಾಂಡ್',
        'st-odisha': 'ಒಡಿಶಾ',
        'st-punjab': 'ಪಂಜಾಬ್',
        'st-rajasthan': 'ರಾಜಸ್ಥಾನ',
        'st-sikkim': 'ಸಿಕ್ಕಿಂ',
        'st-tripura': 'ತ್ರಿಪುರ',
        'st-uttarakhand': 'ಉತ್ತರಾಖಂಡ',
        'st-westbengal': 'ಪಶ್ಚಿಮ ಬಂಗಾಳ'
    },
    'ml-IN': {
        'title-dashboard': 'കന്നുകാലി ഡാഷ്ബോർഡ്',
        'title-trade': 'വ്യാപാരം (ട്രേഡ്)',
        'title-disease': 'രോഗ പരിശോധന',
        'title-advisory': 'വിദഗ്ദ്ധ ഉപദേശം',
        'logo': 'കാറ്റിൽ കെയർ',
        'nav-dashboard': 'ഡാഷ്ബോർഡ്',
        'nav-trade': 'സ്മാർട്ട് ട്രേഡ്',
        'nav-disease': 'രോഗ പരിശോധന',
        'nav-advisory': 'ഉപദേശം',
        'nav-cows': 'എന്റെ കന്നുകാലികൾ',
        'nav-services': 'സേവനങ്ങൾ',
        'nav-alerts': 'അറിയിപ്പുകൾ',
        'nav-settings': 'ക്രമീകരണങ്ങൾ',
        'alerts-title': 'അറിയിപ്പുകൾ',
        'alerts-subtitle': 'നിങ്ങളുടെ കന്നുകാലികളെക്കുറിച്ചുള്ള പ്രധാന അപ്‌ഡേറ്റുകൾ.',
        'alerts-empty': 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല.',
        'settings-title': 'ക്രമീകരണങ്ങൾ',
        'settings-subtitle': 'നിങ്ങളുടെ അക്കൗണ്ടും മുൻഗണനകളും നിയന്ത്രിക്കുക.',
        'stg-account': 'കർഷക അക്കൗണ്ട്',
        'stg-signout': 'പുറത്തുകടക്കുക',
        'stg-pref': 'മുൻഗണനകൾ',
        'stg-lang': 'ഭാഷ',
        'stg-theme': 'തീം',
        'stg-notif': 'അറിയിപ്പുകൾ',
        'stg-push': 'പുഷ് അറിയിപ്പുകൾ',
        'stg-email': 'ഇമെയിൽ അലേർട്ടുകൾ',
        'stg-security': 'സുരക്ഷ',
        'stg-change-pw': 'പാസ്‌വേഡ് മാറ്റുക',
        'stg-save': 'മാറ്റങ്ങൾ വരുത്തുക',
        'grants-title': 'സർക്കാർ ഗ്രാന്റുകൾ',
        'grants-subtitle': 'നിങ്ങളുടെ ഫാമിന് ലഭ്യമായ ഗ്രാന്റുകളും സബ്‌സിഡികളും കണ്ടെത്തുക.',
        'grants-new': 'പുതിയ ഗ്രാന്റ് (അഡ്മിൻ)',
        'grants-schemes': 'ലഭ്യമായ പദ്ധതികൾ',
        'grants-apply': 'അപേക്ഷിക്കുക',
        'predict-title': 'ഹെൽത്ത് എഐ',
        'predict-subtitle': 'ആരോഗ്യ പ്രശ്നങ്ങൾ കണ്ടെത്താൻ ലക്ഷണങ്ങൾ പരിശോധിക്കുക.',
        'pred-enter-vitals': 'വിവരങ്ങൾ നൽകുക',
        'pred-temp': 'താപനില (°C)',
        'pred-appetite': 'വിശപ്പ് (1-10)',
        'pred-mobility': 'ചലനം (1-10)',
        'pred-run': 'പരിശോധിക്കുക',
        'pred-analyzing': 'വിശകലനം ചെയ്യുന്നു...',
        'pred-result-placeholder': 'ഫലം കാണാൻ വിവരങ്ങൾ നൽകുക.',
        'pred-note': 'ശ്രദ്ധിക്കുക: ഇതൊരു AI നിഗമനമാണ്. ദയവായി ഡോക്ടറെ കാണുക.',
        'cows-title': 'എന്റെ കന്നുകാലികൾ',
        'cows-subtitle': 'നിങ്ങളുടെ കന്നുകാലി രജിസ്ട്രിയും ആരോഗ്യ നിലയും നിയന്ത്രിക്കുക.',
        'btn-add-cow': 'പുതിയ പശുവിനെ ചേർക്കുക',
        'hdr-herd-list': 'കന്നുകാലി ലിസ്റ്റ്',
        'tbl-tag': 'ടാഗ് ഐഡി',
        'tbl-age': 'പ്രായം',
        'tbl-health': 'ആരോഗ്യം',
        'tbl-owner': 'ഉടമ',
        'ph-tag': 'ടാഗ് ഐഡി',
        'ph-age': 'പ്രായം',
        'ph-owner': 'ഉടമ',
        'opt-select-status': 'അവസ്ഥ തിരഞ്ഞെടുക്കുക',
        'opt-healthy': 'ആരോഗ്യമുള്ള',
        'opt-sick': 'രോഗബാധിതൻ',
        'opt-pregnant': 'ഗർഭിണി',
        'srv-title': 'ഞങ്ങളുടെ സേവനങ്ങൾ',
        'srv-subtitle': 'നൂതന കന്നുകാലി പരിപാലനത്തിനുള്ള സമഗ്ര ഉപകരണങ്ങൾ.',
        'srv-health-hub': 'ഹെൽത്ത് ഹബ്',
        'srv-health-desc': 'AI പ്രവചനവും രോഗ സ്കാനിംഗും',
        'srv-trade': 'സ്മാർട്ട് ട്രേഡ്',
        'srv-trade-desc': 'ന്യായമായ വില കണക്കാക്കലും വിപണി പ്രവണതകളും',
        'srv-advisory': 'ഉപദേശം',
        'srv-advisory-desc': 'വിദഗ്ദ്ധ നിർദ്ദേശങ്ങളും മികച്ച രീതികളും',
        'srv-grants': 'സർക്കാർ ഗ്രാന്റുകൾ',
        'srv-grants-desc': 'സബ്‌സിഡിയും സാമ്പത്തിക സഹായ വിവരങ്ങളും',
        'dash-active-trades': 'സജീവ വ്യാപാരങ്ങൾ',
        'dash-govt-grants': 'സർക്കാർ ഗ്രാന്റുകൾ',
        'dash-health-ai': 'ഹെൽത്ത് എഐ',
        'lbl-breed': 'ഇനം',
        'lbl-weight': 'ഭാരം (കിലോ)',
        'lbl-age': 'പ്രായം (മാസം)',
        'lbl-milk': 'പാൽ (ലിറ്റർ)',
        'lbl-preg': 'ഗർഭകാലം (മാസം)',
        'btn-calc': 'വില കണക്കാക്കുക',
        'btn-scan': 'സ്കാൻ ചെയ്യുക',
        'total-cattle': 'ആകെ കന്നുകാലികൾ',
        'health-alerts': 'അലേർട്ടുകൾ',
        'market-rate': 'ശരാശരി പ്രാദേശിക നിരക്ക്',
        'weather': 'കാലാവസ്ഥ',
        'recent-activity': 'സമീപകാല പ്രവർത്തനങ്ങൾ',
        'opt-gir': 'ഗീർ (നാടൻ)',
        'opt-sahiwal': 'സാഹിവാൾ',
        'opt-redsindhi': 'റെഡ് സിന്ധി',
        'opt-tharparkar': 'തർപാർക്കർ',
        'opt-jersey': 'ജേഴ്സി',
        'opt-holstein': 'ഹോൾസ്റ്റീൻ',

        'dash-infra': 'ഫാം ഇൻഫ്രാസ്ട്രക്ചർ',
        'subtitle-dashboard': 'സ്മാർട്ട് ഫാം മാനേജ്മെന്റ് സിസ്റ്റം',
        'status-db': 'DB ബന്ധിപ്പിച്ചിരിക്കുന്നു',
        'status-live': 'ലൈവ്',
        'unit-kg': '/കിലോ',
        'chart-milk': 'പാൽ ഉൽപ്പാദനം (ലിറ്റർ)',
        'disclaimer-gps': '*നിങ്ങളുടെ GPS സ്ഥാനം അടിസ്ഥാനമാക്കി',
        'dash-acres': 'ഏക്കർ',
        'dash-sheds': 'ഷെഡുകൾ',
        'dash-cctv': 'CCTV ലൈവ്',
        'dash-feed': 'തീറ്റ ശേഖരം',
        'dash-water': 'വാട്ടർ ടാങ്ക്',
        'dash-trends': 'ഉൽപ്പാദന പ്രവണതകൾ',
        'dash-sick': 'രോഗ ചരിത്രം',
        'dash-no-sick': 'രേഖകൾ കണ്ടെത്തിയില്ല.',
        'dash-vets': 'അടുത്തുള്ള വെറ്റിനറി ആശുപത്രികൾ',
        'dash-nav': 'നാവിഗേറ്റ്',
        'dash-view-map': 'മാപ്പിൽ കാണുക',
        'trade-subtitle': 'AI അധിഷ്ഠിത മൂല്യനിർണ്ണയവും സാക്ഷ്യപ്പെടുത്തലും',
        'grp-desi': 'ഇന്ത്യൻ തദ്ദേശീയ (നാടൻ)',
        'grp-exotic': 'വിദേശ / സങ്കരയിനം',
        'opt-murrah': 'മുറ എരുമ',
        'msg-analyzing': 'AI വിശകലനം ചെയ്യുന്നു...',
        'hint-qr': 'Google Lens ഉപയോഗിക്കുക • വിശദാംശങ്ങൾ സേവ് ചെയ്യുക',
        'lbl-forecast': '6-മാസത്തെ പ്രവചനം',
        'adv-critical': 'അടിയന്തിര ശ്രദ്ധ ആവശ്യമാണ്. ഉടൻ വെറ്റിനറി ഡോക്ടറെ സമീപിക്കുക.',

        'cert-title': 'മൂല്യനിർണ്ണയ റിപ്പോർട്ട്',
        'cert-subtitle': 'Cattle Care AI സാക്ഷ്യപ്പെടുത്തിയത്',
        'cert-value': 'കണക്കാക്കിയ വില',
        'cert-confidence': 'കൃത്യത',
        'cert-proof': 'വില വിവരങ്ങൾ (തെളിവ്)',
        'cert-base': 'ഭാരത്തിന്റെ മൂല്യം',
        'cert-milk': 'പാൽ ബോണസ്',
        'cert-preg': 'ഗർഭകാല ബോണസ്',
        'cert-age': 'പ്രായത്തിന്റെ കുറവ്',
        'cert-analysis': 'AI വിദഗ്ദ്ധ വിശകലനം',
        'cert-footer': 'ജെമിനി AI തയ്യാറാക്കിയത്',
        'btn-download': 'PDF ഡൗൺലോഡ്',
        'qr-scan': 'ഫോണിൽ സേവ് ചെയ്യാൻ സ്കാൻ ചെയ്യുക',

        'adv-chat-placeholder': 'നിങ്ങളുടെ ചോദ്യം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
        'adv-chat-send': 'അയക്കുക',
        'adv-welcome-msg': 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ AI വെറ്ററിനറി വിദഗ്ദ്ധനാണ്. ഇന്ന് എനിക്ക് എങ്ങനെ സഹായിക്കാനാകും?',
        'adv-typing': 'വിദഗ്ദ്ധൻ ടൈപ്പ് ചെയ്യുന്നു...',

        // Dashboard Steps
        'step-1-title': 'കന്നുകാലി രജിസ്ട്രേഷൻ',
        'step-1-desc': 'നിരീക്ഷണത്തിനായി നിങ്ങളുടെ കന്നുകാലി വിവരങ്ങൾ ചേർക്കുക.',
        'step-2-title': 'ആരോഗ്യ നിരീക്ഷണം',
        'step-2-desc': 'ആരോഗ്യം ഉറപ്പാക്കാൻ AI രോഗ സ്കാനർ ഉപയോഗിക്കുക.',
        'step-3-title': 'സേവനങ്ങൾ',
        'step-3-desc': 'ന്യായമായ വ്യാപാര വിലകളും സർക്കാർ ഗ്രാന്റുകളും നേടുക.',

        // Advisory Tabs
        'adv-tab-general': 'പൊതു ഉപദേശം',
        'adv-tab-nutrition': 'പോഷകാഹാര ഉപദേശം',

        'btn-camera': 'ക്യാമറ തുറക്കുക',
        'btn-capture': 'ഫോട്ടോ എടുക്കുക',
        'btn-retake': 'വീണ്ടും എടുക്കുക',
        'lbl-analyzing': 'AI ചിത്രം സ്കാൻ ചെയ്യുന്നു...',
        'p-disease-guide': 'രോഗനിർണ്ണയത്തിനായി ക്യാമറ ബാധിത പ്രദേശത്തേക്ക് (ചർമ്മം, കണ്ണുകൾ, വായ) പിടിക്കുക.',
        'skin-check-title': 'ചർമ്മാരോഗ്യ പരിശോധന',
        'q-skin-rash': 'നിങ്ങൾക്ക് എന്തെങ്കിലും തിണർപ്പുകളോ കുരുക്കളോ ചർമ്മത്തിലെ അസ്വസ്ഥതകളോ കാണുന്നുണ്ടോ?',
        'q-from-birth': 'ഈ അടയാളം ജനനം മുതലേ ഉണ്ടോ?',
        'q-skin-change': 'അടുത്തിടെ എന്തെങ്കിലും മാറ്റം (വലിപ്പം, നിറം, രക്തസ്രാവം) ഉണ്ടായിട്ടുണ്ടോ?',
        'msg-benign': 'ഇത് മിക്കവാറും ഒരു ജന്മനാ ഉള്ള അടയാളമാകാം. നിങ്ങൾക്ക് ഇപ്പോഴും ആശങ്കയുണ്ടെങ്കിൽ സ്കാൻ ചെയ്യാവുന്നതാണ്.',
        'msg-consult': 'കൃത്യമായ രോഗനിർണ്ണയത്തിനായി രോഗ ബാധയുണ്ടോ എന്ന് സ്കാൻ ചെയ്യാൻ ഞങ്ങൾ ശുപാർശ ചെയ്യുന്നു.',
        'btn-continue': 'തുടരുക',
        'btn-check-disease': 'രോഗം പരിശോധിക്കുക',
        'opt-yes': 'അതെ',
        'opt-no': 'അല്ല',
        'lbl-vet-dermatologist': 'AI-അധിഷ്ഠിത വെറ്ററിനറി ഡെർമറ്റോളജിസ്റ്റ്',
        'btn-upload-photo': 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
        'btn-live-camera': 'ലൈവ് ക്യാമറ',
        'btn-remove': 'നീക്കം ചെയ്യുക',
        'btn-run-analysis': 'AI വിശകലനം നടത്തുക',
        'lbl-low-appetite': 'വിശപ്പ് കുറവാണോ?',
        'ph-vitals-history': 'ഉദാ: ഇടത് കാലിലെ പഴയ അണുബാധ...',
        'msg-connecting-gemini': 'ജെമിനി വിഷനുമായി ബന്ധിപ്പിക്കുന്നു...',
        'lbl-ai-recommendation': 'AI ശുപാർശ',
        'lbl-detected': 'കണ്ടെത്തി',
        'lbl-confidence': 'വിശ്വാസം',
        'lbl-ready-scan': 'സ്കാൻ ചെയ്യാൻ തയ്യാറാണ്',
        'msg-upload-start': 'AI വിശകലനം ആരംഭിക്കുന്നതിന് ഒരു ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
        'msg-complete-precheck': 'സ്കാനിംഗ് പ്രവർത്തനക്ഷമമാക്കുന്നതിന് പ്രീ-ചെക്ക് പൂർത്തിയാക്കുക',
        'upload-text': 'ഫോട്ടോ തിരഞ്ഞെടുക്കുക',
        'upload-instruction': 'ഗാലറിയിൽ നിന്ന് അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക',
        'lbl-location': 'സ്ഥലം',
        'lbl-temperature': 'താപനില (°F)',
        'lbl-pregnancy': 'ഗർഭാവസ്ഥ',
        'lbl-fever': 'പനിയുണ്ടോ?',
        'lbl-high-fever': 'കടുത്ത പനി',
        'ph-age': 'ഉദാ: 4',
        'ph-weight': 'കിലോ',
        'ph-temp': '°F',
        'ph-milk': 'ലിറ്റർ',
        'lbl-milk-yield': 'പാൽ വിളവ് (ലിറ്റർ)',
        'lbl-nose': 'മൂക്കൊലിപ്പ് ഉണ്ടോ?',
        'lbl-breath': 'ശ്വസന ശബ്ദം?',
        'lbl-history': 'ചികിത്സാ ചരിത്രം',
        'lbl-diagnosis-basis': 'രോഗനിർണ്ണയത്തിന്റെ അടിസ്ഥാനം',
        'lbl-basis-desc': 'എന്തുകൊണ്ടാണ് ഈ അവസ്ഥ തിരഞ്ഞെടുത്തത്?',

        // System Demo Keys
        'sys-header': 'പ്ലാറ്റ്‌ഫോം ഡെമോ',
        'sys-s1-title': 'നവീകരണ തന്ത്രവും പ്രധാന പ്രവർത്തനരീതിയും',
        'sys-farmers': 'കർഷകർ',
        'sys-frontend': 'ഇന്റർഫേസ് ലെയർ',
        'sys-backend': 'തീരുമാനമെടുക്കുന്ന എഞ്ചിൻ',
        'sys-hybrid': 'ന്യൂറൽ കോർ',
        'sys-datalayer': 'നോളജ് ബേസ്',
        'sys-mobile-web': 'മൾട്ടി-മോഡൽ ഇന്ററാക്ഷൻ',
        'sys-react-vite': 'റെസ്‌പോൺസീവ് റിയാക്റ്റ് ഇക്കോസിസ്റ്റം',
        'sys-flask': 'പൈത്തൺ ഡിസ്ട്രിബ്യൂട്ടഡ് മൈക്രോസർവീസുകൾ',
        'sys-ml-gemini': 'ഹൈബ്രിഡ് വിഷൻ + ലാർജ് ലാംഗ്വേജ് മോഡൽ',
        'sys-mongo': 'ഇൻ-മെമ്മറി / മോംഗോഡിബി',
        'sys-s1-subtitle': 'അടിസ്ഥാന സൗകര്യ അവലോകനം',
        'sys-s1-desc-text': 'ഗ്രാമീണ മേഖലയിലെ ഡാറ്റയെ ആധുനിക എഐയുമായി ബന്ധിപ്പിക്കുന്ന ഉയർന്ന കോൺകറൻസി ആർക്കിറ്റെക്ചർത്തിലാണ് കാറ്റിൽ കെയർ പ്ലാറ്റ്‌ഫോം നിർമ്മിച്ചിരിക്കുന്നത്. ഞങ്ങൾ മൂന്ന് തലങ്ങളുള്ള ഡിസൈൻ തന്ത്രമാണ് ഉപയോഗിക്കുന്നത്: **എഡ്ജ് ഇന്ററാക്ഷൻ**, **സ്കേലബിൾ ബാക്കെൻഡ്**, **ഹൈബ്രിഡ് ഇന്റലിജൻസ് റീസണിംഗ്**. ഈ നേരിട്ടുള്ള വിന്യാസം ഞങ്ങളുടെ 4 പ്രധാന ലക്ഷ്യങ്ങൾ കാര്യക്ഷമതയോടും സുരക്ഷയോടും കൂടി നിറവേറ്റപ്പെടുന്നുവെന്ന് ഉറപ്പാക്കുന്നു.',
        'sys-s1-p1-title': 'ഗ്രാമീണ-പ്രഥമ രൂപകൽപ്പന',
        'sys-s1-p1-desc': 'ഓഫ്‌ലൈൻ-ഫസ്റ്റ് കഴിവുകളുള്ള കുറഞ്ഞ ബാൻഡുവിഡ്ത്ത് സോണുകൾക്കായി ഒപ്റ്റിമൈസ് ചെയ്തത്.',
        'sys-s1-p2-title': 'എഐ സ്കേലബിലിറ്റി',
        'sys-s1-p2-desc': 'ഉയർന്ന തീവ്രതയുള്ള വിഷൻ, പ്രെഡിക്റ്റീവ് ജോലികൾക്കായി ഇലാസ്റ്റിക് കമ്പ്യൂട്ട് ഉറവിടങ്ങൾ.',
        'sys-s1-p3-title': 'ഡാറ്റ സുരക്ഷ',
        'sys-s1-p3-desc': 'എല്ലാ കർഷക ഡാറ്റയ്ക്കും കന്നുകാലികളുടെ ചികിത്സാ ചരിത്രത്തിനും എൻഡ്-ടു-എൻഡ് എൻക്രിപ്ഷൻ.',
        'sys-farmers-desc': 'മൊബൈൽ, വെബ്, വോയിസ് എന്നിവയിലൂടെ ഓമ്‌നിചാനൽ പ്രവേശനം.',
        'sys-frontend-desc': 'ഫ്ലൂയിഡ് യുഐക്കായി ടെയിൽവിൻഡ് ഉള്ള വിറ്റ് എസ്പിഎ.',
        'sys-backend-desc': 'ഫ്ലാസ്ക് ഗേറ്റ്‌വേ ഉപയോഗിച്ചുള്ള റെസ്റ്റ്ഫുൾ മൈക്രോസർവീസുകൾ.',
        'sys-intelligence-desc': 'എഫിഷ്യന്റ് നെറ്റ് വിഷൻ + ജെമിനി സെമാന്റിക് റീസണിംഗ്.',
        'sys-datalayer-desc': 'പ്രൊഫൈലുകൾക്കും ടൈം-സീരീസ് ഡാറ്റയ്ക്കുമായി ഹൈബ്രിഡ് സ്റ്റോറേജ്.',

        'sys-obj-header': 'പ്ലാറ്റ്‌ഫോമിന്റെ പ്രധാന ലക്ഷ്യങ്ങൾ',
        'sys-obj-1-t': 'ആരോഗ്യ സുരക്ഷ',
        'sys-obj-1-d': 'കന്നുകാലി രോഗങ്ങൾ വേഗത്തിൽ കണ്ടെത്തുന്നതിനുള്ള AI അടിസ്ഥാനമാക്കിയുള്ള സ്കാനിംഗ്.',
        'sys-obj-2-t': 'ന്യായമായ വിപണി വ്യാപാരം',
        'sys-obj-2-d': 'ഓരോ കർഷകനും ന്യായമായ വില ഉറപ്പാക്കുന്ന അൽഗരിതമിക് മൂല്യനിർണ്ണയം.',
        'sys-obj-3-t': 'ഗ്രാമീണ പ്രവേശനക്ഷമത',
        'sys-obj-3-d': 'ഡിജിറ്റൽ വിടവ് കുറയ്ക്കുന്ന മൾട്ടി ലിംഗ്വൽ വോയിസ് പിന്തുണ.',
        'sys-obj-4-t': 'ഡാറ്റ അധിഷ്ഠിത ഉൾക്കാഴ്ചകൾ',
        'sys-obj-4-d': 'പാൽ ഉൽപാദനവും ആരോഗ്യ പ്രവചനങ്ങളും വിശകലനം ചെയ്യുന്നു.',
        'sys-obj-interaction': 'കർഷകർ **ഇന്റർഫേസ്** വഴി **ആരോഗ്യ സുരക്ഷ**യ്ക്കായി കന്നുകാലികളെ സ്കാൻ ചെയ്യുന്നു. ഞങ്ങളുടെ **ഇന്റലിജൻസ് കോർ** **ന്യായമായ വ്യാപാര**ത്തിനായി മൂല്യനിർണ്ണയം നടത്തുന്നു, കൂടാതെ **വോയിസ് എഐ** **പ്രവേശനക്ഷമത** ഉറപ്പാക്കുന്നു. എല്ലാ ഡാറ്റയും **പ്രെഡിക്റ്റീവ് ഉൾക്കാഴ്ചകൾക്കായി** **നോളജ് ബേസി**ലേക്ക് നൽകുന്നു.',

        'meth-title-1': 'രീതിശാസ്ത്രം: ആരോഗ്യ സുരക്ഷ',
        'meth-title-2': 'രീതിശാസ്ത്രം: ന്യായമായ വിപണി വ്യാപാരം',
        'meth-title-3': 'രീതിശാസ്ത്രം: ഗ്രാമീണ പ്രവേശനക്ഷമത',
        'meth-title-4': 'രീതിശാസ്ത്രം: ഡാറ്റ അധിഷ്ഠിത ഉൾക്കാഴ്ചകൾ',
        'sys-view-meth': 'രീതിശാസ്ത്രം കാണുക →',

        'sys-s2-title': 'എൻഡ്-ടു-എൻഡ് ഇൻഡിക് ബഹുഭാഷാ പലാറ്റ്‌ഫോം',
        'sys-s2-hybrid-title': 'ഇൻഡിക് വേവ്2വെക് + ജെമിനി ഹൈബ്രിഡ്',
        'sys-s2-desc': 'ഫൊണറ്റിക് ഡീകോഡിംഗിനായി **പ്രീ-ട്രെയിൻഡ് അക്കോസ്റ്റിക് മോഡലുകളും** ക്രോസ്-ലിംഗ്വൽ സെമാന്റിക് റീസണിംഗിനായി **ജെമിനി 1.5 പ്രോയും** സംയോജിപ്പിക്കുന്ന ഒരു ഹൈബ്രിഡ് ആർക്കിറ്റെക്ചർ.',
        'sys-s2-neural-stats': 'ന്യൂറൽ സ്ഥിതിവിവരക്കണക്കുകൾ',
        'sys-s2-model': 'മോഡൽ',
        'sys-s2-params': 'പാരാമീറ്ററുകൾ',
        'sys-s2-latency': 'ലാറ്റൻസി',
        'sys-s2-pipeline-title': 'ക്രോസ്-ലിംഗ്വൽ ഇൻഫറൻസ് പൈപ്പ്‌ലൈൻ',
        'sys-s2-raw-audio': 'റോ ഓഡിയോ',
        'sys-s2-feat-extract': 'ഫീച്ചർ എക്സ്ട്രാക്ഷൻ',
        'sys-s2-phoneme-map': 'ഇൻഡിക് വേവ്2വെക് + ജെമിനി',
        'sys-s2-action': 'പ്രവർത്തനം',

        'sys-s3-title': 'കണ്ടെക്സ്റ്റ്-അവെയർ ജനറേറ്റീവ് റീസണിംഗ്',
        'sys-s3-role-prompt': 'റോൾ-ബേസ്ഡ് പ്രോംപ്റ്റ് എഞ്ചിനീയറിംഗ്',
        'sys-s3-desc': 'ചിട്ടപ്പെടുത്തിയ ചരിത്രവും കർശനമായ പെരുമാറ്റ നിർദ്ദേശങ്ങളും നൽകിക്കൊണ്ട് ഒരു സാധാരണ എൽഎൽഎമ്മിനെ പ്രത്യേക വെറ്ററിനറി അല്ലെങ്കിൽ ന്യൂട്രീഷ്യൻ വിദഗ്ധനായി മാറ്റുന്നു.',
        'sys-s3-cog-func': 'കോഗ്നിറ്റീവ് ഫംഗ്ഷനുകൾ',
        'sys-s3-persona-switch': 'ഡൈനാമിക് പേഴ്സണ സ്വിച്ചിംഗ്',
        'sys-s3-concise': 'ചുരുങ്ങിയ ഔട്ട്‌പുട്ട് (വോയിസ്)',
        'sys-s3-pipe-title': 'സംഭാഷണ പൈപ്പ്‌ലൈൻ',
        'sys-s3-user-query': 'ഉപയോക്താവിന്റെ ചോദ്യം',
        'sys-s3-ctx-engine': 'കണ്ടെക്സ്റ്റ് എഞ്ചിൻ',
        'sys-s3-gemini-llm': 'ജെമിനി എൽഎൽഎം',
        'sys-s3-expert-advice': 'വിദഗ്ദ്ധോപദേശം',

        'sys-s4-title': 'പ്രെഡിക്റ്റീവ് ഫാം അനലിറ്റിക്സ് (TFT)',
        'sys-s4-tft-title': 'ടെമ്പോറൽ ഫ്യൂഷൻ ട്രാൻസ്ഫോർമർ',
        'sys-s4-desc': '**മൾട്ടി-ഹൊറൈസൺ ക്വാണ്ടൈൽ റിക്കറന്റ് ന്യൂറൽ നെറ്റ്‌വർക്ക്** പിന്തുണയ്ക്കുന്നത്. പാൽ ഉൽപാദനം പ്രവചിക്കാൻ **TFT**-യും തത്സമയ അപാകതകൾ കണ്ടെത്താൻ **ഐസൊലേഷൻ ഫോറസ്റ്റ്**-ഉം ഉപയോഗിക്കുന്നു.',
        'sys-s4-model-specs': 'മോഡൽ സ്പെക്സ്',
        'sys-s4-forecasting': 'ഫോർകാസ്റ്റിംഗ്',
        'sys-s4-horizon': 'ഹൊറൈസൺ',
        'sys-s4-error-rate': 'എറർ റേറ്റ്',
        'sys-s4-pipe-title': 'അനലിറ്റിക്സ് പൈപ്പ്‌ലൈൻ',
        'sys-s4-hist-data': 'ചരിത്രപരമായ ഡാറ്റ',
        'sys-s4-sliding-win': 'സ്ലൈഡിംഗ് വിൻഡോ',
        'sys-s4-ensemble': 'എൻസെംബിൾ കോർ',
        'sys-s4-smart-insight': 'സ്മാർട്ട് ഉൾക്കാഴ്ചകൾ',

        // Breeds & Locations
        'opt-gir': 'ഗിർ',
        'opt-sahiwal': 'സാഹിവാൾ',
        'opt-redsindhi': 'റെഡ് സിന്ധി',
        'opt-tharparkar': 'താർപാർക്കർ',
        'opt-jersey': 'ജേഴ്സി',
        'opt-holstein': 'ഹോൾസ്റ്റീൻ ഫ്രീസിയൻ',
        'opt-hfcross': 'എച്ച്എഫ് ക്രോസ്',
        'opt-murrah': 'മുറ',
        'opt-unknown': 'അജ്ഞാത / മറ്റ്',

        // States
        'st-karnataka': 'കർണാടക',
        'st-goa': 'ഗോവ',
        'st-andhrapradesh': 'ആന്ധ്ര പ്രദേശ്',
        'st-telangana': 'തെലങ്കാന',
        'st-tamilnadu': 'തമിഴ്നാട്',
        'st-kerala': 'കേരളം',
        'st-maharashtra': 'മഹாராഷ്ട്ര',
        'st-gujarat': 'ഗുജറാത്ത്',
        'st-madhyapradesh': 'മധ്യ പ്രദേശ്',
        'st-uttarpradesh': 'ഉത്തർ പ്രദേശ്',
        'st-arunachalpradesh': 'അരുണാചൽ പ്രദേശ്',
        'st-assam': 'ആസ്സാം',
        'st-bihar': 'ബീഹാർ',
        'st-chhattisgarh': 'ഛത്തീസ്ഗഢ്',
        'st-haryana': 'ഹരിയാന',
        'st-himachalpradesh': 'ഹിമാചൽ പ്രദേശ്',
        'st-jharkhand': 'ജാർഖണ്ഡ്',
        'st-manipur': 'മണിപ്പൂർ',
        'st-meghalaya': 'മേഘാലയ',
        'st-mizoram': 'മിസോറം',
        'st-nagaland': 'നാഗാലാൻഡ്',
        'st-odisha': 'ഒഡീഷ',
        'st-punjab': 'പഞ്ചാബ്',
        'st-rajasthan': 'രാജസ്ഥാൻ',
        'st-sikkim': 'സിക്കിം',
        'st-tripura': 'ത്രിപുര',
        'st-uttarakhand': 'ഉത്തരാഖണ്ഡ്',
        'st-westbengal': 'പശ്ചിമ ബംഗാൾ'
    }
};

export const LanguageProvider = ({ children }) => {
    const [currentLang, setCurrentLang] = useState('en-US');

    const t = (key) => {
        return translations[currentLang][key] || translations['en-US'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ currentLang, setCurrentLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);

