import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
    'en-US': {
        'title-dashboard': 'Farm Dashboard',
        'title-trade': 'Smart Trade',
        'title-disease': 'Disease Scanner',
        'title-advisory': 'Expert Advisory',
        'logo': 'Cattle Care',
        'nav-dashboard': 'Dashboard',
        'nav-trade': 'Smart Trade',
        'nav-disease': 'Disease Scanner',
        'nav-advisory': 'Advisory',
        'nav-cows': 'My Cattle',
        'nav-services': 'Services',
        'nav-alerts': 'Alerts',
        'nav-settings': 'Settings',
        'alerts-title': 'Alerts & Notifications',
        'alerts-subtitle': 'Critical updates about your herd.',
        'alerts-empty': 'No new alerts.',
        'settings-title': 'Settings',
        'settings-subtitle': 'Manage your account and app preferences.',
        'stg-account': 'Farmer Account',
        'stg-signout': 'Sign Out',
        'stg-pref': 'Preferences',
        'stg-lang': 'Language',
        'stg-theme': 'Theme',
        'stg-notif': 'Notifications',
        'stg-push': 'Push Notifications',
        'stg-email': 'Email Alerts',
        'stg-security': 'Security',
        'stg-change-pw': 'Change Password',
        'stg-save': 'Save Changes',
        'grants-title': 'Government Grants',
        'grants-subtitle': 'Find available grants and subsidies for your farm.',
        'grants-new': 'Post New Grant (Admin)',
        'grants-schemes': 'Available Schemes',
        'grants-apply': 'Apply Now',
        'predict-title': 'Health Prediction AI',
        'predict-subtitle': 'Analyze vital signs to detect potential health issues.',
        'pred-enter-vitals': 'Enter Vitals',
        'pred-temp': 'Temperature (°C)',
        'pred-appetite': 'Appetite (1-10)',
        'pred-mobility': 'Mobility (1-10)',
        'pred-run': 'Run Prediction',
        'pred-analyzing': 'Analyzing...',
        'pred-result-placeholder': 'Enter vitals to see analysis result.',
        'pred-note': 'Note: This is an AI estimation. Please consult a vet for final diagnosis.',
        'cows-title': 'My Cattle',
        'cows-subtitle': 'Manage your herd registry and health status.',
        'btn-add-cow': 'Add New Cow',
        'hdr-herd-list': 'Herd List',
        'tbl-tag': 'Tag ID',
        'tbl-age': 'Age',
        'tbl-health': 'Health',
        'tbl-owner': 'Owner',
        'ph-tag': 'Tag ID',
        'ph-age': 'Age',
        'ph-owner': 'Owner',
        'opt-select-status': 'Select Status',
        'opt-healthy': 'Healthy',
        'opt-sick': 'Sick',
        'opt-pregnant': 'Pregnant',
        'srv-title': 'Our Services',
        'srv-subtitle': 'Comprehensive tools for modern cattle management.',
        'srv-health-hub': 'Health Hub',
        'srv-health-desc': 'AI prediction & disease scanning',
        'srv-trade': 'Smart Trade',
        'srv-trade-desc': 'Fair price estimation & market trends',
        'srv-advisory': 'Advisory',
        'srv-advisory-desc': 'Expert guidance & best practices',
        'srv-grants': 'Govt. Grants',
        'srv-grants-desc': 'Subsidy & financial aid information',
        'dash-active-trades': 'Active Trades',
        'dash-govt-grants': 'Govt Grants',
        'dash-health-ai': 'Health AI',
        'lbl-breed': 'Cattle Breed',
        'lbl-weight': 'Weight (kg)',
        'lbl-age': 'Age (Months)',
        'lbl-milk': 'Milk Yield (L/Day)',
        'lbl-preg': 'Pregnancy (Months)',
        'btn-calc': 'Calculate Price',
        'btn-scan': 'Scan Image',
        'total-cattle': 'Total Cattle',
        'health-alerts': 'Health Alerts',
        'market-rate': 'Avg. Local Rate',
        'weather': 'Weather',
        'recent-activity': 'Recent Activity',
        'opt-gir': 'Gir (Desi)',
        'opt-sahiwal': 'Sahiwal',
        'opt-redsindhi': 'Red Sindhi',
        'opt-tharparkar': 'Tharparkar',
        'opt-jersey': 'Jersey',
        'opt-holstein': 'Holstein Friesian',

        // Dashboard Keys
        'subtitle-dashboard': 'Smart Farm Infrastructure & Management System',
        'status-db': 'DB Connected',
        'status-live': 'LIVE',
        'unit-kg': '/kg',
        'chart-milk': 'Milk Yield (Liters)',
        'disclaimer-gps': '*Based on your GPS location',
        'dash-infra': 'Farm Infrastructure',
        'dash-acres': 'Acres',
        'dash-sheds': 'Sheds',
        'dash-cctv': 'CCTV Live',
        'dash-feed': 'Feed Stock',
        'dash-water': 'Water Tank',
        'dash-trends': 'Production Trends',
        'dash-sick': 'Sick History (Records)',
        'dash-no-sick': 'No sick records found.',
        'dash-vets': 'Nearby Vet Hospitals',
        'dash-nav': 'Navigate',
        'dash-view-map': 'View All on Map',
        'trade-subtitle': 'AI-Powered Valuation & Certification',
        'grp-desi': 'Indian Indigenous (Desi)',
        'grp-exotic': 'Exotic / Cross',
        'opt-murrah': 'Murrah Buffalo',
        'msg-analyzing': 'AI Analyzing...',
        'hint-qr': 'Use Google Lens • Save Details Instantly',
        'lbl-forecast': '6-Month Forecast',
        'adv-critical': 'Critical Attention Needed. Contact Vet Immediately.',

        // Report / Certificate Keys
        'cert-title': 'Valuation Report',
        'cert-subtitle': 'Certified by Cattle Care AI',
        'cert-value': 'Estimated Fair Value',
        'cert-confidence': 'TVL Confidence',
        'cert-proof': 'Price Breakdown (Proof)',
        'cert-base': 'Base Weight Value',
        'cert-milk': 'Milk Yield Bonus',
        'cert-preg': 'Pregnancy Bonus',
        'cert-age': 'Age Depreciation',
        'cert-analysis': 'AI Expert Analysis',
        'cert-footer': 'Generated by Gemini AI • Verifiable Trace',
        'btn-download': 'Download Official PDF',
        'btn-download': 'Download Official PDF',
        'qr-scan': 'Scan to Save on Phone',

        // Advisory Chat Keys
        'adv-chat-placeholder': 'Type your question here...',
        'adv-chat-send': 'Send',
        'adv-welcome-msg': 'Namaste! I am your AI Veterinary Expert. How can I help your cattle today?',
        'adv-welcome-msg': 'Namaste! I am your AI Veterinary Expert. How can I help your cattle today?',
        'adv-typing': 'Vet is typing...',

        // Disease Scanner
        'btn-camera': 'Open Camera',
        'btn-capture': 'Capture Photo',
        'btn-retake': 'Retake',
        'lbl-analyzing': 'AI is scanning the image...',
        'p-disease-guide': 'Point camera at the affected area (skin, eyes, mouth) for instant diagnosis.',

        // Disease Scanner V2 Keys
        'lbl-temperature': 'Temperature (°F)',
        'lbl-pregnancy': 'Pregnancy Status',
        'lbl-water': 'Water Intake (Liters)',
        'lbl-milk-yield': 'Milk Yield (Liters)',
        'lbl-nose': 'Running Nose?',
        'lbl-breath': 'Breathing Sound?',
        'lbl-history': 'Medical History',
        'lbl-diagnosis-basis': 'Basis of Diagnosis',
        'lbl-basis-desc': 'Why was this status chosen?',
        'opt-yes': 'Yes',
        'opt-no': 'No',
        'opt-abnormal': 'Abnormal / Heavy'
    },
    'hi-IN': {
        'title-dashboard': 'पशु फार्म डैशबोर्ड',
        'title-trade': 'व्यापार (स्मार्ट ट्रेड)',
        'title-disease': 'रोग जाँच (स्कैन)',
        'title-advisory': 'विशेषज्ञ सलाह',
        'logo': 'कैटल केयर',
        'nav-dashboard': 'डैशबोर्ड',
        'nav-trade': 'व्यापार',
        'nav-disease': 'रोग जाँच',
        'nav-advisory': 'सलाह',
        'nav-cows': 'पशु धन',
        'nav-services': 'सेवाएं',
        'nav-alerts': 'अलर्ट',
        'nav-settings': 'सेटिंग्स',
        'alerts-title': 'अलर्ट और सूचनाएं',
        'alerts-subtitle': 'आपके झुंड के बारे में महत्वपूर्ण अपडेट।',
        'alerts-empty': 'कोई नई सूचना नहीं।',
        'settings-title': 'सेटिंग्स',
        'settings-subtitle': 'अपने खाते और ऐप की प्राथमिकताओं को प्रबंधित करें।',
        'stg-account': 'किसान खाता',
        'stg-signout': 'साइन आउट',
        'stg-pref': 'प्राथमिकताएं',
        'stg-lang': 'भाषा',
        'stg-theme': 'थीम',
        'stg-notif': 'सूचनाएं',
        'stg-push': 'पुश नोटिफिकेशन',
        'stg-email': 'ईमेल अलर्ट',
        'stg-security': 'सुरक्षा',
        'stg-change-pw': 'पासवर्ड बदलें',
        'stg-save': 'परिवर्तन सहेजें',
        'grants-title': 'सरकारी अनुदान',
        'grants-subtitle': 'अपने खेत के लिए उपलब्ध अनुदान और सब्सिडी खोजें।',
        'grants-new': 'नया अनुदान (व्यवस्थापक)',
        'grants-schemes': 'उपलब्ध योजनाएं',
        'grants-apply': 'आवेदन करें',
        'predict-title': 'स्वास्थ्य भविष्यवाणी एआई',
        'predict-subtitle': 'संभावित स्वास्थ्य समस्याओं का पता लगाने के लिए महत्वपूर्ण संकेतों का विश्लेषण करें।',
        'pred-enter-vitals': 'वाइटल्स दर्ज करें',
        'pred-temp': 'तापमान (°C)',
        'pred-appetite': 'भूख (1-10)',
        'pred-mobility': 'गतिशीलता (1-10)',
        'pred-run': 'भविष्यवाणी करें',
        'pred-analyzing': 'विश्लेषण कर रहा है...',
        'pred-result-placeholder': 'परिणाम देखने के लिए वाइटल्स दर्ज करें।',
        'pred-note': 'नोट: यह एआई अनुमान है। कृपया अंतिम निदान के लिए पशु चिकित्सक से परामर्श करें।',
        'cows-title': 'मेरा पशुधन',
        'cows-subtitle': 'अपने झुंड रजिस्ट्री और स्वास्थ्य स्थिति का प्रबंधन करें।',
        'btn-add-cow': 'नई गाय जोड़ें',
        'hdr-herd-list': 'झुंड सूची',
        'tbl-tag': 'टैग आईडी',
        'tbl-age': 'उम्र',
        'tbl-health': 'स्वास्थ्य',
        'tbl-owner': 'मालिक',
        'ph-tag': 'टैग आईडी',
        'ph-age': 'उम्र',
        'ph-owner': 'मालिक',
        'opt-select-status': 'स्थिति चुनें',
        'opt-healthy': 'स्वस्थ',
        'opt-sick': 'बीमार',
        'opt-pregnant': 'गर्भवती',
        'srv-title': 'हमारी सेवाएं',
        'srv-subtitle': 'आधुनिक पशु प्रबंधन के लिए व्यापक उपकरण।',
        'srv-health-hub': 'स्वास्थ्य केंद्र',
        'srv-health-desc': 'एआई भविष्यवाणी और रोग स्कैनिंग',
        'srv-trade': 'स्मार्ट ट्रेड',
        'srv-trade-desc': 'उचित मूल्य अनुमान और बाजार के रुझान',
        'srv-advisory': 'सलाह',
        'srv-advisory-desc': 'विशेषज्ञ मार्गदर्शन और सर्वोत्तम प्रथाएं',
        'srv-grants': 'सरकारी अनुदान',
        'srv-grants-desc': 'सब्सिडी और वित्तीय सहायता जानकारी',
        'dash-active-trades': 'सक्रिय व्यापार',
        'dash-govt-grants': 'सरकारी अनुदान',
        'dash-health-ai': 'हेल्थ एआई',
        'lbl-breed': 'गाय की नस्ल',
        'lbl-weight': 'वजन (किग्रा)',
        'lbl-age': 'उम्र (महीने)',
        'lbl-milk': 'दूध (लीटर/दिन)',
        'lbl-preg': 'गर्भावस्था (महीने)',
        'btn-calc': 'कीमत बतायें',
        'btn-scan': 'स्कैन करें',
        'total-cattle': 'कुल पशु',
        'health-alerts': 'स्वास्थ्य अलर्ट',
        'market-rate': 'औसत स्थानीय दर',
        'weather': 'मौसम',
        'recent-activity': 'हाल की गतिविधि',
        'opt-gir': 'गिर (देसी)',
        'opt-sahiwal': 'साहीवाल',
        'opt-redsindhi': 'लाल सिंधी',
        'opt-tharparkar': 'थारपारकर',
        'opt-jersey': 'जर्सी',
        'opt-holstein': 'होलस्टीन',

        'dash-infra': 'फार्म इंफ्रास्ट्रक्चर',
        'subtitle-dashboard': 'स्मार्ट फार्म प्रबंधन प्रणाली',
        'status-db': 'DB कनेक्टेड',
        'status-live': 'लाईंव',
        'unit-kg': '/किग्रा',
        'chart-milk': 'दुग्ध उत्पादन (लीटर)',
        'disclaimer-gps': '*आपके जीपीएस स्थान पर आधारित',
        'dash-acres': 'एकड़',
        'dash-sheds': 'शेड',
        'dash-cctv': 'सीसीटीवी (लाइव)',
        'dash-feed': 'चारा भंडार',
        'dash-water': 'पानी की टंकी',
        'dash-trends': 'उत्पादन रुझान',
        'dash-sick': 'बीमारी का इतिहास',
        'dash-no-sick': 'कोई रिकॉर्ड नहीं मिला।',
        'dash-vets': 'निकटतम पशु चिकित्सक',
        'dash-nav': 'रास्ता देखें',
        'dash-view-map': 'मैप पर देखें',
        'trade-subtitle': 'AI संचालित मूल्यांकन और प्रमाणन',
        'grp-desi': 'भारतीय स्वदेशी (देसी)',
        'grp-exotic': 'विदेशी / संकर',
        'opt-murrah': 'मुर्रा भैंस',
        'msg-analyzing': 'AI विश्लेषण कर रहा है...',
        'hint-qr': 'Google Lens का उपयोग करें • विवरण तुरंत सहेजें',
        'lbl-forecast': '6-महीने का पूर्वानुमान',
        'adv-critical': 'गंभीर ध्यान देने की आवश्यकता है। तुरंत पशु चिकित्सक से संपर्क करें।',

        'cert-title': 'मूल्यांकन रिपोर्ट',
        'cert-subtitle': 'कैटल केयर AI द्वारा प्रमाणित',
        'cert-value': 'अनुमानित उचित मूल्य',
        'cert-confidence': 'सटीकता',
        'cert-proof': 'मूल्य का विवरण (प्रमाण)',
        'cert-base': 'वजन का मूल्य',
        'cert-milk': 'दूध का बोनस',
        'cert-preg': 'गर्भावस्था बोनस',
        'cert-age': 'उम्र की कटौती',
        'cert-analysis': 'AI विशेषज्ञ विश्लेषण',
        'cert-footer': 'जेमिनी AI द्वारा निर्मित • सत्यापित रिपोर्ट',
        'btn-download': 'PDF डाउनलोड करें',
        'qr-scan': 'फोन पर सेव करने के लिए स्कैन करें',

        'adv-chat-placeholder': 'अपना प्रश्न यहाँ लिखें...',
        'adv-chat-send': 'भेजें',
        'adv-welcome-msg': 'नमस्ते! मैं आपका एआई पशु चिकित्सक विशेषज्ञ हूँ। आज मैं आपकी कैसे सहायता कर सकता हूँ?',
        'adv-welcome-msg': 'नमस्ते! मैं आपका एआई पशु चिकित्सक विशेषज्ञ हूँ। आज मैं आपकी कैसे सहायता कर सकता हूँ?',
        'adv-typing': 'विशेषज्ञ टाइप कर रहे हैं...',

        'btn-camera': 'कैमरा खोलें',
        'btn-capture': 'फोटो लें',
        'btn-retake': 'दूबारा लें',
        'lbl-analyzing': 'AI छवि को स्कैन कर रहा है...',
        'p-disease-guide': 'त्वरित निदान के लिए कैमरे को प्रभावित क्षेत्र (त्वचा, आंखें, मुंह) की ओर इंगित करें।'
    },
    'te-IN': {
        'title-dashboard': 'పశువుల డాష్‌బోర్డ్',
        'title-trade': 'స్మార్ట్ ట్రేడ్ (ధర)',
        'title-disease': 'వ్యాధి స్కానర్',
        'title-advisory': 'నిపుణుల సలహా',
        'logo': 'కేటిల్ కేర్',
        'nav-dashboard': 'డ్యాష్‌బోర్డ్',
        'nav-trade': 'స్మార్ట్ ట్రేడ్',
        'nav-disease': 'వ్యాధి స్కానర్',
        'nav-advisory': 'సలహా',
        'nav-cows': 'నా పశువులు',
        'nav-services': 'సేవలు',
        'nav-alerts': 'హెచ్చరికలు',
        'nav-settings': 'అమరికలు',
        'alerts-title': 'హెచ్చరికలు & నోటిఫికేషన్‌లు',
        'alerts-subtitle': 'మీ మంద గురించి ముఖ్యమైన నవీకరణలు.',
        'alerts-empty': 'కొత్త హెచ్చరికలు లేవు.',
        'settings-title': 'అమరికలు',
        'settings-subtitle': 'మీ ఖాతా మరియు యాప్ ప్రాధాన్యతలను నిర్వహించండి.',
        'stg-account': 'రైతు ఖాతా',
        'stg-signout': 'సైన్ అవుట్',
        'stg-pref': 'ప్రాధాన్యతలు',
        'stg-lang': 'భాష',
        'stg-theme': 'థీమ్',
        'stg-notif': 'నోటిఫికేషన్‌లు',
        'stg-push': 'పుష్ నోటిఫికేషన్‌లు',
        'stg-email': 'ఇమెయిల్ హెచ్చరికలు',
        'stg-security': 'భద్రత',
        'stg-change-pw': 'పాస్‌వర్డ్ మార్చండి',
        'stg-save': 'మార్పులను భద్రపరచండి',
        'grants-title': 'ప్రభుత్వ గ్రాంట్లు',
        'grants-subtitle': 'మీ పొలం కోసం అందుబాటులో ఉన్న గ్రాంట్లు మరియు సబ్సిడీలను కనుగొనండి.',
        'grants-new': 'కొత్త గ్రాంట్ (అడ్మిన్)',
        'grants-schemes': 'అందుబాటులో ఉన్న పథకాలు',
        'grants-apply': 'దరఖాస్తు చేయండి',
        'predict-title': 'ఆరోగ్య అంచనా AI',
        'predict-subtitle': 'ఆరోగ్య సమస్యలను గుర్తించడానికి కీలక సంకేతాలను విశ్లేషించండి.',
        'pred-enter-vitals': 'వివరాలను నమోదు చేయండి',
        'pred-temp': 'ఉష్ణోగ్రత (°C)',
        'pred-appetite': 'ఆకలి (1-10)',
        'pred-mobility': 'చలనం (1-10)',
        'pred-run': 'అంచనా వేయండి',
        'pred-analyzing': 'విశ్లేషిస్తోంది...',
        'pred-result-placeholder': 'ఫలితాన్ని చూడటానికి వివరాలను నమోదు చేయండి.',
        'pred-note': 'గమనిక: ఇది AI అంచనా. దయచేసి నిర్ధారణ కోసం వెట్‌ను సంప్రదించండి.',
        'cows-title': 'నా పశువులు',
        'cows-subtitle': 'మీ పశువుల జాబితా మరియు ఆరోగ్యాన్ని నిర్వహించండి.',
        'btn-add-cow': 'కొత్త ఆవును జోడించండి',
        'hdr-herd-list': 'పశువుల జాబితా',
        'tbl-tag': 'ట్యాగ్ ఐడి',
        'tbl-age': 'వయస్సు',
        'tbl-health': 'ఆరోగ్యం',
        'tbl-owner': 'యజమాని',
        'ph-tag': 'ట్యాగ్ ఐడి',
        'ph-age': 'వయస్సు',
        'ph-owner': 'యజమాని',
        'opt-select-status': 'స్థితిని ఎంచుకోండి',
        'opt-healthy': 'ఆరోగ్యంగా',
        'opt-sick': 'అనారోగ్యం',
        'opt-pregnant': 'గర్భవతి',
        'srv-title': 'మా సేవలు',
        'srv-subtitle': 'ఆధునిక పశువుల నిర్వహణ కోసం సమగ్ర సాధనాలు.',
        'srv-health-hub': 'హెల్త్ హబ్',
        'srv-health-desc': 'AI అంచనా & వ్యాధి స్కానింగ్',
        'srv-trade': 'స్మార్ట్ ట్రేడ్',
        'srv-trade-desc': 'న్యాయమైన ధర అంచనా & మార్కెట్ పోకడలు',
        'srv-advisory': 'సలహా',
        'srv-advisory-desc': 'నిపుణుల మార్గదర్శకత్వం & ఉత్తమ పద్ధతులు',
        'srv-grants': 'ప్రభుత్వ గ్రాంట్లు',
        'srv-grants-desc': 'సబ్సిడీ & ఆర్థిక సహాయ సమాచారం',
        'dash-active-trades': 'యాక్టివ్ ట్రేడ్స్',
        'dash-govt-grants': 'ప్రభుత్వ గ్రాంట్లు',
        'dash-health-ai': 'హెల్త్ ఏఐ',
        'lbl-breed': 'జాతి',
        'lbl-weight': 'బరువు (kg)',
        'lbl-age': 'వయస్సు (నెలలు)',
        'lbl-milk': 'పాలు (లీటర్లు)',
        'lbl-preg': 'గర్భం (నెలలు)',
        'btn-calc': 'ధరను లెక్కించు',
        'btn-scan': 'స్కాన్ చేయండి',
        'total-cattle': 'మొత్తం పశువులు',
        'health-alerts': 'ఆరోగ్య హెచ్చరికలు',
        'market-rate': 'సగటు స్థానిక ధర',
        'weather': 'వాతావరణం',
        'recent-activity': 'ఇటీవలి కార్యకలాపాలు',
        'opt-gir': 'గిర్ (దేశీయ)',
        'opt-sahiwal': 'సాహివాల్',
        'opt-redsindhi': 'రెడ్ సింధీ',
        'opt-tharparkar': 'థార్‌పార్కర్',
        'opt-jersey': 'జెర్సీ',
        'opt-holstein': 'హోల్స్టీన్',

        'dash-infra': 'ఫార్మ్ మౌలిక సదుపాయాలు',
        'subtitle-dashboard': 'స్మార్ట్ ఫార్మ్ నిర్వహణ వ్యవస్థ',
        'status-db': 'DB కనెక్ట్ చేయబడింది',
        'status-live': 'లైవ్',
        'unit-kg': '/kg',
        'chart-milk': 'పాల దిగుబడి (లీటర్లు)',
        'disclaimer-gps': '*మీ GPS స్థానం ఆధారంగా',
        'dash-acres': 'ఎకరాలు',
        'dash-sheds': 'షెడ్లు',
        'dash-cctv': 'CCTV లైవ్',
        'dash-feed': 'మేత నిల్వ',
        'dash-water': 'నీటి ట్యాంక్',
        'dash-trends': 'ఉత్పత్తి పోకడలు',
        'dash-sick': 'అనారోగ్య చరిత్ర',
        'dash-no-sick': 'రికార్డులు కనుగొనబడలేదు.',
        'dash-vets': 'దగ్గరి పశువైద్యశాలలు',
        'dash-nav': 'దారి చూపించు',
        'dash-view-map': 'మ్యాప్‌లో చూడండి',
        'trade-subtitle': 'AI ఆధారిత వాల్యుయేషన్ & సర్టిఫికేషన్',
        'grp-desi': 'భారతీయ దేశీయ (దేసీ)',
        'grp-exotic': 'విదేశీ / క్రాస్',
        'opt-murrah': 'ముర్రా గేదె',
        'msg-analyzing': 'AI విశ్లేషస్తోంది...',
        'hint-qr': 'Google Lens ఉపయోగించండి • వివరాలను సేవ్ చేయండి',
        'lbl-forecast': '6-నెలల అంచనా',
        'adv-critical': 'అత్యవసర శ్రద్ధ అవసరం. వెంటనే వెట్‌ను సంప్రదించండి.',

        'cert-title': 'వాల్యుయేషన్ రిపోర్ట్',
        'cert-subtitle': 'కాటిల్ కేర్ AI ద్వారా ధృవీకరించబడింది',
        'cert-value': 'అంచనా వేయబడిన ధర',
        'cert-confidence': 'ఖచ్చితత్వం',
        'cert-proof': 'ధర వివరాలు (రుజువు)',
        'cert-base': 'బరువు విలువ',
        'cert-milk': 'పాల దిగుబడి బోనస్',
        'cert-preg': 'గర్భధారణ బోనస్',
        'cert-age': 'వయస్సు తగ్గింపు',
        'cert-analysis': 'AI నిపుణుల విశ్లేషణ',
        'cert-footer': 'జెమిని AI ద్వారా రూపొందించబడింది • అధికారిక నివేదిక',
        'btn-download': 'PDF డౌన్‌లోడ్ చేయండి',
        'qr-scan': 'ఫోన్‌లో సేవ్ చేయడానికి స్కాన్ చేయండి',

        'adv-chat-placeholder': 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
        'adv-chat-send': 'పంపండి',
        'adv-welcome-msg': 'నమస్తే! నేను మీ AI పశువైద్య నిపుణుడిని. ఈ రోజు నేను మీ పశువులకు ఎలా సహాయం చేయగలను?',
        'adv-welcome-msg': 'నమస్తే! నేను మీ AI పశువైద్య నిపుణుడిని. ఈ రోజు నేను మీ పశువులకు ఎలా సహాయం చేయగలను?',
        'adv-typing': 'వెట్ టైప్ చేస్తున్నారు...',

        'btn-camera': 'కెమెరా తెరవండి',
        'btn-capture': 'ఫోటో తీయండి',
        'btn-retake': 'మళ్ళీ తీయండి',
        'lbl-analyzing': 'AI చిత్రాన్ని స్కాన్ చేస్తోంది...',
        'p-disease-guide': 'తక్షణ నిర్ధారణ కోసం కెమెరాను ప్రభావిత ప్రాంతం (చర్మం, కళ్లు, నోరు) వైపు ఉంచండి.'
    },
    'ta-IN': {
        'title-dashboard': 'பண்ணை டாஷ்போர்டு',
        'title-trade': 'ஸ்மார்ட் வர்த்தகம்',
        'title-disease': 'நோய் ஸ்கேனர்',
        'title-advisory': 'நிபுணர் ஆலோசனை',
        'logo': 'கால்நடை பராமரிப்பு',
        'nav-dashboard': 'டாஷ்போர்டு',
        'nav-trade': 'வர்த்தகம்',
        'nav-disease': 'நோய் ஸ்கேனர்',
        'nav-advisory': 'ஆலோசனை',
        'nav-cows': 'என் மாடுகள்',
        'nav-services': 'சேவைகள்',
        'nav-alerts': 'எச்சரிக்கைகள்',
        'nav-settings': 'அமைப்புகள்',
        'alerts-title': 'எச்சரிக்கைகள் & அறிவிப்புகள்',
        'alerts-subtitle': 'உங்கள் மந்தை பற்றிய முக்கிய அறிவிப்புகள்.',
        'alerts-empty': 'புதிய எச்சரிக்கைகள் இல்லை.',
        'settings-title': 'அமைப்புகள்',
        'settings-subtitle': 'கணக்கு மற்றும் பயன்பாட்டு விருப்பங்களை நிர்வகிக்கவும்.',
        'stg-account': 'விவசாயி கணக்கு',
        'stg-signout': 'வெளியேறு',
        'stg-pref': 'விருப்பங்கள்',
        'stg-lang': 'மொழி',
        'stg-theme': 'தீம்',
        'stg-notif': 'அறிவிப்புகள்',
        'stg-push': 'புஷ் அறிவிப்புகள்',
        'stg-email': 'மின்னஞ்சல் எச்சரிக்கைகள்',
        'stg-security': 'பாதுகாப்பு',
        'stg-change-pw': 'கடவுச்சொல்லை மாற்றவும்',
        'stg-save': 'சேமி',
        'grants-title': 'அரசு மானியங்கள்',
        'grants-subtitle': 'உங்கள் பண்ணைக்கான மானியங்களைக் கண்டறியவும்.',
        'grants-new': 'புதிய மானியம் (நிர்வாகி)',
        'grants-schemes': 'கிடைக்கும் திட்டங்கள்',
        'grants-apply': 'விண்ணப்பிக்கவும்',
        'predict-title': 'சுகாதார முன்னறிவிப்பு AI',
        'predict-subtitle': 'சுகாதார சிக்கல்களைக் கண்டறிய முக்கிய அறிகுறிகளை பகுப்பாய்வு செய்யவும்.',
        'pred-enter-vitals': 'விவரங்களை உள்ளிடவும்',
        'pred-temp': 'வெப்பநிலை (°C)',
        'pred-appetite': 'பசி (1-10)',
        'pred-mobility': 'இயக்கம் (1-10)',
        'pred-run': 'கணிக்கவும்',
        'pred-analyzing': 'பகுப்பாய்வு செய்கிறது...',
        'pred-result-placeholder': 'முடிவைக் காண விவரங்களை உள்ளிடவும்.',
        'pred-note': 'குறிப்பு: இது AI மதிப்பீடு. மருத்துவரை அணுகவும்.',
        'cows-title': 'என் மாடுகள்',
        'cows-subtitle': 'உங்கள் மந்தை பதிவு மற்றும் சுகாதார நிலையை நிர்வகிக்கவும்.',
        'btn-add-cow': 'புதிய பசுவைச் சேர்க்கவும்',
        'hdr-herd-list': 'மந்தை பட்டியல்',
        'tbl-tag': 'குறிச்சொல் ஐடி',
        'tbl-age': 'வயது',
        'tbl-health': 'ஆரோக்கியம்',
        'tbl-owner': 'உரிமையாளர்',
        'ph-tag': 'குறிச்சொல் ஐடி',
        'ph-age': 'வயது',
        'ph-owner': 'உரிமையாளர்',
        'opt-select-status': 'நிலையைத் தேர்ந்தெடுக்கவும்',
        'opt-healthy': 'ஆரோக்கியமான',
        'opt-sick': 'நோய்வாய்ப்பட்ட',
        'opt-pregnant': 'கர்ப்பிணி',
        'srv-title': 'எங்கள் சேவைகள்',
        'srv-subtitle': 'நவீன கால்நடை மேலாண்மைக்கான விரிவான கருவிகள்.',
        'srv-health-hub': 'சுகாதார மையம்',
        'srv-health-desc': 'AI கணிப்பு & நோய் ஸ்கேனிங்',
        'srv-trade': 'ஸ்மார்ட் வர்த்தகம்',
        'srv-trade-desc': 'நியாயமான விலை மதிப்பீடு & சந்தை போக்குகள்',
        'srv-advisory': 'ஆலோசனை',
        'srv-advisory-desc': 'நிபுணர் வழிகாட்டுதல் & சிறந்த நடைமுறைகள்',
        'srv-grants': 'அரசு மானியங்கள்',
        'srv-grants-desc': 'மானியம் மற்றும் நிதி உதவித் தகவல்',
        'dash-active-trades': 'செயலில் உள்ள வர்த்தகம்',
        'dash-govt-grants': 'அரசு மானியங்கள்',
        'dash-health-ai': 'ஹெல்த் ஏஐ',
        'lbl-breed': 'இனம்',
        'lbl-weight': 'எடை (kg)',
        'lbl-age': 'வயது (மாதங்கள்)',
        'lbl-milk': 'பால் (லிட்டர்)',
        'lbl-preg': 'கர்ப்பம் (மாதம்)',
        'btn-calc': 'விலையை கணக்கிடு',
        'btn-scan': 'ஸ்கேன் செய்',
        'total-cattle': 'மொத்த கால்நடைகள்',
        'health-alerts': 'சுகாதார எச்சரிக்கைகள்',
        'market-rate': 'சராசரி உள்ளூர் விலை',
        'weather': 'வானிலை',
        'recent-activity': 'சமீபத்திய செயல்பாடு',
        'opt-gir': 'கிர் (நாட்டு மாடு)',
        'opt-sahiwal': 'சாஹிவால்',
        'opt-redsindhi': 'ரெட் சிந்தி',
        'opt-tharparkar': 'தார்பார்கர்',
        'opt-jersey': 'ஜெர்சி',
        'opt-holstein': 'ஹால்ஸ்டீன்',

        'dash-infra': 'பண்ணை கட்டமைப்பு',
        'subtitle-dashboard': 'ஸ்மார்ட் பண்ணை மேலாண்மை அமைப்பு',
        'status-db': 'DB இணைக்கப்பட்டது',
        'status-live': 'நேரலை',
        'unit-kg': '/kg',
        'chart-milk': 'பால் உற்பத்தி (லிட்டர்)',
        'disclaimer-gps': '*உங்கள் GPS இருப்பிடத்தின் அடிப்படையில்',
        'dash-acres': 'ஏக்கர்',
        'dash-sheds': 'கொட்டகைகள்',
        'dash-cctv': 'CCTV நேரலை',
        'dash-feed': 'தீவன இருப்பு',
        'dash-water': 'தண்ணீர் தொட்டி',
        'dash-trends': 'உற்பத்தி போக்குகள்',
        'dash-sick': 'நோய் வரலாறு',
        'dash-no-sick': 'பதிவுகள் எதுவும் இல்லை.',
        'dash-vets': 'அருகிலுள்ள கால்நடை மருத்துவமனைகள்',
        'dash-nav': 'செல்லவும்',
        'dash-view-map': 'வரைபடத்தில் காண்க',
        'trade-subtitle': 'AI மதிப்பீடு மற்றும் சான்றிதழ்',
        'grp-desi': 'இந்திய உள்நாட்டு (தேசி)',
        'grp-exotic': 'வெளிநாட்டு / கலப்பின',
        'opt-murrah': 'முர்ரா எருமை',
        'msg-analyzing': 'AI பகுப்பாய்வு செய்கிறது...',
        'hint-qr': 'Google Lens பயன்படுத்தவும் • விவரங்களைச் சேமிக்கவும்',
        'lbl-forecast': '6 மாத முன்னறிவிப்பு',
        'adv-critical': 'முக்கிய கவனம் தேவை. உடனடியாக மருத்துவரை அணுகவும்.',

        'cert-title': 'மதிப்பீட்டு அறிக்கை',
        'cert-subtitle': 'Cattle Care AI மூலம் சான்றளிக்கப்பட்டது',
        'cert-value': 'மதிப்பிடப்பட்ட விலை',
        'cert-confidence': 'நம்பகத்தன்மை',
        'cert-proof': 'விலை விவரம் (ஆதாரம்)',
        'cert-base': 'எடை மதிப்பு',
        'cert-milk': 'பால் போனஸ்',
        'cert-preg': 'கர்ப்ப போனஸ்',
        'cert-age': 'வயது தேய்மானம்',
        'cert-analysis': 'AI நிபுணர் பகுப்பாய்வு',
        'cert-footer': 'ஜெமினி AI மூலம் உருவாக்கப்பட்டது',
        'btn-download': 'PDF பதிவிறக்கம்',
        'qr-scan': 'தொலைபேசியில் சேமிக்க ஸ்கேன் செய்யவும்',

        'adv-chat-placeholder': 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்யவும்...',
        'adv-chat-send': 'அனுப்பு',
        'adv-welcome-msg': 'வணக்கம்! நான் உங்கள் AI கால்நடை நிபுணர். இன்று உங்கள் கால்நடைகளுக்கு நான் எவ்வாறு உதவ முடியும்?',
        'adv-welcome-msg': 'வணக்கம்! நான் உங்கள் AI கால்நடை நிபுணர். இன்று உங்கள் கால்நடைகளுக்கு நான் எவ்வாறு உதவ முடியும்?',
        'adv-typing': 'நிபுணர் தட்டச்சு செய்கிறார்...',

        'btn-camera': 'கேமராவைத் திற',
        'btn-capture': 'புகைப்படம் எடு',
        'btn-retake': 'மீண்டும் எடு',
        'lbl-analyzing': 'AI படத்தை ஸ்கேன் செய்கிறது...',
        'p-disease-guide': 'உடனடி நோயறிதலுக்கு கேமராவை பாதிக்கப்பட்ட பகுதிக்கு (தோல், கண்கள், வாய்) காட்டவும்.'
    },
    'kn-IN': {
        'title-dashboard': 'ಜಾನುವಾರು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'title-trade': 'ಸ್ಮಾರ್ಟ್ ವ್ಯಾಪಾರ',
        'title-disease': 'ರೋಗ ಪತ್ತೆ',
        'title-advisory': 'ತಜ್ಞರ ಸಲಹೆ',
        'logo': 'ಕ್ಯಾಟಲ್ ಕೇರ್',
        'nav-dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        'nav-trade': 'ಸ್ಮಾರ್ಟ್ ವ್ಯಾಪಾರ',
        'nav-disease': 'ರೋಗ ಪತ್ತೆ',
        'nav-advisory': 'ಸಲಹೆ',
        'nav-cows': 'ನನ್ನ ಹಸುಗಳು',
        'nav-services': 'ಸೇವೆಗಳು',
        'nav-alerts': 'ಎಚ್ಚರಿಕೆಗಳು',
        'nav-settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'alerts-title': 'ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಸೂಚನೆಗಳು',
        'alerts-subtitle': 'ನಿಮ್ಮ ಹಿಂಡಿನ ಬಗ್ಗೆ ಪ್ರಮುಖ ನವೀಕರಣಗಳು.',
        'alerts-empty': 'ಯಾವುದೇ ಹೊಸ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.',
        'settings-title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        'settings-subtitle': 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
        'stg-account': 'ರೈತ ಖಾತೆ',
        'stg-signout': 'ಲಾಗ್ ಔಟ್',
        'stg-pref': 'ಆದ್ಯತೆಗಳು',
        'stg-lang': 'ಭಾಷೆ',
        'stg-theme': 'ಥೀಮ್',
        'stg-notif': 'ಸೂಚನೆಗಳು',
        'stg-push': 'ಪುಶ್ ಸೂಚನೆಗಳು',
        'stg-email': 'ಇಮೇಲ್ ಎಚ್ಚರಿಕೆಗಳು',
        'stg-security': 'ಭದ್ರತೆ',
        'stg-change-pw': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
        'stg-save': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
        'grants-title': 'ಸರ್ಕಾರಿ ಅನುದಾನಗಳು',
        'grants-subtitle': 'ನಿಮ್ಮ ಫಾರ್ಮ್‌ಗಾಗಿ ಲಭ್ಯವಿರುವ ಅನುದಾನ ಮತ್ತು ಸಹಾಯಧನವನ್ನು ಹುಡುಕಿ.',
        'grants-new': 'ಹೊಸ ಅನುದಾನ (ನಿರ್ವಾಹಕ)',
        'grants-schemes': 'ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು',
        'grants-apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
        'predict-title': 'ಆರೋಗ್ಯ ಮುನ್ಸೂಚನೆ AI',
        'predict-subtitle': 'ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಪ್ರಮುಖ ಚಿಹ್ನೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
        'pred-enter-vitals': 'ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
        'pred-temp': 'ತಾಪಮಾನ (°C)',
        'pred-appetite': 'ಹಸಿವು (1-10)',
        'pred-mobility': 'ಚಲನೆ (1-10)',
        'pred-run': 'ಮುನ್ಸೂಚನೆ ನಡೆಸಿ',
        'pred-analyzing': 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
        'pred-result-placeholder': 'ಫಲಿತಾಂಶವನ್ನು ನೋಡಲು ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
        'pred-note': 'ಗಮನಿಸಿ: ಇದು AI ಅಂದಾಜು. ದಯವಿಟ್ಟು ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
        'cows-title': 'ನನ್ನ ಹಸುಗಳು',
        'cows-subtitle': 'ನಿಮ್ಮ ಹಿಂಡಿನ ನೋಂದಣಿ ಮತ್ತು ಆರೋಗ್ಯ ಸ್ಥಿತಿಯನ್ನು ನಿರ್ವಹಿಸಿ.',
        'btn-add-cow': 'ಹೊಸ ಹಸುವನ್ನು ಸೇರಿಸಿ',
        'hdr-herd-list': 'ಹಿಂಡಿನ ಪಟ್ಟಿ',
        'tbl-tag': 'ಟ್ಯಾಗ್ ಐಡಿ',
        'tbl-age': 'ವಯಸ್ಸು',
        'tbl-health': 'ಆರೋಗ್ಯ',
        'tbl-owner': 'ಮಾಲೀಕರು',
        'ph-tag': 'ಟ್ಯಾಗ್ ಐಡಿ',
        'ph-age': 'ವಯಸ್ಸು',
        'ph-owner': 'ಮಾಲೀಕರು',
        'opt-select-status': 'ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        'opt-healthy': 'ಆರೋಗ್ಯಕರ',
        'opt-sick': 'ಅನಾರೋಗ್ಯ',
        'opt-pregnant': 'ಗರ್ಭಿಣಿ',
        'srv-title': 'ನಮ್ಮ ಸೇವೆಗಳು',
        'srv-subtitle': 'ಆಧುನಿಕ ಜಾನುವಾರು ನಿರ್ವಹಣೆಗೆ ಸಮಗ್ರ ಪರಿಕರಗಳು.',
        'srv-health-hub': 'ಆರೋಗ್ಯ ಕೇಂದ್ರ',
        'srv-health-desc': 'AI ಮುನ್ಸೂಚನೆ ಮತ್ತು ರೋಗ ಸ್ಕ್ಯಾನಿಂಗ್',
        'srv-trade': 'ಸ್ಮಾರ್ಟ್ ವ್ಯಾಪಾರ',
        'srv-trade-desc': 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಅಂದಾಜು ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು',
        'srv-advisory': 'ಸಲಹೆ',
        'srv-advisory-desc': 'ತಜ್ಞರ ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಉತ್ತಮ ಅಭ್ಯಾಸಗಳು',
        'srv-grants': 'ಸರ್ಕಾರಿ ಅನುದಾನಗಳು',
        'srv-grants-desc': 'ಸಬ್ಸಿಡಿ ಮತ್ತು ಆರ್ಥಿಕ ಸಹಾಯ ಮಾಹಿತಿ',
        'dash-active-trades': 'ಸಕ್ರಿಯ ವ್ಯಾಪಾರಗಳು',
        'dash-govt-grants': 'ಸರ್ಕಾರಿ ಅನುದಾನಗಳು',
        'dash-health-ai': 'ಹೆಲ್ತ್ ಎಐ',
        'lbl-breed': 'ತಳಿ',
        'lbl-weight': 'ತೂಕ (ಕೆಜಿ)',
        'lbl-age': 'ವಯಸ್ಸು (ತಿಂಗಳು)',
        'lbl-milk': 'ಹಾಲು (ಲೀಟರ್)',
        'lbl-preg': 'ಗರ್ಭಾವಸ್ಥೆ (ತಿಂಗಳು)',
        'btn-calc': 'ಬೆಲೆ ಲೆಕ್ಕಹಾಕಿ',
        'btn-scan': 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
        'total-cattle': 'ಒಟ್ಟು ಜಾನುವಾರು',
        'health-alerts': 'ಆರೋಗ್ಯ ಎಚ್ಚರಿಕೆಗಳು',
        'market-rate': 'ಸರಾಸರಿ ಸ್ಥಳೀಯ ದರ',
        'weather': 'ಹವಾಮಾನ',
        'recent-activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
        'opt-gir': 'ಗಿರ್ (ದೇಸಿ)',
        'opt-sahiwal': 'ಸಾಹಿವಾಲ್',
        'opt-redsindhi': 'ಕೆಂಪು ಸಿಂಧಿ',
        'opt-tharparkar': 'ಥಾರ್ಪಾರ್ಕರ್',
        'opt-jersey': 'ಜರ್ಸಿ',
        'opt-holstein': 'ಹೋಲ್ಸ್ಟೀನ್',

        'dash-infra': 'ಫಾರ್ಮ್ ಮೂಲಸೌಕರ್ಯ',
        'subtitle-dashboard': 'ಸ್ಮಾರ்ட் ಫಾರ್ಮ್ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ',
        'status-db': 'DB ಸಂಪರ್ಕಗೊಂಡಿದೆ',
        'status-live': 'ಲೈವ್',
        'unit-kg': '/ಕೆಜಿ',
        'chart-milk': 'ಹಾಲಿನ ಇಳುವರಿ (ಲೀಟರ್)',
        'disclaimer-gps': '*ನಿಮ್ಮ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಆಧರಿಸಿ',
        'dash-acres': 'ಎಕರೆ',
        'dash-sheds': 'ಶೆಡ್ಗಳು',
        'dash-cctv': 'CCTV ಲೈವ್',
        'dash-feed': 'ಮೇವು ಸಂಗ್ರಹ',
        'dash-water': 'ನೀರಿನ ಟ್ಯಾಂಕ್',
        'dash-trends': 'ಉತ್ಪಾದನೆ ಪ್ರವೃತ್ತಿಗಳು',
        'dash-sick': 'ಅನಾರೋಗ್ಯ ಇತಿಹಾಸ',
        'dash-no-sick': 'ಯಾವುದೇ ದಾಖಲೆಗಳಿಲ್ಲ.',
        'dash-vets': 'ಹತ್ತಿರದ ಪಶುವೈದ್ಯಕೀಯ ಆಸ್ಪತ್ರೆಗಳು',
        'dash-nav': 'ನ್ಯಾವಿಗೇಟ್',
        'dash-view-map': 'ನಕ್ಷೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
        'trade-subtitle': 'AI ಚಾಲಿತ ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ',
        'grp-desi': 'ಭಾರತೀಯ ದೇಶೀಯ (ದೇಸಿ)',
        'grp-exotic': 'ವಿದೇಶಿ / ಮಿಶ್ರತಳಿ',
        'opt-murrah': 'ಮುರ್ರ ಎಮ್ಮೆ',
        'msg-analyzing': 'AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
        'hint-qr': 'Google Lens ಬಳಸಿ • ವಿವರಗಳನ್ನು ತಕ್ಷಣ ಉಳಿಸಿ',
        'lbl-forecast': '6-ತಿಂಗಳ ಮುನ್ಸೂಚನೆ',
        'adv-critical': 'ತುರ್ತು ಗಮನ ನೀಡಬೇಕಿದೆ. ತಕ್ಷಣ ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',

        'cert-title': 'ಮೌಲ್ಯಮಾಪನ ವರದಿ',
        'cert-subtitle': 'ಕ್ಯಾಟಲ್ ಕೇರ್ AI ನಿಂದ ಪ್ರಮಾಣೀಕರಿಸಲಾಗಿದೆ',
        'cert-value': 'ಅಂದಾಜು ಬೆಲೆ',
        'cert-confidence': 'ನಿಖರತೆ',
        'cert-proof': 'ಬೆಲೆ ವಿವರ (ಪುರಾವೆ)',
        'cert-base': 'ತೂಕದ ಮೌಲ್ಯ',
        'cert-milk': 'ಹಾಲಿನ ಬೋನಸ್',
        'cert-preg': 'ಗರ್ಭಾವಸ್ಥೆಯ ಬೋನಸ್',
        'cert-age': 'ವಯಸ್ಸಿನ ಕಡಿತ',
        'cert-analysis': 'AI ತಜ್ಞರ ವಿಶ್ಲೇಷಣೆ',
        'cert-footer': 'ಜೆಮಿನಿ AI ನಿಂದ ರಚಿಸಲಾಗಿದೆ',
        'btn-download': 'PDF ಡೌನ್‌ಲೋಡ್',
        'qr-scan': 'ಫೋನ್‌ನಲ್ಲಿ ಉಳಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',

        'adv-chat-placeholder': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
        'adv-chat-send': 'ಕಳುಹಿಸಿ',
        'adv-welcome-msg': 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಪಶುವೈದ್ಯಕೀಯ ತಜ್ಞ. ಇಂದು ನಾನು ನಿಮ್ಮ ಜಾನುವಾರುಗಳಿಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
        'adv-welcome-msg': 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಪಶುವೈದ್ಯಕೀಯ ತಜ್ಞ. ಇಂದು ನಾನು ನಿಮ್ಮ ಜಾನುವಾರುಗಳಿಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
        'adv-typing': 'ತಜ್ಞರು ಬರೆಯುತ್ತಿದ್ದಾರೆ...',

        'btn-camera': 'ಕ್ಯಾಮರಾ ತೆರೆಯಿರಿ',
        'btn-capture': 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
        'btn-retake': 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
        'lbl-analyzing': 'AI ಚಿತ್ರವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಿದೆ...',
        'p-disease-guide': 'ತ್ವರಿತ ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಕ್ಯಾಮೆರಾವನ್ನು ಪೀಡಿತ ಪ್ರದೇಶದ (ಚರ್ಮ, ಕಣ್ಣುಗಳು, ಬಾಯಿ) ಕಡೆಗೆ ಇರಿಸಿ.'
    },
    'ml-IN': {
        'title-dashboard': 'കന്നുകാലി ഡാഷ്‌ബോർഡ്',
        'title-trade': 'വ്യാപാരം (ട്രേഡ്)',
        'title-disease': 'രോഗ പരിശോധന',
        'title-advisory': 'വിദഗ്ദ്ധ ഉപദേശം',
        'logo': 'കാറ്റിൽ കെയർ',
        'nav-dashboard': 'ഡാഷ്ബോർഡ്',
        'nav-trade': 'സ്മാർട്ട് ട്രേഡ്',
        'nav-disease': 'രോഗ പരിശോധന',
        'nav-advisory': 'ഉപദേശം',
        'nav-cows': 'എന്റെ കന്നുകാലികൾ',
        'nav-services': 'സേവനങ്ങൾ',
        'nav-alerts': 'അറിയിപ്പുകൾ',
        'nav-settings': 'ക്രമീകരണങ്ങൾ',
        'alerts-title': 'അറിയിപ്പുകൾ',
        'alerts-subtitle': 'നിങ്ങളുടെ കന്നുകാലികളെക്കുറിച്ചുള്ള പ്രധാന അപ്‌ഡേറ്റുകൾ.',
        'alerts-empty': 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല.',
        'settings-title': 'ക്രമീകരണങ്ങൾ',
        'settings-subtitle': 'നിങ്ങളുടെ അക്കൗണ്ടും മുൻഗണനകളും നിയന്ത്രിക്കുക.',
        'stg-account': 'കർഷക അക്കൗണ്ട്',
        'stg-signout': 'പുറത്തുകടക്കുക',
        'stg-pref': 'മുൻഗണനകൾ',
        'stg-lang': 'ഭാഷ',
        'stg-theme': 'തീം',
        'stg-notif': 'അറിയിപ്പുകൾ',
        'stg-push': 'പുഷ് അറിയിപ്പുകൾ',
        'stg-email': 'ഇമെയിൽ അലേർട്ടുകൾ',
        'stg-security': 'സുരക്ഷ',
        'stg-change-pw': 'പാസ്‌വേഡ് മാറ്റുക',
        'stg-save': 'മാറ്റങ്ങൾ വരുത്തുക',
        'grants-title': 'സർക്കാർ ഗ്രാന്റുകൾ',
        'grants-subtitle': 'നിങ്ങളുടെ ഫാമിന് ലഭ്യമായ ഗ്രാന്റുകളും സബ്‌സിഡികളും കണ്ടെത്തുക.',
        'grants-new': 'പുതിയ ഗ്രാന്റ് (അഡ്മിൻ)',
        'grants-schemes': 'ലഭ്യമായ പദ്ധതികൾ',
        'grants-apply': 'അപേക്ഷിക്കുക',
        'predict-title': 'ഹെൽത്ത് എഐ',
        'predict-subtitle': 'ആരോഗ്യ പ്രശ്നങ്ങൾ കണ്ടെത്താൻ ലക്ഷണങ്ങൾ പരിശോധിക്കുക.',
        'pred-enter-vitals': 'വിവരങ്ങൾ നൽകുക',
        'pred-temp': 'താപനില (°C)',
        'pred-appetite': 'വിശപ്പ് (1-10)',
        'pred-mobility': 'ചലനം (1-10)',
        'pred-run': 'പരിശോധിക്കുക',
        'pred-analyzing': 'വിശകലനം ചെയ്യുന്നു...',
        'pred-result-placeholder': 'ഫലം കാണാൻ വിവരങ്ങൾ നൽകുക.',
        'pred-note': 'ശ്രദ്ധിക്കുക: ഇതൊരു AI നിഗമനമാണ്. ദയവായി ഡോക്ടറെ കാണുക.',
        'cows-title': 'എന്റെ കന്നുകാലികൾ',
        'cows-subtitle': 'നിങ്ങളുടെ കന്നുകാലി രജിസ്ട്രിയും ആരോഗ്യ നിലയും നിയന്ത്രിക്കുക.',
        'btn-add-cow': 'പുതിയ പശുവിനെ ചേർക്കുക',
        'hdr-herd-list': 'കന്നുകാലി ലിസ്റ്റ്',
        'tbl-tag': 'ടാഗ് ഐഡി',
        'tbl-age': 'പ്രായം',
        'tbl-health': 'ആരോഗ്യം',
        'tbl-owner': 'ഉടമ',
        'ph-tag': 'ടാഗ് ഐഡി',
        'ph-age': 'പ്രായം',
        'ph-owner': 'ഉടമ',
        'opt-select-status': 'അവസ്ഥ തിരഞ്ഞെടുക്കുക',
        'opt-healthy': 'ആരോഗ്യമുള്ള',
        'opt-sick': 'രോഗബാധിതൻ',
        'opt-pregnant': 'ഗർഭിണി',
        'srv-title': 'ഞങ്ങളുടെ സേവനങ്ങൾ',
        'srv-subtitle': 'നൂതന കന്നുകാലി പരിപാലനത്തിനുള്ള സമഗ്ര ഉപകരണങ്ങൾ.',
        'srv-health-hub': 'ഹെൽത്ത് ഹബ്',
        'srv-health-desc': 'AI പ്രവചനവും രോഗ സ്കാനിംഗും',
        'srv-trade': 'സ്മാർട്ട് ട്രേഡ്',
        'srv-trade-desc': 'ന്യായമായ വില കണക്കാക്കലും വിപണി പ്രവണതകളും',
        'srv-advisory': 'ഉപദേശം',
        'srv-advisory-desc': 'വിദഗ്ദ്ധ നിർദ്ദേശങ്ങളും മികച്ച രീതികളും',
        'srv-grants': 'സർക്കാർ ഗ്രാന്റുകൾ',
        'srv-grants-desc': 'സബ്‌സിഡിയും സാമ്പത്തിക സഹായ വിവരങ്ങളും',
        'dash-active-trades': 'സജീവ വ്യാപാരങ്ങൾ',
        'dash-govt-grants': 'സർക്കാർ ഗ്രാന്റുകൾ',
        'dash-health-ai': 'ഹെൽത്ത് എഐ',
        'lbl-breed': 'ഇനം',
        'lbl-weight': 'ഭാരം (കിലോ)',
        'lbl-age': 'പ്രായം (മാസം)',
        'lbl-milk': 'പാൽ (ലിറ്റർ)',
        'lbl-preg': 'ഗർഭകാലം (മാസം)',
        'btn-calc': 'വില കണക്കാക്കുക',
        'btn-scan': 'സ്കാൻ ചെയ്യുക',
        'total-cattle': 'ആകെ കന്നുകാലികൾ',
        'health-alerts': 'അലേർട്ടുകൾ',
        'market-rate': 'ശരാശരി പ്രാദേശിക നിരക്ക്',
        'weather': 'കാലാവസ്ഥ',
        'recent-activity': 'സമീപകാല പ്രവർത്തനങ്ങൾ',
        'opt-gir': 'ഗീർ (നാടൻ)',
        'opt-sahiwal': 'സാഹിവാൾ',
        'opt-redsindhi': 'റെഡ് സിന്ധി',
        'opt-tharparkar': 'തർപാർക്കർ',
        'opt-jersey': 'ജേഴ്സി',
        'opt-holstein': 'ഹോൾസ്റ്റീൻ',

        'dash-infra': 'ഫാം ഇൻഫ്രാസ്ട്രക്ചർ',
        'subtitle-dashboard': 'സ്മാർട്ട് ഫാം മാനേജ്മെന്റ് സിസ്റ്റം',
        'status-db': 'DB ബന്ധിപ്പിച്ചിരിക്കുന്നു',
        'status-live': 'ലൈവ്',
        'unit-kg': '/കിലോ',
        'chart-milk': 'പാൽ ഉൽപ്പാദനം (ലിറ്റർ)',
        'disclaimer-gps': '*നിങ്ങളുടെ GPS സ്ഥാനം അടിസ്ഥാനമാക്കി',
        'dash-acres': 'ഏക്കർ',
        'dash-sheds': 'ഷെഡുകൾ',
        'dash-cctv': 'CCTV ലൈവ്',
        'dash-feed': 'തീറ്റ ശേഖരം',
        'dash-water': 'വാട്ടർ ടാങ്ക്',
        'dash-trends': 'ഉൽപ്പാദന പ്രവണതകൾ',
        'dash-sick': 'രോഗ ചരിത്രം',
        'dash-no-sick': 'രേഖകൾ കണ്ടെത്തിയില്ല.',
        'dash-vets': 'അടുത്തുള്ള വെറ്റിനറി ആശുപത്രികൾ',
        'dash-nav': 'നാവിഗേറ്റ്',
        'dash-view-map': 'മാപ്പിൽ കാണുക',
        'trade-subtitle': 'AI അധിഷ്ഠിത മൂല്യനിർണ്ണയവും സാക്ഷ്യപ്പെടുത്തലും',
        'grp-desi': 'ഇന്ത്യൻ തദ്ദേശീയ (നാടൻ)',
        'grp-exotic': 'വിദേശ / സങ്കരയിനം',
        'opt-murrah': 'മുറ എരുമ',
        'msg-analyzing': 'AI വിശകലനം ചെയ്യുന്നു...',
        'hint-qr': 'Google Lens ഉപയോഗിക്കുക • വിശദാംശങ്ങൾ സേവ് ചെയ്യുക',
        'lbl-forecast': '6-മാസത്തെ പ്രവചനം',
        'adv-critical': 'അടിയന്തിര ശ്രദ്ധ ആവശ്യമാണ്. ഉടൻ വെറ്റിനറി ഡോക്ടറെ സമീപിക്കുക.',

        'cert-title': 'മൂല്യനിർണ്ണയ റിപ്പോർട്ട്',
        'cert-subtitle': 'Cattle Care AI സാക്ഷ്യപ്പെടുത്തിയത്',
        'cert-value': 'കണക്കാക്കിയ വില',
        'cert-confidence': 'കൃത്യത',
        'cert-proof': 'വില വിവരങ്ങൾ (തെളിവ്)',
        'cert-base': 'ഭാരത്തിന്റെ മൂല്യം',
        'cert-milk': 'പാൽ ബോണസ്',
        'cert-preg': 'ഗർഭകാല ബോണസ്',
        'cert-age': 'പ്രായത്തിന്റെ കുറവ്',
        'cert-analysis': 'AI വിദഗ്ദ്ധ വിശകലനം',
        'cert-footer': 'ജെമിനി AI തയ്യാറാക്കിയത്',
        'btn-download': 'PDF ഡൗൺലോഡ്',
        'qr-scan': 'ഫോണിൽ സേവ് ചെയ്യാൻ സ്കാൻ ചെയ്യുക',

        'adv-chat-placeholder': 'നിങ്ങളുടെ ചോദ്യം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
        'adv-chat-send': 'അയക്കുക',
        'adv-welcome-msg': 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ AI വെറ്ററിനറി വിദഗ്ദ്ധനാണ്. ഇന്ന് എനിക്ക് എങ്ങനെ സഹായിക്കാനാകും?',
        'adv-welcome-msg': 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ AI വെറ്ററിനറി വിദഗ്ദ്ധനാണ്. ഇന്ന് എനിക്ക് എങ്ങനെ സഹായിക്കാനാകും?',
        'adv-typing': 'വിദഗ്ദ്ധൻ ടൈപ്പ് ചെയ്യുന്നു...',

        'btn-camera': 'ക്യാമറ തുറക്കുക',
        'btn-capture': 'ഫോട്ടോ എടുക്കുക',
        'btn-retake': 'വീണ്ടും എടുക്കുക',
        'lbl-analyzing': 'AI ചിത്രം സ്കാൻ ചെയ്യുന്നു...',
        'p-disease-guide': 'രോഗനിർണ്ണയത്തിനായി ക്യാമറ ബാധിത പ്രദേശത്തേക്ക് (ചർമ്മം, കണ്ണുകൾ, വായ) പിടിക്കുക.'
    }
};

export const LanguageProvider = ({ children }) => {
    const [currentLang, setCurrentLang] = useState('en-US');

    const t = (key) => {
        return translations[currentLang][key] || translations['en-US'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ currentLang, setCurrentLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
